/*
Symbiotic RFQ Backend Internal API

Internal RFQ backend API: discount listing and resolution.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackendinternal

import (
	"encoding/json"
	"fmt"
)

// checks if the ResolveDiscountResponseOneOf1DiscountsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResolveDiscountResponseOneOf1DiscountsInner{}

// ResolveDiscountResponseOneOf1DiscountsInner struct for ResolveDiscountResponseOneOf1DiscountsInner
type ResolveDiscountResponseOneOf1DiscountsInner struct {
	DiscountId           string                               `json:"discountId" validate:"regexp=^0x[a-fA-F0-9]{64}$"`
	Discount             ResolveDiscountResponseOneOfDiscount `json:"discount"`
	SignerSignature      string                               `json:"signerSignature" validate:"regexp=^0x[a-fA-F0-9]+$"`
	ProtocolDeadline     int64                                `json:"protocolDeadline"`
	ProtocolSignature    string                               `json:"protocolSignature" validate:"regexp=^0x[a-fA-F0-9]+$"`
	AdditionalProperties map[string]interface{}
}

type _ResolveDiscountResponseOneOf1DiscountsInner ResolveDiscountResponseOneOf1DiscountsInner

// NewResolveDiscountResponseOneOf1DiscountsInner instantiates a new ResolveDiscountResponseOneOf1DiscountsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolveDiscountResponseOneOf1DiscountsInner(discountId string, discount ResolveDiscountResponseOneOfDiscount, signerSignature string, protocolDeadline int64, protocolSignature string) *ResolveDiscountResponseOneOf1DiscountsInner {
	this := ResolveDiscountResponseOneOf1DiscountsInner{}
	this.DiscountId = discountId
	this.Discount = discount
	this.SignerSignature = signerSignature
	this.ProtocolDeadline = protocolDeadline
	this.ProtocolSignature = protocolSignature
	return &this
}

// NewResolveDiscountResponseOneOf1DiscountsInnerWithDefaults instantiates a new ResolveDiscountResponseOneOf1DiscountsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolveDiscountResponseOneOf1DiscountsInnerWithDefaults() *ResolveDiscountResponseOneOf1DiscountsInner {
	this := ResolveDiscountResponseOneOf1DiscountsInner{}
	return &this
}

// GetDiscountId returns the DiscountId field value
func (o *ResolveDiscountResponseOneOf1DiscountsInner) GetDiscountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DiscountId
}

// GetDiscountIdOk returns a tuple with the DiscountId field value
// and a boolean to check if the value has been set.
func (o *ResolveDiscountResponseOneOf1DiscountsInner) GetDiscountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiscountId, true
}

// SetDiscountId sets field value
func (o *ResolveDiscountResponseOneOf1DiscountsInner) SetDiscountId(v string) {
	o.DiscountId = v
}

// GetDiscount returns the Discount field value
func (o *ResolveDiscountResponseOneOf1DiscountsInner) GetDiscount() ResolveDiscountResponseOneOfDiscount {
	if o == nil {
		var ret ResolveDiscountResponseOneOfDiscount
		return ret
	}

	return o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value
// and a boolean to check if the value has been set.
func (o *ResolveDiscountResponseOneOf1DiscountsInner) GetDiscountOk() (*ResolveDiscountResponseOneOfDiscount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Discount, true
}

// SetDiscount sets field value
func (o *ResolveDiscountResponseOneOf1DiscountsInner) SetDiscount(v ResolveDiscountResponseOneOfDiscount) {
	o.Discount = v
}

// GetSignerSignature returns the SignerSignature field value
func (o *ResolveDiscountResponseOneOf1DiscountsInner) GetSignerSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignerSignature
}

// GetSignerSignatureOk returns a tuple with the SignerSignature field value
// and a boolean to check if the value has been set.
func (o *ResolveDiscountResponseOneOf1DiscountsInner) GetSignerSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignerSignature, true
}

// SetSignerSignature sets field value
func (o *ResolveDiscountResponseOneOf1DiscountsInner) SetSignerSignature(v string) {
	o.SignerSignature = v
}

// GetProtocolDeadline returns the ProtocolDeadline field value
func (o *ResolveDiscountResponseOneOf1DiscountsInner) GetProtocolDeadline() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ProtocolDeadline
}

// GetProtocolDeadlineOk returns a tuple with the ProtocolDeadline field value
// and a boolean to check if the value has been set.
func (o *ResolveDiscountResponseOneOf1DiscountsInner) GetProtocolDeadlineOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProtocolDeadline, true
}

// SetProtocolDeadline sets field value
func (o *ResolveDiscountResponseOneOf1DiscountsInner) SetProtocolDeadline(v int64) {
	o.ProtocolDeadline = v
}

// GetProtocolSignature returns the ProtocolSignature field value
func (o *ResolveDiscountResponseOneOf1DiscountsInner) GetProtocolSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProtocolSignature
}

// GetProtocolSignatureOk returns a tuple with the ProtocolSignature field value
// and a boolean to check if the value has been set.
func (o *ResolveDiscountResponseOneOf1DiscountsInner) GetProtocolSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProtocolSignature, true
}

// SetProtocolSignature sets field value
func (o *ResolveDiscountResponseOneOf1DiscountsInner) SetProtocolSignature(v string) {
	o.ProtocolSignature = v
}

func (o ResolveDiscountResponseOneOf1DiscountsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResolveDiscountResponseOneOf1DiscountsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["discountId"] = o.DiscountId
	toSerialize["discount"] = o.Discount
	toSerialize["signerSignature"] = o.SignerSignature
	toSerialize["protocolDeadline"] = o.ProtocolDeadline
	toSerialize["protocolSignature"] = o.ProtocolSignature

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResolveDiscountResponseOneOf1DiscountsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"discountId",
		"discount",
		"signerSignature",
		"protocolDeadline",
		"protocolSignature",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResolveDiscountResponseOneOf1DiscountsInner := _ResolveDiscountResponseOneOf1DiscountsInner{}

	err = json.Unmarshal(data, &varResolveDiscountResponseOneOf1DiscountsInner)

	if err != nil {
		return err
	}

	*o = ResolveDiscountResponseOneOf1DiscountsInner(varResolveDiscountResponseOneOf1DiscountsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "discountId")
		delete(additionalProperties, "discount")
		delete(additionalProperties, "signerSignature")
		delete(additionalProperties, "protocolDeadline")
		delete(additionalProperties, "protocolSignature")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResolveDiscountResponseOneOf1DiscountsInner struct {
	value *ResolveDiscountResponseOneOf1DiscountsInner
	isSet bool
}

func (v NullableResolveDiscountResponseOneOf1DiscountsInner) Get() *ResolveDiscountResponseOneOf1DiscountsInner {
	return v.value
}

func (v *NullableResolveDiscountResponseOneOf1DiscountsInner) Set(val *ResolveDiscountResponseOneOf1DiscountsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableResolveDiscountResponseOneOf1DiscountsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableResolveDiscountResponseOneOf1DiscountsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolveDiscountResponseOneOf1DiscountsInner(val *ResolveDiscountResponseOneOf1DiscountsInner) *NullableResolveDiscountResponseOneOf1DiscountsInner {
	return &NullableResolveDiscountResponseOneOf1DiscountsInner{value: val, isSet: true}
}

func (v NullableResolveDiscountResponseOneOf1DiscountsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolveDiscountResponseOneOf1DiscountsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
