/*
Symbiotic RFQ Backend Internal API

Internal RFQ backend API: discount listing and resolution.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackendinternal

import (
	"encoding/json"
	"fmt"
)

// checks if the ResolveDiscountRequestOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResolveDiscountRequestOneOf1{}

// ResolveDiscountRequestOneOf1 struct for ResolveDiscountRequestOneOf1
type ResolveDiscountRequestOneOf1 struct {
	DiscountIds          []string `json:"discountIds"`
	AdditionalProperties map[string]interface{}
}

type _ResolveDiscountRequestOneOf1 ResolveDiscountRequestOneOf1

// NewResolveDiscountRequestOneOf1 instantiates a new ResolveDiscountRequestOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolveDiscountRequestOneOf1(discountIds []string) *ResolveDiscountRequestOneOf1 {
	this := ResolveDiscountRequestOneOf1{}
	this.DiscountIds = discountIds
	return &this
}

// NewResolveDiscountRequestOneOf1WithDefaults instantiates a new ResolveDiscountRequestOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolveDiscountRequestOneOf1WithDefaults() *ResolveDiscountRequestOneOf1 {
	this := ResolveDiscountRequestOneOf1{}
	return &this
}

// GetDiscountIds returns the DiscountIds field value
func (o *ResolveDiscountRequestOneOf1) GetDiscountIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.DiscountIds
}

// GetDiscountIdsOk returns a tuple with the DiscountIds field value
// and a boolean to check if the value has been set.
func (o *ResolveDiscountRequestOneOf1) GetDiscountIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DiscountIds, true
}

// SetDiscountIds sets field value
func (o *ResolveDiscountRequestOneOf1) SetDiscountIds(v []string) {
	o.DiscountIds = v
}

func (o ResolveDiscountRequestOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResolveDiscountRequestOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["discountIds"] = o.DiscountIds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResolveDiscountRequestOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"discountIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResolveDiscountRequestOneOf1 := _ResolveDiscountRequestOneOf1{}

	err = json.Unmarshal(data, &varResolveDiscountRequestOneOf1)

	if err != nil {
		return err
	}

	*o = ResolveDiscountRequestOneOf1(varResolveDiscountRequestOneOf1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "discountIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResolveDiscountRequestOneOf1 struct {
	value *ResolveDiscountRequestOneOf1
	isSet bool
}

func (v NullableResolveDiscountRequestOneOf1) Get() *ResolveDiscountRequestOneOf1 {
	return v.value
}

func (v *NullableResolveDiscountRequestOneOf1) Set(val *ResolveDiscountRequestOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableResolveDiscountRequestOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableResolveDiscountRequestOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolveDiscountRequestOneOf1(val *ResolveDiscountRequestOneOf1) *NullableResolveDiscountRequestOneOf1 {
	return &NullableResolveDiscountRequestOneOf1{value: val, isSet: true}
}

func (v NullableResolveDiscountRequestOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolveDiscountRequestOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
