/*
Symbiotic RFQ Backend Internal API

Internal RFQ backend API: discount listing and resolution.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackendinternal

import (
	"encoding/json"
	"fmt"
)

// checks if the ResolveDiscountRequestOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResolveDiscountRequestOneOf2{}

// ResolveDiscountRequestOneOf2 struct for ResolveDiscountRequestOneOf2
type ResolveDiscountRequestOneOf2 struct {
	Adapter              string `json:"adapter" validate:"regexp=^0x[a-fA-F0-9]{40}$"`
	TokenToRedeem        string `json:"tokenToRedeem" validate:"regexp=^0x[a-fA-F0-9]{40}$"`
	AdditionalProperties map[string]interface{}
}

type _ResolveDiscountRequestOneOf2 ResolveDiscountRequestOneOf2

// NewResolveDiscountRequestOneOf2 instantiates a new ResolveDiscountRequestOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolveDiscountRequestOneOf2(adapter string, tokenToRedeem string) *ResolveDiscountRequestOneOf2 {
	this := ResolveDiscountRequestOneOf2{}
	this.Adapter = adapter
	this.TokenToRedeem = tokenToRedeem
	return &this
}

// NewResolveDiscountRequestOneOf2WithDefaults instantiates a new ResolveDiscountRequestOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolveDiscountRequestOneOf2WithDefaults() *ResolveDiscountRequestOneOf2 {
	this := ResolveDiscountRequestOneOf2{}
	return &this
}

// GetAdapter returns the Adapter field value
func (o *ResolveDiscountRequestOneOf2) GetAdapter() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Adapter
}

// GetAdapterOk returns a tuple with the Adapter field value
// and a boolean to check if the value has been set.
func (o *ResolveDiscountRequestOneOf2) GetAdapterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Adapter, true
}

// SetAdapter sets field value
func (o *ResolveDiscountRequestOneOf2) SetAdapter(v string) {
	o.Adapter = v
}

// GetTokenToRedeem returns the TokenToRedeem field value
func (o *ResolveDiscountRequestOneOf2) GetTokenToRedeem() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenToRedeem
}

// GetTokenToRedeemOk returns a tuple with the TokenToRedeem field value
// and a boolean to check if the value has been set.
func (o *ResolveDiscountRequestOneOf2) GetTokenToRedeemOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenToRedeem, true
}

// SetTokenToRedeem sets field value
func (o *ResolveDiscountRequestOneOf2) SetTokenToRedeem(v string) {
	o.TokenToRedeem = v
}

func (o ResolveDiscountRequestOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResolveDiscountRequestOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["adapter"] = o.Adapter
	toSerialize["tokenToRedeem"] = o.TokenToRedeem

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResolveDiscountRequestOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"adapter",
		"tokenToRedeem",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResolveDiscountRequestOneOf2 := _ResolveDiscountRequestOneOf2{}

	err = json.Unmarshal(data, &varResolveDiscountRequestOneOf2)

	if err != nil {
		return err
	}

	*o = ResolveDiscountRequestOneOf2(varResolveDiscountRequestOneOf2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "adapter")
		delete(additionalProperties, "tokenToRedeem")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResolveDiscountRequestOneOf2 struct {
	value *ResolveDiscountRequestOneOf2
	isSet bool
}

func (v NullableResolveDiscountRequestOneOf2) Get() *ResolveDiscountRequestOneOf2 {
	return v.value
}

func (v *NullableResolveDiscountRequestOneOf2) Set(val *ResolveDiscountRequestOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableResolveDiscountRequestOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableResolveDiscountRequestOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolveDiscountRequestOneOf2(val *ResolveDiscountRequestOneOf2) *NullableResolveDiscountRequestOneOf2 {
	return &NullableResolveDiscountRequestOneOf2{value: val, isSet: true}
}

func (v NullableResolveDiscountRequestOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolveDiscountRequestOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
