/*
Symbiotic RFQ Backend Internal API

Internal RFQ backend API: discount listing and resolution.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackendinternal

import (
	"encoding/json"
	"fmt"
)

// checks if the ResolveDiscountResponseOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResolveDiscountResponseOneOf{}

// ResolveDiscountResponseOneOf struct for ResolveDiscountResponseOneOf
type ResolveDiscountResponseOneOf struct {
	RequestId            string                               `json:"requestId"`
	DiscountId           string                               `json:"discountId" validate:"regexp=^0x[a-fA-F0-9]{64}$"`
	Discount             ResolveDiscountResponseOneOfDiscount `json:"discount"`
	SignerSignature      string                               `json:"signerSignature" validate:"regexp=^0x[a-fA-F0-9]+$"`
	ProtocolDeadline     int32                                `json:"protocolDeadline"`
	ProtocolSignature    string                               `json:"protocolSignature" validate:"regexp=^0x[a-fA-F0-9]+$"`
	AdditionalProperties map[string]interface{}
}

type _ResolveDiscountResponseOneOf ResolveDiscountResponseOneOf

// NewResolveDiscountResponseOneOf instantiates a new ResolveDiscountResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolveDiscountResponseOneOf(requestId string, discountId string, discount ResolveDiscountResponseOneOfDiscount, signerSignature string, protocolDeadline int32, protocolSignature string) *ResolveDiscountResponseOneOf {
	this := ResolveDiscountResponseOneOf{}
	this.RequestId = requestId
	this.DiscountId = discountId
	this.Discount = discount
	this.SignerSignature = signerSignature
	this.ProtocolDeadline = protocolDeadline
	this.ProtocolSignature = protocolSignature
	return &this
}

// NewResolveDiscountResponseOneOfWithDefaults instantiates a new ResolveDiscountResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolveDiscountResponseOneOfWithDefaults() *ResolveDiscountResponseOneOf {
	this := ResolveDiscountResponseOneOf{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *ResolveDiscountResponseOneOf) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *ResolveDiscountResponseOneOf) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *ResolveDiscountResponseOneOf) SetRequestId(v string) {
	o.RequestId = v
}

// GetDiscountId returns the DiscountId field value
func (o *ResolveDiscountResponseOneOf) GetDiscountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DiscountId
}

// GetDiscountIdOk returns a tuple with the DiscountId field value
// and a boolean to check if the value has been set.
func (o *ResolveDiscountResponseOneOf) GetDiscountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiscountId, true
}

// SetDiscountId sets field value
func (o *ResolveDiscountResponseOneOf) SetDiscountId(v string) {
	o.DiscountId = v
}

// GetDiscount returns the Discount field value
func (o *ResolveDiscountResponseOneOf) GetDiscount() ResolveDiscountResponseOneOfDiscount {
	if o == nil {
		var ret ResolveDiscountResponseOneOfDiscount
		return ret
	}

	return o.Discount
}

// GetDiscountOk returns a tuple with the Discount field value
// and a boolean to check if the value has been set.
func (o *ResolveDiscountResponseOneOf) GetDiscountOk() (*ResolveDiscountResponseOneOfDiscount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Discount, true
}

// SetDiscount sets field value
func (o *ResolveDiscountResponseOneOf) SetDiscount(v ResolveDiscountResponseOneOfDiscount) {
	o.Discount = v
}

// GetSignerSignature returns the SignerSignature field value
func (o *ResolveDiscountResponseOneOf) GetSignerSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignerSignature
}

// GetSignerSignatureOk returns a tuple with the SignerSignature field value
// and a boolean to check if the value has been set.
func (o *ResolveDiscountResponseOneOf) GetSignerSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignerSignature, true
}

// SetSignerSignature sets field value
func (o *ResolveDiscountResponseOneOf) SetSignerSignature(v string) {
	o.SignerSignature = v
}

// GetProtocolDeadline returns the ProtocolDeadline field value
func (o *ResolveDiscountResponseOneOf) GetProtocolDeadline() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProtocolDeadline
}

// GetProtocolDeadlineOk returns a tuple with the ProtocolDeadline field value
// and a boolean to check if the value has been set.
func (o *ResolveDiscountResponseOneOf) GetProtocolDeadlineOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProtocolDeadline, true
}

// SetProtocolDeadline sets field value
func (o *ResolveDiscountResponseOneOf) SetProtocolDeadline(v int32) {
	o.ProtocolDeadline = v
}

// GetProtocolSignature returns the ProtocolSignature field value
func (o *ResolveDiscountResponseOneOf) GetProtocolSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProtocolSignature
}

// GetProtocolSignatureOk returns a tuple with the ProtocolSignature field value
// and a boolean to check if the value has been set.
func (o *ResolveDiscountResponseOneOf) GetProtocolSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProtocolSignature, true
}

// SetProtocolSignature sets field value
func (o *ResolveDiscountResponseOneOf) SetProtocolSignature(v string) {
	o.ProtocolSignature = v
}

func (o ResolveDiscountResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResolveDiscountResponseOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	toSerialize["discountId"] = o.DiscountId
	toSerialize["discount"] = o.Discount
	toSerialize["signerSignature"] = o.SignerSignature
	toSerialize["protocolDeadline"] = o.ProtocolDeadline
	toSerialize["protocolSignature"] = o.ProtocolSignature

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResolveDiscountResponseOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestId",
		"discountId",
		"discount",
		"signerSignature",
		"protocolDeadline",
		"protocolSignature",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResolveDiscountResponseOneOf := _ResolveDiscountResponseOneOf{}

	err = json.Unmarshal(data, &varResolveDiscountResponseOneOf)

	if err != nil {
		return err
	}

	*o = ResolveDiscountResponseOneOf(varResolveDiscountResponseOneOf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requestId")
		delete(additionalProperties, "discountId")
		delete(additionalProperties, "discount")
		delete(additionalProperties, "signerSignature")
		delete(additionalProperties, "protocolDeadline")
		delete(additionalProperties, "protocolSignature")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResolveDiscountResponseOneOf struct {
	value *ResolveDiscountResponseOneOf
	isSet bool
}

func (v NullableResolveDiscountResponseOneOf) Get() *ResolveDiscountResponseOneOf {
	return v.value
}

func (v *NullableResolveDiscountResponseOneOf) Set(val *ResolveDiscountResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableResolveDiscountResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableResolveDiscountResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolveDiscountResponseOneOf(val *ResolveDiscountResponseOneOf) *NullableResolveDiscountResponseOneOf {
	return &NullableResolveDiscountResponseOneOf{value: val, isSet: true}
}

func (v NullableResolveDiscountResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolveDiscountResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
