---
misconfigurations:
  # Description: Image user should not be ‘root’
  # Link: https://avd.aquasec.com/misconfig/dockerfile/general/avd-ds-0002/
  - id: AVD-DS-0002
    statement: no really need for k8s
  # Description: No HEALTHCHECK defined
  # Link: https://avd.aquasec.com/misconfig/dockerfile/general/avd-ds-0026/
  - id: AVD-DS-0026
    statement: no really need for k8s

# vulnerabilities:
#   - id: CVE-2025-32414 # not fixed yet in base nginx image
#     expired_at: 2025-09-01
#   - id: CVE-2025-32415 # not fixed yet in base nginx image
#     expired_at: 2025-09-01
