/*
Symbiotic RFQ Backend API

Public RFQ backend API for approval checks, quote creation, order submission, and order polling.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackend

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApprovalCheckResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApprovalCheckResponse{}

// ApprovalCheckResponse struct for ApprovalCheckResponse
type ApprovalCheckResponse struct {
	RequestId string                        `json:"requestId"`
	Approval  ApprovalCheckResponseApproval `json:"approval"`
	Cancel    interface{}                   `json:"cancel"`
}

type _ApprovalCheckResponse ApprovalCheckResponse

// NewApprovalCheckResponse instantiates a new ApprovalCheckResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApprovalCheckResponse(requestId string, approval ApprovalCheckResponseApproval, cancel interface{}) *ApprovalCheckResponse {
	this := ApprovalCheckResponse{}
	this.RequestId = requestId
	this.Approval = approval
	this.Cancel = cancel
	return &this
}

// NewApprovalCheckResponseWithDefaults instantiates a new ApprovalCheckResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApprovalCheckResponseWithDefaults() *ApprovalCheckResponse {
	this := ApprovalCheckResponse{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *ApprovalCheckResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *ApprovalCheckResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *ApprovalCheckResponse) SetRequestId(v string) {
	o.RequestId = v
}

// GetApproval returns the Approval field value
func (o *ApprovalCheckResponse) GetApproval() ApprovalCheckResponseApproval {
	if o == nil {
		var ret ApprovalCheckResponseApproval
		return ret
	}

	return o.Approval
}

// GetApprovalOk returns a tuple with the Approval field value
// and a boolean to check if the value has been set.
func (o *ApprovalCheckResponse) GetApprovalOk() (*ApprovalCheckResponseApproval, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Approval, true
}

// SetApproval sets field value
func (o *ApprovalCheckResponse) SetApproval(v ApprovalCheckResponseApproval) {
	o.Approval = v
}

// GetCancel returns the Cancel field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ApprovalCheckResponse) GetCancel() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Cancel
}

// GetCancelOk returns a tuple with the Cancel field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApprovalCheckResponse) GetCancelOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Cancel) {
		return nil, false
	}
	return &o.Cancel, true
}

// SetCancel sets field value
func (o *ApprovalCheckResponse) SetCancel(v interface{}) {
	o.Cancel = v
}

func (o ApprovalCheckResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApprovalCheckResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	toSerialize["approval"] = o.Approval
	if o.Cancel != nil {
		toSerialize["cancel"] = o.Cancel
	}
	return toSerialize, nil
}

func (o *ApprovalCheckResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestId",
		"approval",
		"cancel",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApprovalCheckResponse := _ApprovalCheckResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApprovalCheckResponse)

	if err != nil {
		return err
	}

	*o = ApprovalCheckResponse(varApprovalCheckResponse)

	return err
}

type NullableApprovalCheckResponse struct {
	value *ApprovalCheckResponse
	isSet bool
}

func (v NullableApprovalCheckResponse) Get() *ApprovalCheckResponse {
	return v.value
}

func (v *NullableApprovalCheckResponse) Set(val *ApprovalCheckResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApprovalCheckResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApprovalCheckResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApprovalCheckResponse(val *ApprovalCheckResponse) *NullableApprovalCheckResponse {
	return &NullableApprovalCheckResponse{value: val, isSet: true}
}

func (v NullableApprovalCheckResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApprovalCheckResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
