/*
Symbiotic RFQ Backend API

Public RFQ backend API for approval checks, quote creation, order submission, and order polling.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackend

import (
	"bytes"
	"encoding/json"
)

// checks if the PublicQuoteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicQuoteResponse{}

// PublicQuoteResponse struct for PublicQuoteResponse
type PublicQuoteResponse struct {
	RequestId     string                           `json:"requestId"`
	Routing       string                           `json:"routing"`
	Quote         PublicQuoteResponseQuote         `json:"quote"`
	SignatureData PublicQuoteResponseSignatureData `json:"signatureData"`
	Quotes        []PublicQuoteResponseQuotesInner `json:"quotes,omitempty"`
}

type _PublicQuoteResponse PublicQuoteResponse

// NewPublicQuoteResponse instantiates a new PublicQuoteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicQuoteResponse(requestId string, routing string, quote PublicQuoteResponseQuote, signatureData PublicQuoteResponseSignatureData) *PublicQuoteResponse {
	this := PublicQuoteResponse{}
	this.RequestId = requestId
	this.Routing = routing
	this.Quote = quote
	this.SignatureData = signatureData
	return &this
}

// NewPublicQuoteResponseWithDefaults instantiates a new PublicQuoteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicQuoteResponseWithDefaults() *PublicQuoteResponse {
	this := PublicQuoteResponse{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *PublicQuoteResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *PublicQuoteResponse) SetRequestId(v string) {
	o.RequestId = v
}

// GetRouting returns the Routing field value
func (o *PublicQuoteResponse) GetRouting() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Routing
}

// GetRoutingOk returns a tuple with the Routing field value
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponse) GetRoutingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Routing, true
}

// SetRouting sets field value
func (o *PublicQuoteResponse) SetRouting(v string) {
	o.Routing = v
}

// GetQuote returns the Quote field value
func (o *PublicQuoteResponse) GetQuote() PublicQuoteResponseQuote {
	if o == nil {
		var ret PublicQuoteResponseQuote
		return ret
	}

	return o.Quote
}

// GetQuoteOk returns a tuple with the Quote field value
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponse) GetQuoteOk() (*PublicQuoteResponseQuote, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quote, true
}

// SetQuote sets field value
func (o *PublicQuoteResponse) SetQuote(v PublicQuoteResponseQuote) {
	o.Quote = v
}

// GetSignatureData returns the SignatureData field value
func (o *PublicQuoteResponse) GetSignatureData() PublicQuoteResponseSignatureData {
	if o == nil {
		var ret PublicQuoteResponseSignatureData
		return ret
	}

	return o.SignatureData
}

// GetSignatureDataOk returns a tuple with the SignatureData field value
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponse) GetSignatureDataOk() (*PublicQuoteResponseSignatureData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignatureData, true
}

// SetSignatureData sets field value
func (o *PublicQuoteResponse) SetSignatureData(v PublicQuoteResponseSignatureData) {
	o.SignatureData = v
}

// GetQuotes returns the Quotes field value if set, zero value otherwise.
func (o *PublicQuoteResponse) GetQuotes() []PublicQuoteResponseQuotesInner {
	if o == nil || IsNil(o.Quotes) {
		var ret []PublicQuoteResponseQuotesInner
		return ret
	}
	return o.Quotes
}

// GetQuotesOk returns a tuple with the Quotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponse) GetQuotesOk() ([]PublicQuoteResponseQuotesInner, bool) {
	if o == nil || IsNil(o.Quotes) {
		return nil, false
	}
	return o.Quotes, true
}

// HasQuotes returns a boolean if a field has been set.
func (o *PublicQuoteResponse) HasQuotes() bool {
	if o != nil && !IsNil(o.Quotes) {
		return true
	}

	return false
}

// SetQuotes gets a reference to the given []PublicQuoteResponseQuotesInner and assigns it to the Quotes field.
func (o *PublicQuoteResponse) SetQuotes(v []PublicQuoteResponseQuotesInner) {
	o.Quotes = v
}

func (o PublicQuoteResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicQuoteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	toSerialize["routing"] = o.Routing
	toSerialize["quote"] = o.Quote
	toSerialize["signatureData"] = o.SignatureData
	if !IsNil(o.Quotes) {
		toSerialize["quotes"] = o.Quotes
	}
	return toSerialize, nil
}

func (o *PublicQuoteResponse) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varPublicQuoteResponse := _PublicQuoteResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// Unknown fields tolerated (hack/openapi-relax-client.py): upstream may add
	// fields at any time without breaking us.
	err = decoder.Decode(&varPublicQuoteResponse)

	if err != nil {
		return err
	}

	*o = PublicQuoteResponse(varPublicQuoteResponse)

	return err
}

type NullablePublicQuoteResponse struct {
	value *PublicQuoteResponse
	isSet bool
}

func (v NullablePublicQuoteResponse) Get() *PublicQuoteResponse {
	return v.value
}

func (v *NullablePublicQuoteResponse) Set(val *PublicQuoteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicQuoteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicQuoteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicQuoteResponse(val *PublicQuoteResponse) *NullablePublicQuoteResponse {
	return &NullablePublicQuoteResponse{value: val, isSet: true}
}

func (v NullablePublicQuoteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicQuoteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
