/*
Symbiotic RFQ Backend API

Public RFQ backend API for approval checks, quote creation, order submission, and order polling.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackend

import (
	"encoding/json"
)

// checks if the LiquidityBatchResponseTokensInInnerTokenInInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LiquidityBatchResponseTokensInInnerTokenInInfo{}

// LiquidityBatchResponseTokensInInnerTokenInInfo struct for LiquidityBatchResponseTokensInInnerTokenInInfo
type LiquidityBatchResponseTokensInInnerTokenInInfo struct {
	Address              string `json:"address" validate:"regexp=^0x[a-fA-F0-9]{40}$"`
	Symbol               string `json:"symbol"`
	Name                 string `json:"name"`
	Decimals             int64  `json:"decimals"`
	AdditionalProperties map[string]interface{}
}

type _LiquidityBatchResponseTokensInInnerTokenInInfo LiquidityBatchResponseTokensInInnerTokenInInfo

// NewLiquidityBatchResponseTokensInInnerTokenInInfo instantiates a new LiquidityBatchResponseTokensInInnerTokenInInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLiquidityBatchResponseTokensInInnerTokenInInfo(address string, symbol string, name string, decimals int64) *LiquidityBatchResponseTokensInInnerTokenInInfo {
	this := LiquidityBatchResponseTokensInInnerTokenInInfo{}
	this.Address = address
	this.Symbol = symbol
	this.Name = name
	this.Decimals = decimals
	return &this
}

// NewLiquidityBatchResponseTokensInInnerTokenInInfoWithDefaults instantiates a new LiquidityBatchResponseTokensInInnerTokenInInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLiquidityBatchResponseTokensInInnerTokenInInfoWithDefaults() *LiquidityBatchResponseTokensInInnerTokenInInfo {
	this := LiquidityBatchResponseTokensInInnerTokenInInfo{}
	return &this
}

// GetAddress returns the Address field value
func (o *LiquidityBatchResponseTokensInInnerTokenInInfo) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *LiquidityBatchResponseTokensInInnerTokenInInfo) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *LiquidityBatchResponseTokensInInnerTokenInInfo) SetAddress(v string) {
	o.Address = v
}

// GetSymbol returns the Symbol field value
func (o *LiquidityBatchResponseTokensInInnerTokenInInfo) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *LiquidityBatchResponseTokensInInnerTokenInInfo) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *LiquidityBatchResponseTokensInInnerTokenInInfo) SetSymbol(v string) {
	o.Symbol = v
}

// GetName returns the Name field value
func (o *LiquidityBatchResponseTokensInInnerTokenInInfo) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LiquidityBatchResponseTokensInInnerTokenInInfo) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LiquidityBatchResponseTokensInInnerTokenInInfo) SetName(v string) {
	o.Name = v
}

// GetDecimals returns the Decimals field value
func (o *LiquidityBatchResponseTokensInInnerTokenInInfo) GetDecimals() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Decimals
}

// GetDecimalsOk returns a tuple with the Decimals field value
// and a boolean to check if the value has been set.
func (o *LiquidityBatchResponseTokensInInnerTokenInInfo) GetDecimalsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decimals, true
}

// SetDecimals sets field value
func (o *LiquidityBatchResponseTokensInInnerTokenInInfo) SetDecimals(v int64) {
	o.Decimals = v
}

func (o LiquidityBatchResponseTokensInInnerTokenInInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LiquidityBatchResponseTokensInInnerTokenInInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["symbol"] = o.Symbol
	toSerialize["name"] = o.Name
	toSerialize["decimals"] = o.Decimals

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LiquidityBatchResponseTokensInInnerTokenInInfo) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varLiquidityBatchResponseTokensInInnerTokenInInfo := _LiquidityBatchResponseTokensInInnerTokenInInfo{}

	err = json.Unmarshal(data, &varLiquidityBatchResponseTokensInInnerTokenInInfo)

	if err != nil {
		return err
	}

	*o = LiquidityBatchResponseTokensInInnerTokenInInfo(varLiquidityBatchResponseTokensInInnerTokenInInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address")
		delete(additionalProperties, "symbol")
		delete(additionalProperties, "name")
		delete(additionalProperties, "decimals")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLiquidityBatchResponseTokensInInnerTokenInInfo struct {
	value *LiquidityBatchResponseTokensInInnerTokenInInfo
	isSet bool
}

func (v NullableLiquidityBatchResponseTokensInInnerTokenInInfo) Get() *LiquidityBatchResponseTokensInInnerTokenInInfo {
	return v.value
}

func (v *NullableLiquidityBatchResponseTokensInInnerTokenInInfo) Set(val *LiquidityBatchResponseTokensInInnerTokenInInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableLiquidityBatchResponseTokensInInnerTokenInInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableLiquidityBatchResponseTokensInInnerTokenInInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiquidityBatchResponseTokensInInnerTokenInInfo(val *LiquidityBatchResponseTokensInInnerTokenInInfo) *NullableLiquidityBatchResponseTokensInInnerTokenInInfo {
	return &NullableLiquidityBatchResponseTokensInInnerTokenInInfo{value: val, isSet: true}
}

func (v NullableLiquidityBatchResponseTokensInInnerTokenInInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLiquidityBatchResponseTokensInInnerTokenInInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
