/*
Symbiotic RFQ Backend API

Public RFQ backend API for approval checks, quote creation, order submission, and order polling.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackend

import (
	"bytes"
	"encoding/json"
)

// checks if the LocalFaucetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocalFaucetResponse{}

// LocalFaucetResponse struct for LocalFaucetResponse
type LocalFaucetResponse struct {
	RequestId string                           `json:"requestId"`
	Assets    []LocalFaucetResponseAssetsInner `json:"assets"`
}

type _LocalFaucetResponse LocalFaucetResponse

// NewLocalFaucetResponse instantiates a new LocalFaucetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocalFaucetResponse(requestId string, assets []LocalFaucetResponseAssetsInner) *LocalFaucetResponse {
	this := LocalFaucetResponse{}
	this.RequestId = requestId
	this.Assets = assets
	return &this
}

// NewLocalFaucetResponseWithDefaults instantiates a new LocalFaucetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocalFaucetResponseWithDefaults() *LocalFaucetResponse {
	this := LocalFaucetResponse{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *LocalFaucetResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *LocalFaucetResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *LocalFaucetResponse) SetRequestId(v string) {
	o.RequestId = v
}

// GetAssets returns the Assets field value
func (o *LocalFaucetResponse) GetAssets() []LocalFaucetResponseAssetsInner {
	if o == nil {
		var ret []LocalFaucetResponseAssetsInner
		return ret
	}

	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value
// and a boolean to check if the value has been set.
func (o *LocalFaucetResponse) GetAssetsOk() ([]LocalFaucetResponseAssetsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Assets, true
}

// SetAssets sets field value
func (o *LocalFaucetResponse) SetAssets(v []LocalFaucetResponseAssetsInner) {
	o.Assets = v
}

func (o LocalFaucetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocalFaucetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	toSerialize["assets"] = o.Assets
	return toSerialize, nil
}

func (o *LocalFaucetResponse) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varLocalFaucetResponse := _LocalFaucetResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// Unknown fields tolerated (hack/openapi-relax-client.py): upstream may add
	// fields at any time without breaking us.
	err = decoder.Decode(&varLocalFaucetResponse)

	if err != nil {
		return err
	}

	*o = LocalFaucetResponse(varLocalFaucetResponse)

	return err
}

type NullableLocalFaucetResponse struct {
	value *LocalFaucetResponse
	isSet bool
}

func (v NullableLocalFaucetResponse) Get() *LocalFaucetResponse {
	return v.value
}

func (v *NullableLocalFaucetResponse) Set(val *LocalFaucetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLocalFaucetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLocalFaucetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocalFaucetResponse(val *LocalFaucetResponse) *NullableLocalFaucetResponse {
	return &NullableLocalFaucetResponse{value: val, isSet: true}
}

func (v NullableLocalFaucetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocalFaucetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
