/*
Symbiotic RFQ Backend API

Public RFQ backend API for approval checks, quote creation, order submission, and order polling.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackend

import (
	"bytes"
	"encoding/json"
)

// checks if the PublicQuoteResponseQuotesInnerSignatureData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicQuoteResponseQuotesInnerSignatureData{}

// PublicQuoteResponseQuotesInnerSignatureData struct for PublicQuoteResponseQuotesInnerSignatureData
type PublicQuoteResponseQuotesInnerSignatureData struct {
	Domain      map[string]*interface{}        `json:"domain"`
	Types       map[string][]map[string]string `json:"types"`
	PrimaryType string                         `json:"primaryType"`
	Value       map[string]*interface{}        `json:"value"`
}

type _PublicQuoteResponseQuotesInnerSignatureData PublicQuoteResponseQuotesInnerSignatureData

// NewPublicQuoteResponseQuotesInnerSignatureData instantiates a new PublicQuoteResponseQuotesInnerSignatureData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicQuoteResponseQuotesInnerSignatureData(domain map[string]*interface{}, types map[string][]map[string]string, primaryType string, value map[string]*interface{}) *PublicQuoteResponseQuotesInnerSignatureData {
	this := PublicQuoteResponseQuotesInnerSignatureData{}
	this.Domain = domain
	this.Types = types
	this.PrimaryType = primaryType
	this.Value = value
	return &this
}

// NewPublicQuoteResponseQuotesInnerSignatureDataWithDefaults instantiates a new PublicQuoteResponseQuotesInnerSignatureData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicQuoteResponseQuotesInnerSignatureDataWithDefaults() *PublicQuoteResponseQuotesInnerSignatureData {
	this := PublicQuoteResponseQuotesInnerSignatureData{}
	return &this
}

// GetDomain returns the Domain field value
func (o *PublicQuoteResponseQuotesInnerSignatureData) GetDomain() map[string]*interface{} {
	if o == nil {
		var ret map[string]*interface{}
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponseQuotesInnerSignatureData) GetDomainOk() (map[string]*interface{}, bool) {
	if o == nil {
		return map[string]*interface{}{}, false
	}
	return o.Domain, true
}

// SetDomain sets field value
func (o *PublicQuoteResponseQuotesInnerSignatureData) SetDomain(v map[string]*interface{}) {
	o.Domain = v
}

// GetTypes returns the Types field value
func (o *PublicQuoteResponseQuotesInnerSignatureData) GetTypes() map[string][]map[string]string {
	if o == nil {
		var ret map[string][]map[string]string
		return ret
	}

	return o.Types
}

// GetTypesOk returns a tuple with the Types field value
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponseQuotesInnerSignatureData) GetTypesOk() (map[string][]map[string]string, bool) {
	if o == nil {
		return map[string][]map[string]string{}, false
	}
	return o.Types, true
}

// SetTypes sets field value
func (o *PublicQuoteResponseQuotesInnerSignatureData) SetTypes(v map[string][]map[string]string) {
	o.Types = v
}

// GetPrimaryType returns the PrimaryType field value
func (o *PublicQuoteResponseQuotesInnerSignatureData) GetPrimaryType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrimaryType
}

// GetPrimaryTypeOk returns a tuple with the PrimaryType field value
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponseQuotesInnerSignatureData) GetPrimaryTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrimaryType, true
}

// SetPrimaryType sets field value
func (o *PublicQuoteResponseQuotesInnerSignatureData) SetPrimaryType(v string) {
	o.PrimaryType = v
}

// GetValue returns the Value field value
func (o *PublicQuoteResponseQuotesInnerSignatureData) GetValue() map[string]*interface{} {
	if o == nil {
		var ret map[string]*interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponseQuotesInnerSignatureData) GetValueOk() (map[string]*interface{}, bool) {
	if o == nil {
		return map[string]*interface{}{}, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *PublicQuoteResponseQuotesInnerSignatureData) SetValue(v map[string]*interface{}) {
	o.Value = v
}

func (o PublicQuoteResponseQuotesInnerSignatureData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicQuoteResponseQuotesInnerSignatureData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain"] = o.Domain
	toSerialize["types"] = o.Types
	toSerialize["primaryType"] = o.PrimaryType
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *PublicQuoteResponseQuotesInnerSignatureData) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varPublicQuoteResponseQuotesInnerSignatureData := _PublicQuoteResponseQuotesInnerSignatureData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// Unknown fields tolerated (hack/openapi-relax-client.py): upstream may add
	// fields at any time without breaking us.
	err = decoder.Decode(&varPublicQuoteResponseQuotesInnerSignatureData)

	if err != nil {
		return err
	}

	*o = PublicQuoteResponseQuotesInnerSignatureData(varPublicQuoteResponseQuotesInnerSignatureData)

	return err
}

type NullablePublicQuoteResponseQuotesInnerSignatureData struct {
	value *PublicQuoteResponseQuotesInnerSignatureData
	isSet bool
}

func (v NullablePublicQuoteResponseQuotesInnerSignatureData) Get() *PublicQuoteResponseQuotesInnerSignatureData {
	return v.value
}

func (v *NullablePublicQuoteResponseQuotesInnerSignatureData) Set(val *PublicQuoteResponseQuotesInnerSignatureData) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicQuoteResponseQuotesInnerSignatureData) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicQuoteResponseQuotesInnerSignatureData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicQuoteResponseQuotesInnerSignatureData(val *PublicQuoteResponseQuotesInnerSignatureData) *NullablePublicQuoteResponseQuotesInnerSignatureData {
	return &NullablePublicQuoteResponseQuotesInnerSignatureData{value: val, isSet: true}
}

func (v NullablePublicQuoteResponseQuotesInnerSignatureData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicQuoteResponseQuotesInnerSignatureData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
