/*
Symbiotic RFQ Backend API

Public RFQ backend API for approval checks, quote creation, order submission, and order polling.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackend

import (
	"encoding/json"
)

// checks if the CreateOrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrderRequest{}

// CreateOrderRequest struct for CreateOrderRequest
type CreateOrderRequest struct {
	Quote                CreateOrderRequestQuote `json:"quote"`
	Signature            string                  `json:"signature" validate:"regexp=^0x[a-fA-F0-9]+$"`
	AdditionalProperties map[string]interface{}
}

type _CreateOrderRequest CreateOrderRequest

// NewCreateOrderRequest instantiates a new CreateOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderRequest(quote CreateOrderRequestQuote, signature string) *CreateOrderRequest {
	this := CreateOrderRequest{}
	this.Quote = quote
	this.Signature = signature
	return &this
}

// NewCreateOrderRequestWithDefaults instantiates a new CreateOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderRequestWithDefaults() *CreateOrderRequest {
	this := CreateOrderRequest{}
	return &this
}

// GetQuote returns the Quote field value
func (o *CreateOrderRequest) GetQuote() CreateOrderRequestQuote {
	if o == nil {
		var ret CreateOrderRequestQuote
		return ret
	}

	return o.Quote
}

// GetQuoteOk returns a tuple with the Quote field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequest) GetQuoteOk() (*CreateOrderRequestQuote, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quote, true
}

// SetQuote sets field value
func (o *CreateOrderRequest) SetQuote(v CreateOrderRequestQuote) {
	o.Quote = v
}

// GetSignature returns the Signature field value
func (o *CreateOrderRequest) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequest) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *CreateOrderRequest) SetSignature(v string) {
	o.Signature = v
}

func (o CreateOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["quote"] = o.Quote
	toSerialize["signature"] = o.Signature

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateOrderRequest) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varCreateOrderRequest := _CreateOrderRequest{}

	err = json.Unmarshal(data, &varCreateOrderRequest)

	if err != nil {
		return err
	}

	*o = CreateOrderRequest(varCreateOrderRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "quote")
		delete(additionalProperties, "signature")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateOrderRequest struct {
	value *CreateOrderRequest
	isSet bool
}

func (v NullableCreateOrderRequest) Get() *CreateOrderRequest {
	return v.value
}

func (v *NullableCreateOrderRequest) Set(val *CreateOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderRequest(val *CreateOrderRequest) *NullableCreateOrderRequest {
	return &NullableCreateOrderRequest{value: val, isSet: true}
}

func (v NullableCreateOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
