/*
Symbiotic RFQ Backend API

Public RFQ backend API for approval checks, quote creation, order submission, and order polling.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackend

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LocalFundRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocalFundRequest{}

// LocalFundRequest struct for LocalFundRequest
type LocalFundRequest struct {
	WalletAddress string `json:"walletAddress" validate:"regexp=^0x[a-fA-F0-9]{40}$"`
}

type _LocalFundRequest LocalFundRequest

// NewLocalFundRequest instantiates a new LocalFundRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocalFundRequest(walletAddress string) *LocalFundRequest {
	this := LocalFundRequest{}
	this.WalletAddress = walletAddress
	return &this
}

// NewLocalFundRequestWithDefaults instantiates a new LocalFundRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocalFundRequestWithDefaults() *LocalFundRequest {
	this := LocalFundRequest{}
	return &this
}

// GetWalletAddress returns the WalletAddress field value
func (o *LocalFundRequest) GetWalletAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletAddress
}

// GetWalletAddressOk returns a tuple with the WalletAddress field value
// and a boolean to check if the value has been set.
func (o *LocalFundRequest) GetWalletAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletAddress, true
}

// SetWalletAddress sets field value
func (o *LocalFundRequest) SetWalletAddress(v string) {
	o.WalletAddress = v
}

func (o LocalFundRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocalFundRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["walletAddress"] = o.WalletAddress
	return toSerialize, nil
}

func (o *LocalFundRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"walletAddress",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLocalFundRequest := _LocalFundRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLocalFundRequest)

	if err != nil {
		return err
	}

	*o = LocalFundRequest(varLocalFundRequest)

	return err
}

type NullableLocalFundRequest struct {
	value *LocalFundRequest
	isSet bool
}

func (v NullableLocalFundRequest) Get() *LocalFundRequest {
	return v.value
}

func (v *NullableLocalFundRequest) Set(val *LocalFundRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLocalFundRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLocalFundRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocalFundRequest(val *LocalFundRequest) *NullableLocalFundRequest {
	return &NullableLocalFundRequest{value: val, isSet: true}
}

func (v NullableLocalFundRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocalFundRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
