/*
Symbiotic RFQ Backend API

Public RFQ backend API for approval checks, quote creation, order submission, and order polling.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackend

import (
	"bytes"
	"encoding/json"
)

// checks if the PublicQuoteResponseQuoteOrderInfoOutputsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicQuoteResponseQuoteOrderInfoOutputsInner{}

// PublicQuoteResponseQuoteOrderInfoOutputsInner struct for PublicQuoteResponseQuoteOrderInfoOutputsInner
type PublicQuoteResponseQuoteOrderInfoOutputsInner struct {
	Token      string `json:"token" validate:"regexp=^0x[a-fA-F0-9]{40}$"`
	Recipient  string `json:"recipient" validate:"regexp=^0x[a-fA-F0-9]{40}$"`
	Amount     string `json:"amount" validate:"regexp=^\\\\d+$"`
	PortionBps *int32 `json:"portionBps,omitempty"`
}

type _PublicQuoteResponseQuoteOrderInfoOutputsInner PublicQuoteResponseQuoteOrderInfoOutputsInner

// NewPublicQuoteResponseQuoteOrderInfoOutputsInner instantiates a new PublicQuoteResponseQuoteOrderInfoOutputsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicQuoteResponseQuoteOrderInfoOutputsInner(token string, recipient string, amount string) *PublicQuoteResponseQuoteOrderInfoOutputsInner {
	this := PublicQuoteResponseQuoteOrderInfoOutputsInner{}
	this.Token = token
	this.Recipient = recipient
	this.Amount = amount
	return &this
}

// NewPublicQuoteResponseQuoteOrderInfoOutputsInnerWithDefaults instantiates a new PublicQuoteResponseQuoteOrderInfoOutputsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicQuoteResponseQuoteOrderInfoOutputsInnerWithDefaults() *PublicQuoteResponseQuoteOrderInfoOutputsInner {
	this := PublicQuoteResponseQuoteOrderInfoOutputsInner{}
	return &this
}

// GetToken returns the Token field value
func (o *PublicQuoteResponseQuoteOrderInfoOutputsInner) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponseQuoteOrderInfoOutputsInner) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *PublicQuoteResponseQuoteOrderInfoOutputsInner) SetToken(v string) {
	o.Token = v
}

// GetRecipient returns the Recipient field value
func (o *PublicQuoteResponseQuoteOrderInfoOutputsInner) GetRecipient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponseQuoteOrderInfoOutputsInner) GetRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recipient, true
}

// SetRecipient sets field value
func (o *PublicQuoteResponseQuoteOrderInfoOutputsInner) SetRecipient(v string) {
	o.Recipient = v
}

// GetAmount returns the Amount field value
func (o *PublicQuoteResponseQuoteOrderInfoOutputsInner) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponseQuoteOrderInfoOutputsInner) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *PublicQuoteResponseQuoteOrderInfoOutputsInner) SetAmount(v string) {
	o.Amount = v
}

// GetPortionBps returns the PortionBps field value if set, zero value otherwise.
func (o *PublicQuoteResponseQuoteOrderInfoOutputsInner) GetPortionBps() int32 {
	if o == nil || IsNil(o.PortionBps) {
		var ret int32
		return ret
	}
	return *o.PortionBps
}

// GetPortionBpsOk returns a tuple with the PortionBps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponseQuoteOrderInfoOutputsInner) GetPortionBpsOk() (*int32, bool) {
	if o == nil || IsNil(o.PortionBps) {
		return nil, false
	}
	return o.PortionBps, true
}

// HasPortionBps returns a boolean if a field has been set.
func (o *PublicQuoteResponseQuoteOrderInfoOutputsInner) HasPortionBps() bool {
	if o != nil && !IsNil(o.PortionBps) {
		return true
	}

	return false
}

// SetPortionBps gets a reference to the given int32 and assigns it to the PortionBps field.
func (o *PublicQuoteResponseQuoteOrderInfoOutputsInner) SetPortionBps(v int32) {
	o.PortionBps = &v
}

func (o PublicQuoteResponseQuoteOrderInfoOutputsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicQuoteResponseQuoteOrderInfoOutputsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	toSerialize["recipient"] = o.Recipient
	toSerialize["amount"] = o.Amount
	if !IsNil(o.PortionBps) {
		toSerialize["portionBps"] = o.PortionBps
	}
	return toSerialize, nil
}

func (o *PublicQuoteResponseQuoteOrderInfoOutputsInner) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varPublicQuoteResponseQuoteOrderInfoOutputsInner := _PublicQuoteResponseQuoteOrderInfoOutputsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// Unknown fields tolerated (hack/openapi-relax-client.py): upstream may add
	// fields at any time without breaking us.
	err = decoder.Decode(&varPublicQuoteResponseQuoteOrderInfoOutputsInner)

	if err != nil {
		return err
	}

	*o = PublicQuoteResponseQuoteOrderInfoOutputsInner(varPublicQuoteResponseQuoteOrderInfoOutputsInner)

	return err
}

type NullablePublicQuoteResponseQuoteOrderInfoOutputsInner struct {
	value *PublicQuoteResponseQuoteOrderInfoOutputsInner
	isSet bool
}

func (v NullablePublicQuoteResponseQuoteOrderInfoOutputsInner) Get() *PublicQuoteResponseQuoteOrderInfoOutputsInner {
	return v.value
}

func (v *NullablePublicQuoteResponseQuoteOrderInfoOutputsInner) Set(val *PublicQuoteResponseQuoteOrderInfoOutputsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicQuoteResponseQuoteOrderInfoOutputsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicQuoteResponseQuoteOrderInfoOutputsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicQuoteResponseQuoteOrderInfoOutputsInner(val *PublicQuoteResponseQuoteOrderInfoOutputsInner) *NullablePublicQuoteResponseQuoteOrderInfoOutputsInner {
	return &NullablePublicQuoteResponseQuoteOrderInfoOutputsInner{value: val, isSet: true}
}

func (v NullablePublicQuoteResponseQuoteOrderInfoOutputsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicQuoteResponseQuoteOrderInfoOutputsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
