/*
Symbiotic RFQ Backend API

Public RFQ backend API for approval checks, quote creation, order submission, and order polling.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackend

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the QuoteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteRequest{}

// QuoteRequest struct for QuoteRequest
type QuoteRequest struct {
	TokenInChainId    int32                      `json:"tokenInChainId"`
	TokenOutChainId   int32                      `json:"tokenOutChainId"`
	TokenIn           string                     `json:"tokenIn" validate:"regexp=^0x[a-fA-F0-9]{40}$"`
	TokenOut          string                     `json:"tokenOut" validate:"regexp=^0x[a-fA-F0-9]{40}$"`
	Type              string                     `json:"type"`
	Amount            string                     `json:"amount" validate:"regexp=^\\\\d+$"`
	Swapper           string                     `json:"swapper" validate:"regexp=^0x[a-fA-F0-9]{40}$"`
	SlippageTolerance float32                    `json:"slippageTolerance"`
	RoutingPreference *string                    `json:"routingPreference,omitempty"`
	PermitAmount      *string                    `json:"permitAmount,omitempty"`
	SolverIds         []string                   `json:"solverIds,omitempty"`
	Outputs           []QuoteRequestOutputsInner `json:"outputs"`
}

type _QuoteRequest QuoteRequest

// NewQuoteRequest instantiates a new QuoteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteRequest(tokenInChainId int32, tokenOutChainId int32, tokenIn string, tokenOut string, type_ string, amount string, swapper string, slippageTolerance float32, outputs []QuoteRequestOutputsInner) *QuoteRequest {
	this := QuoteRequest{}
	this.TokenInChainId = tokenInChainId
	this.TokenOutChainId = tokenOutChainId
	this.TokenIn = tokenIn
	this.TokenOut = tokenOut
	this.Type = type_
	this.Amount = amount
	this.Swapper = swapper
	this.SlippageTolerance = slippageTolerance
	var routingPreference string = "BEST_PRICE"
	this.RoutingPreference = &routingPreference
	this.Outputs = outputs
	return &this
}

// NewQuoteRequestWithDefaults instantiates a new QuoteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteRequestWithDefaults() *QuoteRequest {
	this := QuoteRequest{}
	var routingPreference string = "BEST_PRICE"
	this.RoutingPreference = &routingPreference
	return &this
}

// GetTokenInChainId returns the TokenInChainId field value
func (o *QuoteRequest) GetTokenInChainId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TokenInChainId
}

// GetTokenInChainIdOk returns a tuple with the TokenInChainId field value
// and a boolean to check if the value has been set.
func (o *QuoteRequest) GetTokenInChainIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenInChainId, true
}

// SetTokenInChainId sets field value
func (o *QuoteRequest) SetTokenInChainId(v int32) {
	o.TokenInChainId = v
}

// GetTokenOutChainId returns the TokenOutChainId field value
func (o *QuoteRequest) GetTokenOutChainId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TokenOutChainId
}

// GetTokenOutChainIdOk returns a tuple with the TokenOutChainId field value
// and a boolean to check if the value has been set.
func (o *QuoteRequest) GetTokenOutChainIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenOutChainId, true
}

// SetTokenOutChainId sets field value
func (o *QuoteRequest) SetTokenOutChainId(v int32) {
	o.TokenOutChainId = v
}

// GetTokenIn returns the TokenIn field value
func (o *QuoteRequest) GetTokenIn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenIn
}

// GetTokenInOk returns a tuple with the TokenIn field value
// and a boolean to check if the value has been set.
func (o *QuoteRequest) GetTokenInOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenIn, true
}

// SetTokenIn sets field value
func (o *QuoteRequest) SetTokenIn(v string) {
	o.TokenIn = v
}

// GetTokenOut returns the TokenOut field value
func (o *QuoteRequest) GetTokenOut() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenOut
}

// GetTokenOutOk returns a tuple with the TokenOut field value
// and a boolean to check if the value has been set.
func (o *QuoteRequest) GetTokenOutOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenOut, true
}

// SetTokenOut sets field value
func (o *QuoteRequest) SetTokenOut(v string) {
	o.TokenOut = v
}

// GetType returns the Type field value
func (o *QuoteRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *QuoteRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *QuoteRequest) SetType(v string) {
	o.Type = v
}

// GetAmount returns the Amount field value
func (o *QuoteRequest) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *QuoteRequest) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *QuoteRequest) SetAmount(v string) {
	o.Amount = v
}

// GetSwapper returns the Swapper field value
func (o *QuoteRequest) GetSwapper() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Swapper
}

// GetSwapperOk returns a tuple with the Swapper field value
// and a boolean to check if the value has been set.
func (o *QuoteRequest) GetSwapperOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Swapper, true
}

// SetSwapper sets field value
func (o *QuoteRequest) SetSwapper(v string) {
	o.Swapper = v
}

// GetSlippageTolerance returns the SlippageTolerance field value
func (o *QuoteRequest) GetSlippageTolerance() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SlippageTolerance
}

// GetSlippageToleranceOk returns a tuple with the SlippageTolerance field value
// and a boolean to check if the value has been set.
func (o *QuoteRequest) GetSlippageToleranceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SlippageTolerance, true
}

// SetSlippageTolerance sets field value
func (o *QuoteRequest) SetSlippageTolerance(v float32) {
	o.SlippageTolerance = v
}

// GetRoutingPreference returns the RoutingPreference field value if set, zero value otherwise.
func (o *QuoteRequest) GetRoutingPreference() string {
	if o == nil || IsNil(o.RoutingPreference) {
		var ret string
		return ret
	}
	return *o.RoutingPreference
}

// GetRoutingPreferenceOk returns a tuple with the RoutingPreference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteRequest) GetRoutingPreferenceOk() (*string, bool) {
	if o == nil || IsNil(o.RoutingPreference) {
		return nil, false
	}
	return o.RoutingPreference, true
}

// HasRoutingPreference returns a boolean if a field has been set.
func (o *QuoteRequest) HasRoutingPreference() bool {
	if o != nil && !IsNil(o.RoutingPreference) {
		return true
	}

	return false
}

// SetRoutingPreference gets a reference to the given string and assigns it to the RoutingPreference field.
func (o *QuoteRequest) SetRoutingPreference(v string) {
	o.RoutingPreference = &v
}

// GetPermitAmount returns the PermitAmount field value if set, zero value otherwise.
func (o *QuoteRequest) GetPermitAmount() string {
	if o == nil || IsNil(o.PermitAmount) {
		var ret string
		return ret
	}
	return *o.PermitAmount
}

// GetPermitAmountOk returns a tuple with the PermitAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteRequest) GetPermitAmountOk() (*string, bool) {
	if o == nil || IsNil(o.PermitAmount) {
		return nil, false
	}
	return o.PermitAmount, true
}

// HasPermitAmount returns a boolean if a field has been set.
func (o *QuoteRequest) HasPermitAmount() bool {
	if o != nil && !IsNil(o.PermitAmount) {
		return true
	}

	return false
}

// SetPermitAmount gets a reference to the given string and assigns it to the PermitAmount field.
func (o *QuoteRequest) SetPermitAmount(v string) {
	o.PermitAmount = &v
}

// GetSolverIds returns the SolverIds field value if set, zero value otherwise.
func (o *QuoteRequest) GetSolverIds() []string {
	if o == nil || IsNil(o.SolverIds) {
		var ret []string
		return ret
	}
	return o.SolverIds
}

// GetSolverIdsOk returns a tuple with the SolverIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteRequest) GetSolverIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SolverIds) {
		return nil, false
	}
	return o.SolverIds, true
}

// HasSolverIds returns a boolean if a field has been set.
func (o *QuoteRequest) HasSolverIds() bool {
	if o != nil && !IsNil(o.SolverIds) {
		return true
	}

	return false
}

// SetSolverIds gets a reference to the given []string and assigns it to the SolverIds field.
func (o *QuoteRequest) SetSolverIds(v []string) {
	o.SolverIds = v
}

// GetOutputs returns the Outputs field value
func (o *QuoteRequest) GetOutputs() []QuoteRequestOutputsInner {
	if o == nil {
		var ret []QuoteRequestOutputsInner
		return ret
	}

	return o.Outputs
}

// GetOutputsOk returns a tuple with the Outputs field value
// and a boolean to check if the value has been set.
func (o *QuoteRequest) GetOutputsOk() ([]QuoteRequestOutputsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Outputs, true
}

// SetOutputs sets field value
func (o *QuoteRequest) SetOutputs(v []QuoteRequestOutputsInner) {
	o.Outputs = v
}

func (o QuoteRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tokenInChainId"] = o.TokenInChainId
	toSerialize["tokenOutChainId"] = o.TokenOutChainId
	toSerialize["tokenIn"] = o.TokenIn
	toSerialize["tokenOut"] = o.TokenOut
	toSerialize["type"] = o.Type
	toSerialize["amount"] = o.Amount
	toSerialize["swapper"] = o.Swapper
	toSerialize["slippageTolerance"] = o.SlippageTolerance
	if !IsNil(o.RoutingPreference) {
		toSerialize["routingPreference"] = o.RoutingPreference
	}
	if !IsNil(o.PermitAmount) {
		toSerialize["permitAmount"] = o.PermitAmount
	}
	if !IsNil(o.SolverIds) {
		toSerialize["solverIds"] = o.SolverIds
	}
	toSerialize["outputs"] = o.Outputs
	return toSerialize, nil
}

func (o *QuoteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tokenInChainId",
		"tokenOutChainId",
		"tokenIn",
		"tokenOut",
		"type",
		"amount",
		"swapper",
		"slippageTolerance",
		"outputs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuoteRequest := _QuoteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuoteRequest)

	if err != nil {
		return err
	}

	*o = QuoteRequest(varQuoteRequest)

	return err
}

type NullableQuoteRequest struct {
	value *QuoteRequest
	isSet bool
}

func (v NullableQuoteRequest) Get() *QuoteRequest {
	return v.value
}

func (v *NullableQuoteRequest) Set(val *QuoteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteRequest(val *QuoteRequest) *NullableQuoteRequest {
	return &NullableQuoteRequest{value: val, isSet: true}
}

func (v NullableQuoteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
