/*
Symbiotic RFQ Backend API

Public RFQ backend API for approval checks, quote creation, order submission, and order polling.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackend

import (
	"bytes"
	"encoding/json"
)

// checks if the PublicQuoteResponseQuotesInnerQuote type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicQuoteResponseQuotesInnerQuote{}

// PublicQuoteResponseQuotesInnerQuote struct for PublicQuoteResponseQuotesInnerQuote
type PublicQuoteResponseQuotesInnerQuote struct {
	QuoteId           string                                          `json:"quoteId" validate:"regexp=^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"`
	AggregatedOutputs []CreateOrderRequestQuoteAggregatedOutputsInner `json:"aggregatedOutputs"`
	OrderInfo         PublicQuoteResponseQuotesInnerQuoteOrderInfo    `json:"orderInfo"`
}

type _PublicQuoteResponseQuotesInnerQuote PublicQuoteResponseQuotesInnerQuote

// NewPublicQuoteResponseQuotesInnerQuote instantiates a new PublicQuoteResponseQuotesInnerQuote object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicQuoteResponseQuotesInnerQuote(quoteId string, aggregatedOutputs []CreateOrderRequestQuoteAggregatedOutputsInner, orderInfo PublicQuoteResponseQuotesInnerQuoteOrderInfo) *PublicQuoteResponseQuotesInnerQuote {
	this := PublicQuoteResponseQuotesInnerQuote{}
	this.QuoteId = quoteId
	this.AggregatedOutputs = aggregatedOutputs
	this.OrderInfo = orderInfo
	return &this
}

// NewPublicQuoteResponseQuotesInnerQuoteWithDefaults instantiates a new PublicQuoteResponseQuotesInnerQuote object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicQuoteResponseQuotesInnerQuoteWithDefaults() *PublicQuoteResponseQuotesInnerQuote {
	this := PublicQuoteResponseQuotesInnerQuote{}
	return &this
}

// GetQuoteId returns the QuoteId field value
func (o *PublicQuoteResponseQuotesInnerQuote) GetQuoteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuoteId
}

// GetQuoteIdOk returns a tuple with the QuoteId field value
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponseQuotesInnerQuote) GetQuoteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteId, true
}

// SetQuoteId sets field value
func (o *PublicQuoteResponseQuotesInnerQuote) SetQuoteId(v string) {
	o.QuoteId = v
}

// GetAggregatedOutputs returns the AggregatedOutputs field value
func (o *PublicQuoteResponseQuotesInnerQuote) GetAggregatedOutputs() []CreateOrderRequestQuoteAggregatedOutputsInner {
	if o == nil {
		var ret []CreateOrderRequestQuoteAggregatedOutputsInner
		return ret
	}

	return o.AggregatedOutputs
}

// GetAggregatedOutputsOk returns a tuple with the AggregatedOutputs field value
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponseQuotesInnerQuote) GetAggregatedOutputsOk() ([]CreateOrderRequestQuoteAggregatedOutputsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.AggregatedOutputs, true
}

// SetAggregatedOutputs sets field value
func (o *PublicQuoteResponseQuotesInnerQuote) SetAggregatedOutputs(v []CreateOrderRequestQuoteAggregatedOutputsInner) {
	o.AggregatedOutputs = v
}

// GetOrderInfo returns the OrderInfo field value
func (o *PublicQuoteResponseQuotesInnerQuote) GetOrderInfo() PublicQuoteResponseQuotesInnerQuoteOrderInfo {
	if o == nil {
		var ret PublicQuoteResponseQuotesInnerQuoteOrderInfo
		return ret
	}

	return o.OrderInfo
}

// GetOrderInfoOk returns a tuple with the OrderInfo field value
// and a boolean to check if the value has been set.
func (o *PublicQuoteResponseQuotesInnerQuote) GetOrderInfoOk() (*PublicQuoteResponseQuotesInnerQuoteOrderInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderInfo, true
}

// SetOrderInfo sets field value
func (o *PublicQuoteResponseQuotesInnerQuote) SetOrderInfo(v PublicQuoteResponseQuotesInnerQuoteOrderInfo) {
	o.OrderInfo = v
}

func (o PublicQuoteResponseQuotesInnerQuote) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicQuoteResponseQuotesInnerQuote) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["quoteId"] = o.QuoteId
	toSerialize["aggregatedOutputs"] = o.AggregatedOutputs
	toSerialize["orderInfo"] = o.OrderInfo
	return toSerialize, nil
}

func (o *PublicQuoteResponseQuotesInnerQuote) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varPublicQuoteResponseQuotesInnerQuote := _PublicQuoteResponseQuotesInnerQuote{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// Unknown fields tolerated (hack/openapi-relax-client.py): upstream may add
	// fields at any time without breaking us.
	err = decoder.Decode(&varPublicQuoteResponseQuotesInnerQuote)

	if err != nil {
		return err
	}

	*o = PublicQuoteResponseQuotesInnerQuote(varPublicQuoteResponseQuotesInnerQuote)

	return err
}

type NullablePublicQuoteResponseQuotesInnerQuote struct {
	value *PublicQuoteResponseQuotesInnerQuote
	isSet bool
}

func (v NullablePublicQuoteResponseQuotesInnerQuote) Get() *PublicQuoteResponseQuotesInnerQuote {
	return v.value
}

func (v *NullablePublicQuoteResponseQuotesInnerQuote) Set(val *PublicQuoteResponseQuotesInnerQuote) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicQuoteResponseQuotesInnerQuote) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicQuoteResponseQuotesInnerQuote) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicQuoteResponseQuotesInnerQuote(val *PublicQuoteResponseQuotesInnerQuote) *NullablePublicQuoteResponseQuotesInnerQuote {
	return &NullablePublicQuoteResponseQuotesInnerQuote{value: val, isSet: true}
}

func (v NullablePublicQuoteResponseQuotesInnerQuote) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicQuoteResponseQuotesInnerQuote) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
