/*
Symbiotic RFQ Backend API

Public RFQ backend API for approval checks, quote creation, order submission, and order polling.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackend

import (
	"encoding/json"
)

// checks if the LocalFaucetFundResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocalFaucetFundResponse{}

// LocalFaucetFundResponse struct for LocalFaucetFundResponse
type LocalFaucetFundResponse struct {
	RequestId            string                                     `json:"requestId"`
	WalletAddress        string                                     `json:"walletAddress" validate:"regexp=^0x[a-fA-F0-9]{40}$"`
	FundedAssets         []LocalFaucetFundResponseFundedAssetsInner `json:"fundedAssets"`
	AdditionalProperties map[string]interface{}
}

type _LocalFaucetFundResponse LocalFaucetFundResponse

// NewLocalFaucetFundResponse instantiates a new LocalFaucetFundResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocalFaucetFundResponse(requestId string, walletAddress string, fundedAssets []LocalFaucetFundResponseFundedAssetsInner) *LocalFaucetFundResponse {
	this := LocalFaucetFundResponse{}
	this.RequestId = requestId
	this.WalletAddress = walletAddress
	this.FundedAssets = fundedAssets
	return &this
}

// NewLocalFaucetFundResponseWithDefaults instantiates a new LocalFaucetFundResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocalFaucetFundResponseWithDefaults() *LocalFaucetFundResponse {
	this := LocalFaucetFundResponse{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *LocalFaucetFundResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *LocalFaucetFundResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *LocalFaucetFundResponse) SetRequestId(v string) {
	o.RequestId = v
}

// GetWalletAddress returns the WalletAddress field value
func (o *LocalFaucetFundResponse) GetWalletAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletAddress
}

// GetWalletAddressOk returns a tuple with the WalletAddress field value
// and a boolean to check if the value has been set.
func (o *LocalFaucetFundResponse) GetWalletAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletAddress, true
}

// SetWalletAddress sets field value
func (o *LocalFaucetFundResponse) SetWalletAddress(v string) {
	o.WalletAddress = v
}

// GetFundedAssets returns the FundedAssets field value
func (o *LocalFaucetFundResponse) GetFundedAssets() []LocalFaucetFundResponseFundedAssetsInner {
	if o == nil {
		var ret []LocalFaucetFundResponseFundedAssetsInner
		return ret
	}

	return o.FundedAssets
}

// GetFundedAssetsOk returns a tuple with the FundedAssets field value
// and a boolean to check if the value has been set.
func (o *LocalFaucetFundResponse) GetFundedAssetsOk() ([]LocalFaucetFundResponseFundedAssetsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.FundedAssets, true
}

// SetFundedAssets sets field value
func (o *LocalFaucetFundResponse) SetFundedAssets(v []LocalFaucetFundResponseFundedAssetsInner) {
	o.FundedAssets = v
}

func (o LocalFaucetFundResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocalFaucetFundResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	toSerialize["walletAddress"] = o.WalletAddress
	toSerialize["fundedAssets"] = o.FundedAssets

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LocalFaucetFundResponse) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varLocalFaucetFundResponse := _LocalFaucetFundResponse{}

	err = json.Unmarshal(data, &varLocalFaucetFundResponse)

	if err != nil {
		return err
	}

	*o = LocalFaucetFundResponse(varLocalFaucetFundResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requestId")
		delete(additionalProperties, "walletAddress")
		delete(additionalProperties, "fundedAssets")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLocalFaucetFundResponse struct {
	value *LocalFaucetFundResponse
	isSet bool
}

func (v NullableLocalFaucetFundResponse) Get() *LocalFaucetFundResponse {
	return v.value
}

func (v *NullableLocalFaucetFundResponse) Set(val *LocalFaucetFundResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLocalFaucetFundResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLocalFaucetFundResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocalFaucetFundResponse(val *LocalFaucetFundResponse) *NullableLocalFaucetFundResponse {
	return &NullableLocalFaucetFundResponse{value: val, isSet: true}
}

func (v NullableLocalFaucetFundResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocalFaucetFundResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
