/*
Symbiotic RFQ Backend API

Public RFQ backend API for approval checks, quote creation, order submission, and order polling.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackend

import (
	"encoding/json"
)

// checks if the LiquidityBatchResponseTokensInInnerSolversInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LiquidityBatchResponseTokensInInnerSolversInner{}

// LiquidityBatchResponseTokensInInnerSolversInner struct for LiquidityBatchResponseTokensInInnerSolversInner
type LiquidityBatchResponseTokensInInnerSolversInner struct {
	SolverId string `json:"solverId"`
	// Sum of adapters[].maxAssets that the quote builder makes available to this solver, in tokenOut base units.
	Liquidity            string `json:"liquidity" validate:"regexp=^\\d+$"`
	AdditionalProperties map[string]interface{}
}

type _LiquidityBatchResponseTokensInInnerSolversInner LiquidityBatchResponseTokensInInnerSolversInner

// NewLiquidityBatchResponseTokensInInnerSolversInner instantiates a new LiquidityBatchResponseTokensInInnerSolversInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLiquidityBatchResponseTokensInInnerSolversInner(solverId string, liquidity string) *LiquidityBatchResponseTokensInInnerSolversInner {
	this := LiquidityBatchResponseTokensInInnerSolversInner{}
	this.SolverId = solverId
	this.Liquidity = liquidity
	return &this
}

// NewLiquidityBatchResponseTokensInInnerSolversInnerWithDefaults instantiates a new LiquidityBatchResponseTokensInInnerSolversInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLiquidityBatchResponseTokensInInnerSolversInnerWithDefaults() *LiquidityBatchResponseTokensInInnerSolversInner {
	this := LiquidityBatchResponseTokensInInnerSolversInner{}
	return &this
}

// GetSolverId returns the SolverId field value
func (o *LiquidityBatchResponseTokensInInnerSolversInner) GetSolverId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SolverId
}

// GetSolverIdOk returns a tuple with the SolverId field value
// and a boolean to check if the value has been set.
func (o *LiquidityBatchResponseTokensInInnerSolversInner) GetSolverIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SolverId, true
}

// SetSolverId sets field value
func (o *LiquidityBatchResponseTokensInInnerSolversInner) SetSolverId(v string) {
	o.SolverId = v
}

// GetLiquidity returns the Liquidity field value
func (o *LiquidityBatchResponseTokensInInnerSolversInner) GetLiquidity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Liquidity
}

// GetLiquidityOk returns a tuple with the Liquidity field value
// and a boolean to check if the value has been set.
func (o *LiquidityBatchResponseTokensInInnerSolversInner) GetLiquidityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Liquidity, true
}

// SetLiquidity sets field value
func (o *LiquidityBatchResponseTokensInInnerSolversInner) SetLiquidity(v string) {
	o.Liquidity = v
}

func (o LiquidityBatchResponseTokensInInnerSolversInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LiquidityBatchResponseTokensInInnerSolversInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["solverId"] = o.SolverId
	toSerialize["liquidity"] = o.Liquidity

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LiquidityBatchResponseTokensInInnerSolversInner) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varLiquidityBatchResponseTokensInInnerSolversInner := _LiquidityBatchResponseTokensInInnerSolversInner{}

	err = json.Unmarshal(data, &varLiquidityBatchResponseTokensInInnerSolversInner)

	if err != nil {
		return err
	}

	*o = LiquidityBatchResponseTokensInInnerSolversInner(varLiquidityBatchResponseTokensInInnerSolversInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "solverId")
		delete(additionalProperties, "liquidity")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLiquidityBatchResponseTokensInInnerSolversInner struct {
	value *LiquidityBatchResponseTokensInInnerSolversInner
	isSet bool
}

func (v NullableLiquidityBatchResponseTokensInInnerSolversInner) Get() *LiquidityBatchResponseTokensInInnerSolversInner {
	return v.value
}

func (v *NullableLiquidityBatchResponseTokensInInnerSolversInner) Set(val *LiquidityBatchResponseTokensInInnerSolversInner) {
	v.value = val
	v.isSet = true
}

func (v NullableLiquidityBatchResponseTokensInInnerSolversInner) IsSet() bool {
	return v.isSet
}

func (v *NullableLiquidityBatchResponseTokensInInnerSolversInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiquidityBatchResponseTokensInInnerSolversInner(val *LiquidityBatchResponseTokensInInnerSolversInner) *NullableLiquidityBatchResponseTokensInInnerSolversInner {
	return &NullableLiquidityBatchResponseTokensInInnerSolversInner{value: val, isSet: true}
}

func (v NullableLiquidityBatchResponseTokensInInnerSolversInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLiquidityBatchResponseTokensInInnerSolversInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
