/*
Symbiotic RFQ Backend API

Public RFQ backend API for approval checks, quote creation, order submission, and order polling.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rfqbackend

import (
	"encoding/json"
)

// checks if the CreateOrderRequestQuoteOrderInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrderRequestQuoteOrderInfo{}

// CreateOrderRequestQuoteOrderInfo struct for CreateOrderRequestQuoteOrderInfo
type CreateOrderRequestQuoteOrderInfo struct {
	TokenIn  string                                         `json:"tokenIn" validate:"regexp=^0x[a-fA-F0-9]{40}$"`
	AmountIn string                                         `json:"amountIn" validate:"regexp=^\\d+$"`
	Outputs  []CreateOrderRequestQuoteOrderInfoOutputsInner `json:"outputs"`
	Deadline int32                                          `json:"deadline"`
	// Base-10 uint256 string from 0 through 115792089237316195423570985008687907853269984665640564039457584007913129639935; leading zeroes are accepted.
	Nonce                string `json:"nonce" validate:"regexp=^\\d+$"`
	AdditionalProperties map[string]interface{}
}

type _CreateOrderRequestQuoteOrderInfo CreateOrderRequestQuoteOrderInfo

// NewCreateOrderRequestQuoteOrderInfo instantiates a new CreateOrderRequestQuoteOrderInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrderRequestQuoteOrderInfo(tokenIn string, amountIn string, outputs []CreateOrderRequestQuoteOrderInfoOutputsInner, deadline int32, nonce string) *CreateOrderRequestQuoteOrderInfo {
	this := CreateOrderRequestQuoteOrderInfo{}
	this.TokenIn = tokenIn
	this.AmountIn = amountIn
	this.Outputs = outputs
	this.Deadline = deadline
	this.Nonce = nonce
	return &this
}

// NewCreateOrderRequestQuoteOrderInfoWithDefaults instantiates a new CreateOrderRequestQuoteOrderInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrderRequestQuoteOrderInfoWithDefaults() *CreateOrderRequestQuoteOrderInfo {
	this := CreateOrderRequestQuoteOrderInfo{}
	return &this
}

// GetTokenIn returns the TokenIn field value
func (o *CreateOrderRequestQuoteOrderInfo) GetTokenIn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenIn
}

// GetTokenInOk returns a tuple with the TokenIn field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestQuoteOrderInfo) GetTokenInOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenIn, true
}

// SetTokenIn sets field value
func (o *CreateOrderRequestQuoteOrderInfo) SetTokenIn(v string) {
	o.TokenIn = v
}

// GetAmountIn returns the AmountIn field value
func (o *CreateOrderRequestQuoteOrderInfo) GetAmountIn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmountIn
}

// GetAmountInOk returns a tuple with the AmountIn field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestQuoteOrderInfo) GetAmountInOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountIn, true
}

// SetAmountIn sets field value
func (o *CreateOrderRequestQuoteOrderInfo) SetAmountIn(v string) {
	o.AmountIn = v
}

// GetOutputs returns the Outputs field value
func (o *CreateOrderRequestQuoteOrderInfo) GetOutputs() []CreateOrderRequestQuoteOrderInfoOutputsInner {
	if o == nil {
		var ret []CreateOrderRequestQuoteOrderInfoOutputsInner
		return ret
	}

	return o.Outputs
}

// GetOutputsOk returns a tuple with the Outputs field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestQuoteOrderInfo) GetOutputsOk() ([]CreateOrderRequestQuoteOrderInfoOutputsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Outputs, true
}

// SetOutputs sets field value
func (o *CreateOrderRequestQuoteOrderInfo) SetOutputs(v []CreateOrderRequestQuoteOrderInfoOutputsInner) {
	o.Outputs = v
}

// GetDeadline returns the Deadline field value
func (o *CreateOrderRequestQuoteOrderInfo) GetDeadline() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Deadline
}

// GetDeadlineOk returns a tuple with the Deadline field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestQuoteOrderInfo) GetDeadlineOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deadline, true
}

// SetDeadline sets field value
func (o *CreateOrderRequestQuoteOrderInfo) SetDeadline(v int32) {
	o.Deadline = v
}

// GetNonce returns the Nonce field value
func (o *CreateOrderRequestQuoteOrderInfo) GetNonce() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Nonce
}

// GetNonceOk returns a tuple with the Nonce field value
// and a boolean to check if the value has been set.
func (o *CreateOrderRequestQuoteOrderInfo) GetNonceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nonce, true
}

// SetNonce sets field value
func (o *CreateOrderRequestQuoteOrderInfo) SetNonce(v string) {
	o.Nonce = v
}

func (o CreateOrderRequestQuoteOrderInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrderRequestQuoteOrderInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tokenIn"] = o.TokenIn
	toSerialize["amountIn"] = o.AmountIn
	toSerialize["outputs"] = o.Outputs
	toSerialize["deadline"] = o.Deadline
	toSerialize["nonce"] = o.Nonce

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateOrderRequestQuoteOrderInfo) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varCreateOrderRequestQuoteOrderInfo := _CreateOrderRequestQuoteOrderInfo{}

	err = json.Unmarshal(data, &varCreateOrderRequestQuoteOrderInfo)

	if err != nil {
		return err
	}

	*o = CreateOrderRequestQuoteOrderInfo(varCreateOrderRequestQuoteOrderInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tokenIn")
		delete(additionalProperties, "amountIn")
		delete(additionalProperties, "outputs")
		delete(additionalProperties, "deadline")
		delete(additionalProperties, "nonce")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateOrderRequestQuoteOrderInfo struct {
	value *CreateOrderRequestQuoteOrderInfo
	isSet bool
}

func (v NullableCreateOrderRequestQuoteOrderInfo) Get() *CreateOrderRequestQuoteOrderInfo {
	return v.value
}

func (v *NullableCreateOrderRequestQuoteOrderInfo) Set(val *CreateOrderRequestQuoteOrderInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrderRequestQuoteOrderInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrderRequestQuoteOrderInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrderRequestQuoteOrderInfo(val *CreateOrderRequestQuoteOrderInfo) *NullableCreateOrderRequestQuoteOrderInfo {
	return &NullableCreateOrderRequestQuoteOrderInfo{value: val, isSet: true}
}

func (v NullableCreateOrderRequestQuoteOrderInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrderRequestQuoteOrderInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
