/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.20
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
)

// checks if the GetSolverQuotesResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSolverQuotesResponseDto{}

// GetSolverQuotesResponseDto struct for GetSolverQuotesResponseDto
type GetSolverQuotesResponseDto struct {
	// Array of solver quotes
	Data []SolverQuoteDto `json:"data"`
	// Pagination metadata
	Meta                 PaginationMetaDto `json:"meta"`
	AdditionalProperties map[string]interface{}
}

type _GetSolverQuotesResponseDto GetSolverQuotesResponseDto

// NewGetSolverQuotesResponseDto instantiates a new GetSolverQuotesResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSolverQuotesResponseDto(data []SolverQuoteDto, meta PaginationMetaDto) *GetSolverQuotesResponseDto {
	this := GetSolverQuotesResponseDto{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewGetSolverQuotesResponseDtoWithDefaults instantiates a new GetSolverQuotesResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSolverQuotesResponseDtoWithDefaults() *GetSolverQuotesResponseDto {
	this := GetSolverQuotesResponseDto{}
	return &this
}

// GetData returns the Data field value
func (o *GetSolverQuotesResponseDto) GetData() []SolverQuoteDto {
	if o == nil {
		var ret []SolverQuoteDto
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetSolverQuotesResponseDto) GetDataOk() ([]SolverQuoteDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetSolverQuotesResponseDto) SetData(v []SolverQuoteDto) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *GetSolverQuotesResponseDto) GetMeta() PaginationMetaDto {
	if o == nil {
		var ret PaginationMetaDto
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetSolverQuotesResponseDto) GetMetaOk() (*PaginationMetaDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *GetSolverQuotesResponseDto) SetMeta(v PaginationMetaDto) {
	o.Meta = v
}

func (o GetSolverQuotesResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSolverQuotesResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["meta"] = o.Meta

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetSolverQuotesResponseDto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varGetSolverQuotesResponseDto := _GetSolverQuotesResponseDto{}

	err = json.Unmarshal(data, &varGetSolverQuotesResponseDto)

	if err != nil {
		return err
	}

	*o = GetSolverQuotesResponseDto(varGetSolverQuotesResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetSolverQuotesResponseDto struct {
	value *GetSolverQuotesResponseDto
	isSet bool
}

func (v NullableGetSolverQuotesResponseDto) Get() *GetSolverQuotesResponseDto {
	return v.value
}

func (v *NullableGetSolverQuotesResponseDto) Set(val *GetSolverQuotesResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSolverQuotesResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSolverQuotesResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSolverQuotesResponseDto(val *GetSolverQuotesResponseDto) *NullableGetSolverQuotesResponseDto {
	return &NullableGetSolverQuotesResponseDto{value: val, isSet: true}
}

func (v NullableGetSolverQuotesResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSolverQuotesResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
