/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the QuoteRequestDtoIntent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteRequestDtoIntent{}

// QuoteRequestDtoIntent Intent details for the quote request
type QuoteRequestDtoIntent struct {
	// Intent type (otherwise return quotes: [])
	IntentType string `json:"intentType"`
	// Available inputs for the quote. Order is significant if preference is input-priority. Constraint: Amount must be positive whole integer
	Inputs []QuoteRequestDtoIntentInputsInner `json:"inputs"`
	// Requested outputs for the quote. Constraint: Amount must be positive whole integer
	Outputs []QuoteRequestDtoIntentOutputsInner `json:"outputs"`
	// Swap type for the quote. exact-input: quotes are based on inputs[].amount and outputs[].amount is ignored. exact-output: quotes are based on outputs[].amount and inputs[].amount is ignored. If none available, return []
	SwapType *string `json:"swapType,omitempty"`
	// Minimum validity timestamp in unix timestamp (seconds). Only select solver quotes with longer TTL.
	MinValidUntil *float32 `json:"minValidUntil,omitempty"`
	// Quote preference (unsupported, ignored if provided)
	Preference       *string     `json:"preference,omitempty"`
	OriginSubmission interface{} `json:"originSubmission,omitempty"`
	// Failure handling policy for execution that the integrator supports (unsupported, ignored)
	FailureHandling []string `json:"failureHandling,omitempty"`
	// Whether the integrator supports partial fills. Partial fills are not supported - if true, return quotes: []
	PartialFill *bool                          `json:"partialFill,omitempty"`
	Metadata    *QuoteRequestDtoIntentMetadata `json:"metadata,omitempty"`
}

type _QuoteRequestDtoIntent QuoteRequestDtoIntent

// NewQuoteRequestDtoIntent instantiates a new QuoteRequestDtoIntent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteRequestDtoIntent(intentType string, inputs []QuoteRequestDtoIntentInputsInner, outputs []QuoteRequestDtoIntentOutputsInner) *QuoteRequestDtoIntent {
	this := QuoteRequestDtoIntent{}
	this.IntentType = intentType
	this.Inputs = inputs
	this.Outputs = outputs
	var swapType string = "exact-input"
	this.SwapType = &swapType
	return &this
}

// NewQuoteRequestDtoIntentWithDefaults instantiates a new QuoteRequestDtoIntent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteRequestDtoIntentWithDefaults() *QuoteRequestDtoIntent {
	this := QuoteRequestDtoIntent{}
	var swapType string = "exact-input"
	this.SwapType = &swapType
	return &this
}

// GetIntentType returns the IntentType field value
func (o *QuoteRequestDtoIntent) GetIntentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntentType
}

// GetIntentTypeOk returns a tuple with the IntentType field value
// and a boolean to check if the value has been set.
func (o *QuoteRequestDtoIntent) GetIntentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntentType, true
}

// SetIntentType sets field value
func (o *QuoteRequestDtoIntent) SetIntentType(v string) {
	o.IntentType = v
}

// GetInputs returns the Inputs field value
func (o *QuoteRequestDtoIntent) GetInputs() []QuoteRequestDtoIntentInputsInner {
	if o == nil {
		var ret []QuoteRequestDtoIntentInputsInner
		return ret
	}

	return o.Inputs
}

// GetInputsOk returns a tuple with the Inputs field value
// and a boolean to check if the value has been set.
func (o *QuoteRequestDtoIntent) GetInputsOk() ([]QuoteRequestDtoIntentInputsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Inputs, true
}

// SetInputs sets field value
func (o *QuoteRequestDtoIntent) SetInputs(v []QuoteRequestDtoIntentInputsInner) {
	o.Inputs = v
}

// GetOutputs returns the Outputs field value
func (o *QuoteRequestDtoIntent) GetOutputs() []QuoteRequestDtoIntentOutputsInner {
	if o == nil {
		var ret []QuoteRequestDtoIntentOutputsInner
		return ret
	}

	return o.Outputs
}

// GetOutputsOk returns a tuple with the Outputs field value
// and a boolean to check if the value has been set.
func (o *QuoteRequestDtoIntent) GetOutputsOk() ([]QuoteRequestDtoIntentOutputsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Outputs, true
}

// SetOutputs sets field value
func (o *QuoteRequestDtoIntent) SetOutputs(v []QuoteRequestDtoIntentOutputsInner) {
	o.Outputs = v
}

// GetSwapType returns the SwapType field value if set, zero value otherwise.
func (o *QuoteRequestDtoIntent) GetSwapType() string {
	if o == nil || IsNil(o.SwapType) {
		var ret string
		return ret
	}
	return *o.SwapType
}

// GetSwapTypeOk returns a tuple with the SwapType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteRequestDtoIntent) GetSwapTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SwapType) {
		return nil, false
	}
	return o.SwapType, true
}

// HasSwapType returns a boolean if a field has been set.
func (o *QuoteRequestDtoIntent) HasSwapType() bool {
	if o != nil && !IsNil(o.SwapType) {
		return true
	}

	return false
}

// SetSwapType gets a reference to the given string and assigns it to the SwapType field.
func (o *QuoteRequestDtoIntent) SetSwapType(v string) {
	o.SwapType = &v
}

// GetMinValidUntil returns the MinValidUntil field value if set, zero value otherwise.
func (o *QuoteRequestDtoIntent) GetMinValidUntil() float32 {
	if o == nil || IsNil(o.MinValidUntil) {
		var ret float32
		return ret
	}
	return *o.MinValidUntil
}

// GetMinValidUntilOk returns a tuple with the MinValidUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteRequestDtoIntent) GetMinValidUntilOk() (*float32, bool) {
	if o == nil || IsNil(o.MinValidUntil) {
		return nil, false
	}
	return o.MinValidUntil, true
}

// HasMinValidUntil returns a boolean if a field has been set.
func (o *QuoteRequestDtoIntent) HasMinValidUntil() bool {
	if o != nil && !IsNil(o.MinValidUntil) {
		return true
	}

	return false
}

// SetMinValidUntil gets a reference to the given float32 and assigns it to the MinValidUntil field.
func (o *QuoteRequestDtoIntent) SetMinValidUntil(v float32) {
	o.MinValidUntil = &v
}

// GetPreference returns the Preference field value if set, zero value otherwise.
func (o *QuoteRequestDtoIntent) GetPreference() string {
	if o == nil || IsNil(o.Preference) {
		var ret string
		return ret
	}
	return *o.Preference
}

// GetPreferenceOk returns a tuple with the Preference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteRequestDtoIntent) GetPreferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Preference) {
		return nil, false
	}
	return o.Preference, true
}

// HasPreference returns a boolean if a field has been set.
func (o *QuoteRequestDtoIntent) HasPreference() bool {
	if o != nil && !IsNil(o.Preference) {
		return true
	}

	return false
}

// SetPreference gets a reference to the given string and assigns it to the Preference field.
func (o *QuoteRequestDtoIntent) SetPreference(v string) {
	o.Preference = &v
}

// GetOriginSubmission returns the OriginSubmission field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *QuoteRequestDtoIntent) GetOriginSubmission() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.OriginSubmission
}

// GetOriginSubmissionOk returns a tuple with the OriginSubmission field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QuoteRequestDtoIntent) GetOriginSubmissionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.OriginSubmission) {
		return nil, false
	}
	return &o.OriginSubmission, true
}

// HasOriginSubmission returns a boolean if a field has been set.
func (o *QuoteRequestDtoIntent) HasOriginSubmission() bool {
	if o != nil && !IsNil(o.OriginSubmission) {
		return true
	}

	return false
}

// SetOriginSubmission gets a reference to the given interface{} and assigns it to the OriginSubmission field.
func (o *QuoteRequestDtoIntent) SetOriginSubmission(v interface{}) {
	o.OriginSubmission = v
}

// GetFailureHandling returns the FailureHandling field value if set, zero value otherwise.
func (o *QuoteRequestDtoIntent) GetFailureHandling() []string {
	if o == nil || IsNil(o.FailureHandling) {
		var ret []string
		return ret
	}
	return o.FailureHandling
}

// GetFailureHandlingOk returns a tuple with the FailureHandling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteRequestDtoIntent) GetFailureHandlingOk() ([]string, bool) {
	if o == nil || IsNil(o.FailureHandling) {
		return nil, false
	}
	return o.FailureHandling, true
}

// HasFailureHandling returns a boolean if a field has been set.
func (o *QuoteRequestDtoIntent) HasFailureHandling() bool {
	if o != nil && !IsNil(o.FailureHandling) {
		return true
	}

	return false
}

// SetFailureHandling gets a reference to the given []string and assigns it to the FailureHandling field.
func (o *QuoteRequestDtoIntent) SetFailureHandling(v []string) {
	o.FailureHandling = v
}

// GetPartialFill returns the PartialFill field value if set, zero value otherwise.
func (o *QuoteRequestDtoIntent) GetPartialFill() bool {
	if o == nil || IsNil(o.PartialFill) {
		var ret bool
		return ret
	}
	return *o.PartialFill
}

// GetPartialFillOk returns a tuple with the PartialFill field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteRequestDtoIntent) GetPartialFillOk() (*bool, bool) {
	if o == nil || IsNil(o.PartialFill) {
		return nil, false
	}
	return o.PartialFill, true
}

// HasPartialFill returns a boolean if a field has been set.
func (o *QuoteRequestDtoIntent) HasPartialFill() bool {
	if o != nil && !IsNil(o.PartialFill) {
		return true
	}

	return false
}

// SetPartialFill gets a reference to the given bool and assigns it to the PartialFill field.
func (o *QuoteRequestDtoIntent) SetPartialFill(v bool) {
	o.PartialFill = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *QuoteRequestDtoIntent) GetMetadata() QuoteRequestDtoIntentMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret QuoteRequestDtoIntentMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteRequestDtoIntent) GetMetadataOk() (*QuoteRequestDtoIntentMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *QuoteRequestDtoIntent) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given QuoteRequestDtoIntentMetadata and assigns it to the Metadata field.
func (o *QuoteRequestDtoIntent) SetMetadata(v QuoteRequestDtoIntentMetadata) {
	o.Metadata = &v
}

func (o QuoteRequestDtoIntent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteRequestDtoIntent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["intentType"] = o.IntentType
	toSerialize["inputs"] = o.Inputs
	toSerialize["outputs"] = o.Outputs
	if !IsNil(o.SwapType) {
		toSerialize["swapType"] = o.SwapType
	}
	if !IsNil(o.MinValidUntil) {
		toSerialize["minValidUntil"] = o.MinValidUntil
	}
	if !IsNil(o.Preference) {
		toSerialize["preference"] = o.Preference
	}
	if o.OriginSubmission != nil {
		toSerialize["originSubmission"] = o.OriginSubmission
	}
	if !IsNil(o.FailureHandling) {
		toSerialize["failureHandling"] = o.FailureHandling
	}
	if !IsNil(o.PartialFill) {
		toSerialize["partialFill"] = o.PartialFill
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *QuoteRequestDtoIntent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"intentType",
		"inputs",
		"outputs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuoteRequestDtoIntent := _QuoteRequestDtoIntent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuoteRequestDtoIntent)

	if err != nil {
		return err
	}

	*o = QuoteRequestDtoIntent(varQuoteRequestDtoIntent)

	return err
}

type NullableQuoteRequestDtoIntent struct {
	value *QuoteRequestDtoIntent
	isSet bool
}

func (v NullableQuoteRequestDtoIntent) Get() *QuoteRequestDtoIntent {
	return v.value
}

func (v *NullableQuoteRequestDtoIntent) Set(val *QuoteRequestDtoIntent) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteRequestDtoIntent) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteRequestDtoIntent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteRequestDtoIntent(val *QuoteRequestDtoIntent) *NullableQuoteRequestDtoIntent {
	return &NullableQuoteRequestDtoIntent{value: val, isSet: true}
}

func (v NullableQuoteRequestDtoIntent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteRequestDtoIntent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
