/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the QuoteRequestDtoIntentMetadataOracleInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteRequestDtoIntentMetadataOracleInner{}

// QuoteRequestDtoIntentMetadataOracleInner struct for QuoteRequestDtoIntentMetadataOracleInner
type QuoteRequestDtoIntentMetadataOracleInner struct {
	// CAIP-2 chain identifier, e.g. \"eip155:1\"
	Chain string `json:"chain"`
	// Native contract address for the chain
	Address string `json:"address"`
}

type _QuoteRequestDtoIntentMetadataOracleInner QuoteRequestDtoIntentMetadataOracleInner

// NewQuoteRequestDtoIntentMetadataOracleInner instantiates a new QuoteRequestDtoIntentMetadataOracleInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteRequestDtoIntentMetadataOracleInner(chain string, address string) *QuoteRequestDtoIntentMetadataOracleInner {
	this := QuoteRequestDtoIntentMetadataOracleInner{}
	this.Chain = chain
	this.Address = address
	return &this
}

// NewQuoteRequestDtoIntentMetadataOracleInnerWithDefaults instantiates a new QuoteRequestDtoIntentMetadataOracleInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteRequestDtoIntentMetadataOracleInnerWithDefaults() *QuoteRequestDtoIntentMetadataOracleInner {
	this := QuoteRequestDtoIntentMetadataOracleInner{}
	return &this
}

// GetChain returns the Chain field value
func (o *QuoteRequestDtoIntentMetadataOracleInner) GetChain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *QuoteRequestDtoIntentMetadataOracleInner) GetChainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *QuoteRequestDtoIntentMetadataOracleInner) SetChain(v string) {
	o.Chain = v
}

// GetAddress returns the Address field value
func (o *QuoteRequestDtoIntentMetadataOracleInner) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *QuoteRequestDtoIntentMetadataOracleInner) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *QuoteRequestDtoIntentMetadataOracleInner) SetAddress(v string) {
	o.Address = v
}

func (o QuoteRequestDtoIntentMetadataOracleInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteRequestDtoIntentMetadataOracleInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chain"] = o.Chain
	toSerialize["address"] = o.Address
	return toSerialize, nil
}

func (o *QuoteRequestDtoIntentMetadataOracleInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"chain",
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuoteRequestDtoIntentMetadataOracleInner := _QuoteRequestDtoIntentMetadataOracleInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuoteRequestDtoIntentMetadataOracleInner)

	if err != nil {
		return err
	}

	*o = QuoteRequestDtoIntentMetadataOracleInner(varQuoteRequestDtoIntentMetadataOracleInner)

	return err
}

type NullableQuoteRequestDtoIntentMetadataOracleInner struct {
	value *QuoteRequestDtoIntentMetadataOracleInner
	isSet bool
}

func (v NullableQuoteRequestDtoIntentMetadataOracleInner) Get() *QuoteRequestDtoIntentMetadataOracleInner {
	return v.value
}

func (v *NullableQuoteRequestDtoIntentMetadataOracleInner) Set(val *QuoteRequestDtoIntentMetadataOracleInner) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteRequestDtoIntentMetadataOracleInner) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteRequestDtoIntentMetadataOracleInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteRequestDtoIntentMetadataOracleInner(val *QuoteRequestDtoIntentMetadataOracleInner) *NullableQuoteRequestDtoIntentMetadataOracleInner {
	return &NullableQuoteRequestDtoIntentMetadataOracleInner{value: val, isSet: true}
}

func (v NullableQuoteRequestDtoIntentMetadataOracleInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteRequestDtoIntentMetadataOracleInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
