/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.20
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
)

// checks if the OifQuotePreviewDtoInputsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OifQuotePreviewDtoInputsInner{}

// OifQuotePreviewDtoInputsInner struct for OifQuotePreviewDtoInputsInner
type OifQuotePreviewDtoInputsInner struct {
	User                 *string `json:"user,omitempty"`
	Asset                *string `json:"asset,omitempty"`
	Amount               *string `json:"amount,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OifQuotePreviewDtoInputsInner OifQuotePreviewDtoInputsInner

// NewOifQuotePreviewDtoInputsInner instantiates a new OifQuotePreviewDtoInputsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOifQuotePreviewDtoInputsInner() *OifQuotePreviewDtoInputsInner {
	this := OifQuotePreviewDtoInputsInner{}
	return &this
}

// NewOifQuotePreviewDtoInputsInnerWithDefaults instantiates a new OifQuotePreviewDtoInputsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOifQuotePreviewDtoInputsInnerWithDefaults() *OifQuotePreviewDtoInputsInner {
	this := OifQuotePreviewDtoInputsInner{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *OifQuotePreviewDtoInputsInner) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OifQuotePreviewDtoInputsInner) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *OifQuotePreviewDtoInputsInner) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *OifQuotePreviewDtoInputsInner) SetUser(v string) {
	o.User = &v
}

// GetAsset returns the Asset field value if set, zero value otherwise.
func (o *OifQuotePreviewDtoInputsInner) GetAsset() string {
	if o == nil || IsNil(o.Asset) {
		var ret string
		return ret
	}
	return *o.Asset
}

// GetAssetOk returns a tuple with the Asset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OifQuotePreviewDtoInputsInner) GetAssetOk() (*string, bool) {
	if o == nil || IsNil(o.Asset) {
		return nil, false
	}
	return o.Asset, true
}

// HasAsset returns a boolean if a field has been set.
func (o *OifQuotePreviewDtoInputsInner) HasAsset() bool {
	if o != nil && !IsNil(o.Asset) {
		return true
	}

	return false
}

// SetAsset gets a reference to the given string and assigns it to the Asset field.
func (o *OifQuotePreviewDtoInputsInner) SetAsset(v string) {
	o.Asset = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *OifQuotePreviewDtoInputsInner) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OifQuotePreviewDtoInputsInner) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *OifQuotePreviewDtoInputsInner) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *OifQuotePreviewDtoInputsInner) SetAmount(v string) {
	o.Amount = &v
}

func (o OifQuotePreviewDtoInputsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OifQuotePreviewDtoInputsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Asset) {
		toSerialize["asset"] = o.Asset
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OifQuotePreviewDtoInputsInner) UnmarshalJSON(data []byte) (err error) {
	varOifQuotePreviewDtoInputsInner := _OifQuotePreviewDtoInputsInner{}

	err = json.Unmarshal(data, &varOifQuotePreviewDtoInputsInner)

	if err != nil {
		return err
	}

	*o = OifQuotePreviewDtoInputsInner(varOifQuotePreviewDtoInputsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "user")
		delete(additionalProperties, "asset")
		delete(additionalProperties, "amount")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOifQuotePreviewDtoInputsInner struct {
	value *OifQuotePreviewDtoInputsInner
	isSet bool
}

func (v NullableOifQuotePreviewDtoInputsInner) Get() *OifQuotePreviewDtoInputsInner {
	return v.value
}

func (v *NullableOifQuotePreviewDtoInputsInner) Set(val *OifQuotePreviewDtoInputsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOifQuotePreviewDtoInputsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOifQuotePreviewDtoInputsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOifQuotePreviewDtoInputsInner(val *OifQuotePreviewDtoInputsInner) *NullableOifQuotePreviewDtoInputsInner {
	return &NullableOifQuotePreviewDtoInputsInner{value: val, isSet: true}
}

func (v NullableOifQuotePreviewDtoInputsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOifQuotePreviewDtoInputsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
