/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
)

// checks if the RegisterAccountV1ResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterAccountV1ResponseDto{}

// RegisterAccountV1ResponseDto struct for RegisterAccountV1ResponseDto
type RegisterAccountV1ResponseDto struct {
	// Indicates if registration was successful
	Success              bool `json:"success"`
	AdditionalProperties map[string]interface{}
}

type _RegisterAccountV1ResponseDto RegisterAccountV1ResponseDto

// NewRegisterAccountV1ResponseDto instantiates a new RegisterAccountV1ResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterAccountV1ResponseDto(success bool) *RegisterAccountV1ResponseDto {
	this := RegisterAccountV1ResponseDto{}
	this.Success = success
	return &this
}

// NewRegisterAccountV1ResponseDtoWithDefaults instantiates a new RegisterAccountV1ResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterAccountV1ResponseDtoWithDefaults() *RegisterAccountV1ResponseDto {
	this := RegisterAccountV1ResponseDto{}
	return &this
}

// GetSuccess returns the Success field value
func (o *RegisterAccountV1ResponseDto) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *RegisterAccountV1ResponseDto) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *RegisterAccountV1ResponseDto) SetSuccess(v bool) {
	o.Success = v
}

func (o RegisterAccountV1ResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterAccountV1ResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RegisterAccountV1ResponseDto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varRegisterAccountV1ResponseDto := _RegisterAccountV1ResponseDto{}

	err = json.Unmarshal(data, &varRegisterAccountV1ResponseDto)

	if err != nil {
		return err
	}

	*o = RegisterAccountV1ResponseDto(varRegisterAccountV1ResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRegisterAccountV1ResponseDto struct {
	value *RegisterAccountV1ResponseDto
	isSet bool
}

func (v NullableRegisterAccountV1ResponseDto) Get() *RegisterAccountV1ResponseDto {
	return v.value
}

func (v *NullableRegisterAccountV1ResponseDto) Set(val *RegisterAccountV1ResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterAccountV1ResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterAccountV1ResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterAccountV1ResponseDto(val *RegisterAccountV1ResponseDto) *NullableRegisterAccountV1ResponseDto {
	return &NullableRegisterAccountV1ResponseDto{value: val, isSet: true}
}

func (v NullableRegisterAccountV1ResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterAccountV1ResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
