/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.20
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
)

// checks if the OifQuoteRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OifQuoteRequestDto{}

// OifQuoteRequestDto struct for OifQuoteRequestDto
type OifQuoteRequestDto struct {
	// User requesting the quote and recipient of refund inputs in case of failures. Must be provided in ERC-7930 interoperable address format.
	User   string                   `json:"user"`
	Intent OifQuoteRequestDtoIntent `json:"intent"`
	// Order types supported by the provider
	SupportedTypes       []string `json:"supportedTypes"`
	AdditionalProperties map[string]interface{}
}

type _OifQuoteRequestDto OifQuoteRequestDto

// NewOifQuoteRequestDto instantiates a new OifQuoteRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOifQuoteRequestDto(user string, intent OifQuoteRequestDtoIntent, supportedTypes []string) *OifQuoteRequestDto {
	this := OifQuoteRequestDto{}
	this.User = user
	this.Intent = intent
	this.SupportedTypes = supportedTypes
	return &this
}

// NewOifQuoteRequestDtoWithDefaults instantiates a new OifQuoteRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOifQuoteRequestDtoWithDefaults() *OifQuoteRequestDto {
	this := OifQuoteRequestDto{}
	return &this
}

// GetUser returns the User field value
func (o *OifQuoteRequestDto) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *OifQuoteRequestDto) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *OifQuoteRequestDto) SetUser(v string) {
	o.User = v
}

// GetIntent returns the Intent field value
func (o *OifQuoteRequestDto) GetIntent() OifQuoteRequestDtoIntent {
	if o == nil {
		var ret OifQuoteRequestDtoIntent
		return ret
	}

	return o.Intent
}

// GetIntentOk returns a tuple with the Intent field value
// and a boolean to check if the value has been set.
func (o *OifQuoteRequestDto) GetIntentOk() (*OifQuoteRequestDtoIntent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Intent, true
}

// SetIntent sets field value
func (o *OifQuoteRequestDto) SetIntent(v OifQuoteRequestDtoIntent) {
	o.Intent = v
}

// GetSupportedTypes returns the SupportedTypes field value
func (o *OifQuoteRequestDto) GetSupportedTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SupportedTypes
}

// GetSupportedTypesOk returns a tuple with the SupportedTypes field value
// and a boolean to check if the value has been set.
func (o *OifQuoteRequestDto) GetSupportedTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupportedTypes, true
}

// SetSupportedTypes sets field value
func (o *OifQuoteRequestDto) SetSupportedTypes(v []string) {
	o.SupportedTypes = v
}

func (o OifQuoteRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OifQuoteRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user"] = o.User
	toSerialize["intent"] = o.Intent
	toSerialize["supportedTypes"] = o.SupportedTypes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OifQuoteRequestDto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varOifQuoteRequestDto := _OifQuoteRequestDto{}

	err = json.Unmarshal(data, &varOifQuoteRequestDto)

	if err != nil {
		return err
	}

	*o = OifQuoteRequestDto(varOifQuoteRequestDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "user")
		delete(additionalProperties, "intent")
		delete(additionalProperties, "supportedTypes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOifQuoteRequestDto struct {
	value *OifQuoteRequestDto
	isSet bool
}

func (v NullableOifQuoteRequestDto) Get() *OifQuoteRequestDto {
	return v.value
}

func (v *NullableOifQuoteRequestDto) Set(val *OifQuoteRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableOifQuoteRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableOifQuoteRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOifQuoteRequestDto(val *OifQuoteRequestDto) *NullableOifQuoteRequestDto {
	return &NullableOifQuoteRequestDto{value: val, isSet: true}
}

func (v NullableOifQuoteRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOifQuoteRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
