/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
)

// checks if the ContractsByKindDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContractsByKindDto{}

// ContractsByKindDto struct for ContractsByKindDto
type ContractsByKindDto struct {
	// Oracle contracts the solver supports
	Oracle []ChainAddressDto `json:"oracle"`
	// Input settler contracts the solver supports
	InputSettler []ChainAddressDto `json:"inputSettler"`
	// Output settler contracts the solver supports
	OutputSettler        []ChainAddressDto `json:"outputSettler"`
	AdditionalProperties map[string]interface{}
}

type _ContractsByKindDto ContractsByKindDto

// NewContractsByKindDto instantiates a new ContractsByKindDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContractsByKindDto(oracle []ChainAddressDto, inputSettler []ChainAddressDto, outputSettler []ChainAddressDto) *ContractsByKindDto {
	this := ContractsByKindDto{}
	this.Oracle = oracle
	this.InputSettler = inputSettler
	this.OutputSettler = outputSettler
	return &this
}

// NewContractsByKindDtoWithDefaults instantiates a new ContractsByKindDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContractsByKindDtoWithDefaults() *ContractsByKindDto {
	this := ContractsByKindDto{}
	return &this
}

// GetOracle returns the Oracle field value
func (o *ContractsByKindDto) GetOracle() []ChainAddressDto {
	if o == nil {
		var ret []ChainAddressDto
		return ret
	}

	return o.Oracle
}

// GetOracleOk returns a tuple with the Oracle field value
// and a boolean to check if the value has been set.
func (o *ContractsByKindDto) GetOracleOk() ([]ChainAddressDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Oracle, true
}

// SetOracle sets field value
func (o *ContractsByKindDto) SetOracle(v []ChainAddressDto) {
	o.Oracle = v
}

// GetInputSettler returns the InputSettler field value
func (o *ContractsByKindDto) GetInputSettler() []ChainAddressDto {
	if o == nil {
		var ret []ChainAddressDto
		return ret
	}

	return o.InputSettler
}

// GetInputSettlerOk returns a tuple with the InputSettler field value
// and a boolean to check if the value has been set.
func (o *ContractsByKindDto) GetInputSettlerOk() ([]ChainAddressDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.InputSettler, true
}

// SetInputSettler sets field value
func (o *ContractsByKindDto) SetInputSettler(v []ChainAddressDto) {
	o.InputSettler = v
}

// GetOutputSettler returns the OutputSettler field value
func (o *ContractsByKindDto) GetOutputSettler() []ChainAddressDto {
	if o == nil {
		var ret []ChainAddressDto
		return ret
	}

	return o.OutputSettler
}

// GetOutputSettlerOk returns a tuple with the OutputSettler field value
// and a boolean to check if the value has been set.
func (o *ContractsByKindDto) GetOutputSettlerOk() ([]ChainAddressDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.OutputSettler, true
}

// SetOutputSettler sets field value
func (o *ContractsByKindDto) SetOutputSettler(v []ChainAddressDto) {
	o.OutputSettler = v
}

func (o ContractsByKindDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContractsByKindDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["oracle"] = o.Oracle
	toSerialize["inputSettler"] = o.InputSettler
	toSerialize["outputSettler"] = o.OutputSettler

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ContractsByKindDto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varContractsByKindDto := _ContractsByKindDto{}

	err = json.Unmarshal(data, &varContractsByKindDto)

	if err != nil {
		return err
	}

	*o = ContractsByKindDto(varContractsByKindDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "oracle")
		delete(additionalProperties, "inputSettler")
		delete(additionalProperties, "outputSettler")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableContractsByKindDto struct {
	value *ContractsByKindDto
	isSet bool
}

func (v NullableContractsByKindDto) Get() *ContractsByKindDto {
	return v.value
}

func (v *NullableContractsByKindDto) Set(val *ContractsByKindDto) {
	v.value = val
	v.isSet = true
}

func (v NullableContractsByKindDto) IsSet() bool {
	return v.isSet
}

func (v *NullableContractsByKindDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContractsByKindDto(val *ContractsByKindDto) *NullableContractsByKindDto {
	return &NullableContractsByKindDto{value: val, isSet: true}
}

func (v NullableContractsByKindDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContractsByKindDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
