/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UnregisterSolverAddressDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnregisterSolverAddressDto{}

// UnregisterSolverAddressDto struct for UnregisterSolverAddressDto
type UnregisterSolverAddressDto struct {
	// The address of the solver
	Address string `json:"address"`
}

type _UnregisterSolverAddressDto UnregisterSolverAddressDto

// NewUnregisterSolverAddressDto instantiates a new UnregisterSolverAddressDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnregisterSolverAddressDto(address string) *UnregisterSolverAddressDto {
	this := UnregisterSolverAddressDto{}
	this.Address = address
	return &this
}

// NewUnregisterSolverAddressDtoWithDefaults instantiates a new UnregisterSolverAddressDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnregisterSolverAddressDtoWithDefaults() *UnregisterSolverAddressDto {
	this := UnregisterSolverAddressDto{}
	return &this
}

// GetAddress returns the Address field value
func (o *UnregisterSolverAddressDto) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *UnregisterSolverAddressDto) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *UnregisterSolverAddressDto) SetAddress(v string) {
	o.Address = v
}

func (o UnregisterSolverAddressDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnregisterSolverAddressDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	return toSerialize, nil
}

func (o *UnregisterSolverAddressDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnregisterSolverAddressDto := _UnregisterSolverAddressDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnregisterSolverAddressDto)

	if err != nil {
		return err
	}

	*o = UnregisterSolverAddressDto(varUnregisterSolverAddressDto)

	return err
}

type NullableUnregisterSolverAddressDto struct {
	value *UnregisterSolverAddressDto
	isSet bool
}

func (v NullableUnregisterSolverAddressDto) Get() *UnregisterSolverAddressDto {
	return v.value
}

func (v *NullableUnregisterSolverAddressDto) Set(val *UnregisterSolverAddressDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUnregisterSolverAddressDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUnregisterSolverAddressDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnregisterSolverAddressDto(val *UnregisterSolverAddressDto) *NullableUnregisterSolverAddressDto {
	return &NullableUnregisterSolverAddressDto{value: val, isSet: true}
}

func (v NullableUnregisterSolverAddressDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnregisterSolverAddressDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
