/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the QuotePreviewDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuotePreviewDto{}

// QuotePreviewDto struct for QuotePreviewDto
type QuotePreviewDto struct {
	// Inputs for the preview
	Inputs []InputDto `json:"inputs"`
	// Outputs for the preview
	Outputs []OutputDto `json:"outputs"`
}

type _QuotePreviewDto QuotePreviewDto

// NewQuotePreviewDto instantiates a new QuotePreviewDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuotePreviewDto(inputs []InputDto, outputs []OutputDto) *QuotePreviewDto {
	this := QuotePreviewDto{}
	this.Inputs = inputs
	this.Outputs = outputs
	return &this
}

// NewQuotePreviewDtoWithDefaults instantiates a new QuotePreviewDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotePreviewDtoWithDefaults() *QuotePreviewDto {
	this := QuotePreviewDto{}
	return &this
}

// GetInputs returns the Inputs field value
func (o *QuotePreviewDto) GetInputs() []InputDto {
	if o == nil {
		var ret []InputDto
		return ret
	}

	return o.Inputs
}

// GetInputsOk returns a tuple with the Inputs field value
// and a boolean to check if the value has been set.
func (o *QuotePreviewDto) GetInputsOk() ([]InputDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Inputs, true
}

// SetInputs sets field value
func (o *QuotePreviewDto) SetInputs(v []InputDto) {
	o.Inputs = v
}

// GetOutputs returns the Outputs field value
func (o *QuotePreviewDto) GetOutputs() []OutputDto {
	if o == nil {
		var ret []OutputDto
		return ret
	}

	return o.Outputs
}

// GetOutputsOk returns a tuple with the Outputs field value
// and a boolean to check if the value has been set.
func (o *QuotePreviewDto) GetOutputsOk() ([]OutputDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Outputs, true
}

// SetOutputs sets field value
func (o *QuotePreviewDto) SetOutputs(v []OutputDto) {
	o.Outputs = v
}

func (o QuotePreviewDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuotePreviewDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["inputs"] = o.Inputs
	toSerialize["outputs"] = o.Outputs
	return toSerialize, nil
}

func (o *QuotePreviewDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"inputs",
		"outputs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuotePreviewDto := _QuotePreviewDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuotePreviewDto)

	if err != nil {
		return err
	}

	*o = QuotePreviewDto(varQuotePreviewDto)

	return err
}

type NullableQuotePreviewDto struct {
	value *QuotePreviewDto
	isSet bool
}

func (v NullableQuotePreviewDto) Get() *QuotePreviewDto {
	return v.value
}

func (v *NullableQuotePreviewDto) Set(val *QuotePreviewDto) {
	v.value = val
	v.isSet = true
}

func (v NullableQuotePreviewDto) IsSet() bool {
	return v.isSet
}

func (v *NullableQuotePreviewDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuotePreviewDto(val *QuotePreviewDto) *NullableQuotePreviewDto {
	return &NullableQuotePreviewDto{value: val, isSet: true}
}

func (v NullableQuotePreviewDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuotePreviewDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
