/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.20
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
)

// checks if the QuoteOracleMetadataDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteOracleMetadataDto{}

// QuoteOracleMetadataDto struct for QuoteOracleMetadataDto
type QuoteOracleMetadataDto struct {
	// Resolved input oracle in the source chain native address format. For cross-chain Solana origins, this is the Polymer oracle state PDA.
	Input string `json:"input"`
	// Oracle identity encoded in the order output, rendered in the destination chain native address format. For cross-chain Polymer routes with EVM or Tron on both sides, this identifies the source chain oracle and can differ from the destination deployment accepted in intent.metadata.oracle. Solana routes retain their protocol-specific oracle identities. For same-chain quotes, both oracle fields identify the output settler.
	Output               string `json:"output"`
	AdditionalProperties map[string]interface{}
}

type _QuoteOracleMetadataDto QuoteOracleMetadataDto

// NewQuoteOracleMetadataDto instantiates a new QuoteOracleMetadataDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteOracleMetadataDto(input string, output string) *QuoteOracleMetadataDto {
	this := QuoteOracleMetadataDto{}
	this.Input = input
	this.Output = output
	return &this
}

// NewQuoteOracleMetadataDtoWithDefaults instantiates a new QuoteOracleMetadataDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteOracleMetadataDtoWithDefaults() *QuoteOracleMetadataDto {
	this := QuoteOracleMetadataDto{}
	return &this
}

// GetInput returns the Input field value
func (o *QuoteOracleMetadataDto) GetInput() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *QuoteOracleMetadataDto) GetInputOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Input, true
}

// SetInput sets field value
func (o *QuoteOracleMetadataDto) SetInput(v string) {
	o.Input = v
}

// GetOutput returns the Output field value
func (o *QuoteOracleMetadataDto) GetOutput() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Output
}

// GetOutputOk returns a tuple with the Output field value
// and a boolean to check if the value has been set.
func (o *QuoteOracleMetadataDto) GetOutputOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Output, true
}

// SetOutput sets field value
func (o *QuoteOracleMetadataDto) SetOutput(v string) {
	o.Output = v
}

func (o QuoteOracleMetadataDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteOracleMetadataDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["input"] = o.Input
	toSerialize["output"] = o.Output

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QuoteOracleMetadataDto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varQuoteOracleMetadataDto := _QuoteOracleMetadataDto{}

	err = json.Unmarshal(data, &varQuoteOracleMetadataDto)

	if err != nil {
		return err
	}

	*o = QuoteOracleMetadataDto(varQuoteOracleMetadataDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "input")
		delete(additionalProperties, "output")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQuoteOracleMetadataDto struct {
	value *QuoteOracleMetadataDto
	isSet bool
}

func (v NullableQuoteOracleMetadataDto) Get() *QuoteOracleMetadataDto {
	return v.value
}

func (v *NullableQuoteOracleMetadataDto) Set(val *QuoteOracleMetadataDto) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteOracleMetadataDto) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteOracleMetadataDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteOracleMetadataDto(val *QuoteOracleMetadataDto) *NullableQuoteOracleMetadataDto {
	return &NullableQuoteOracleMetadataDto{value: val, isSet: true}
}

func (v NullableQuoteOracleMetadataDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteOracleMetadataDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
