/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UnregisterAccountV1ResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnregisterAccountV1ResponseDto{}

// UnregisterAccountV1ResponseDto struct for UnregisterAccountV1ResponseDto
type UnregisterAccountV1ResponseDto struct {
	// Indicates if unregistration was successful
	Success bool `json:"success"`
}

type _UnregisterAccountV1ResponseDto UnregisterAccountV1ResponseDto

// NewUnregisterAccountV1ResponseDto instantiates a new UnregisterAccountV1ResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnregisterAccountV1ResponseDto(success bool) *UnregisterAccountV1ResponseDto {
	this := UnregisterAccountV1ResponseDto{}
	this.Success = success
	return &this
}

// NewUnregisterAccountV1ResponseDtoWithDefaults instantiates a new UnregisterAccountV1ResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnregisterAccountV1ResponseDtoWithDefaults() *UnregisterAccountV1ResponseDto {
	this := UnregisterAccountV1ResponseDto{}
	return &this
}

// GetSuccess returns the Success field value
func (o *UnregisterAccountV1ResponseDto) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *UnregisterAccountV1ResponseDto) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *UnregisterAccountV1ResponseDto) SetSuccess(v bool) {
	o.Success = v
}

func (o UnregisterAccountV1ResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnregisterAccountV1ResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	return toSerialize, nil
}

func (o *UnregisterAccountV1ResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnregisterAccountV1ResponseDto := _UnregisterAccountV1ResponseDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnregisterAccountV1ResponseDto)

	if err != nil {
		return err
	}

	*o = UnregisterAccountV1ResponseDto(varUnregisterAccountV1ResponseDto)

	return err
}

type NullableUnregisterAccountV1ResponseDto struct {
	value *UnregisterAccountV1ResponseDto
	isSet bool
}

func (v NullableUnregisterAccountV1ResponseDto) Get() *UnregisterAccountV1ResponseDto {
	return v.value
}

func (v *NullableUnregisterAccountV1ResponseDto) Set(val *UnregisterAccountV1ResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUnregisterAccountV1ResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUnregisterAccountV1ResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnregisterAccountV1ResponseDto(val *UnregisterAccountV1ResponseDto) *NullableUnregisterAccountV1ResponseDto {
	return &NullableUnregisterAccountV1ResponseDto{value: val, isSet: true}
}

func (v NullableUnregisterAccountV1ResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnregisterAccountV1ResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
