/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.20
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
)

// checks if the GetOifQuotesResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOifQuotesResponseDto{}

// GetOifQuotesResponseDto struct for GetOifQuotesResponseDto
type GetOifQuotesResponseDto struct {
	// Array of generated quotes
	Quotes               []OifQuoteDto `json:"quotes"`
	AdditionalProperties map[string]interface{}
}

type _GetOifQuotesResponseDto GetOifQuotesResponseDto

// NewGetOifQuotesResponseDto instantiates a new GetOifQuotesResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOifQuotesResponseDto(quotes []OifQuoteDto) *GetOifQuotesResponseDto {
	this := GetOifQuotesResponseDto{}
	this.Quotes = quotes
	return &this
}

// NewGetOifQuotesResponseDtoWithDefaults instantiates a new GetOifQuotesResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOifQuotesResponseDtoWithDefaults() *GetOifQuotesResponseDto {
	this := GetOifQuotesResponseDto{}
	return &this
}

// GetQuotes returns the Quotes field value
func (o *GetOifQuotesResponseDto) GetQuotes() []OifQuoteDto {
	if o == nil {
		var ret []OifQuoteDto
		return ret
	}

	return o.Quotes
}

// GetQuotesOk returns a tuple with the Quotes field value
// and a boolean to check if the value has been set.
func (o *GetOifQuotesResponseDto) GetQuotesOk() ([]OifQuoteDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Quotes, true
}

// SetQuotes sets field value
func (o *GetOifQuotesResponseDto) SetQuotes(v []OifQuoteDto) {
	o.Quotes = v
}

func (o GetOifQuotesResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOifQuotesResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["quotes"] = o.Quotes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetOifQuotesResponseDto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varGetOifQuotesResponseDto := _GetOifQuotesResponseDto{}

	err = json.Unmarshal(data, &varGetOifQuotesResponseDto)

	if err != nil {
		return err
	}

	*o = GetOifQuotesResponseDto(varGetOifQuotesResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "quotes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetOifQuotesResponseDto struct {
	value *GetOifQuotesResponseDto
	isSet bool
}

func (v NullableGetOifQuotesResponseDto) Get() *GetOifQuotesResponseDto {
	return v.value
}

func (v *NullableGetOifQuotesResponseDto) Set(val *GetOifQuotesResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOifQuotesResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOifQuotesResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOifQuotesResponseDto(val *GetOifQuotesResponseDto) *NullableGetOifQuotesResponseDto {
	return &NullableGetOifQuotesResponseDto{value: val, isSet: true}
}

func (v NullableGetOifQuotesResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOifQuotesResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
