/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RegisterSolverAddressDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterSolverAddressDto{}

// RegisterSolverAddressDto struct for RegisterSolverAddressDto
type RegisterSolverAddressDto struct {
	// The address of the solver
	Address string `json:"address"`
	// The message to sign
	Message string `json:"message"`
	// The signature of the message
	Signature string `json:"signature"`
	// The chain ID where the address exists (required for EIP-1271 validation). Can empty in case of ECDSA signature
	ChainId *string `json:"chainId,omitempty"`
}

type _RegisterSolverAddressDto RegisterSolverAddressDto

// NewRegisterSolverAddressDto instantiates a new RegisterSolverAddressDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterSolverAddressDto(address string, message string, signature string) *RegisterSolverAddressDto {
	this := RegisterSolverAddressDto{}
	this.Address = address
	this.Message = message
	this.Signature = signature
	return &this
}

// NewRegisterSolverAddressDtoWithDefaults instantiates a new RegisterSolverAddressDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterSolverAddressDtoWithDefaults() *RegisterSolverAddressDto {
	this := RegisterSolverAddressDto{}
	return &this
}

// GetAddress returns the Address field value
func (o *RegisterSolverAddressDto) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *RegisterSolverAddressDto) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *RegisterSolverAddressDto) SetAddress(v string) {
	o.Address = v
}

// GetMessage returns the Message field value
func (o *RegisterSolverAddressDto) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *RegisterSolverAddressDto) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *RegisterSolverAddressDto) SetMessage(v string) {
	o.Message = v
}

// GetSignature returns the Signature field value
func (o *RegisterSolverAddressDto) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *RegisterSolverAddressDto) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *RegisterSolverAddressDto) SetSignature(v string) {
	o.Signature = v
}

// GetChainId returns the ChainId field value if set, zero value otherwise.
func (o *RegisterSolverAddressDto) GetChainId() string {
	if o == nil || IsNil(o.ChainId) {
		var ret string
		return ret
	}
	return *o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterSolverAddressDto) GetChainIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChainId) {
		return nil, false
	}
	return o.ChainId, true
}

// HasChainId returns a boolean if a field has been set.
func (o *RegisterSolverAddressDto) HasChainId() bool {
	if o != nil && !IsNil(o.ChainId) {
		return true
	}

	return false
}

// SetChainId gets a reference to the given string and assigns it to the ChainId field.
func (o *RegisterSolverAddressDto) SetChainId(v string) {
	o.ChainId = &v
}

func (o RegisterSolverAddressDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterSolverAddressDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["message"] = o.Message
	toSerialize["signature"] = o.Signature
	if !IsNil(o.ChainId) {
		toSerialize["chainId"] = o.ChainId
	}
	return toSerialize, nil
}

func (o *RegisterSolverAddressDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"message",
		"signature",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterSolverAddressDto := _RegisterSolverAddressDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterSolverAddressDto)

	if err != nil {
		return err
	}

	*o = RegisterSolverAddressDto(varRegisterSolverAddressDto)

	return err
}

type NullableRegisterSolverAddressDto struct {
	value *RegisterSolverAddressDto
	isSet bool
}

func (v NullableRegisterSolverAddressDto) Get() *RegisterSolverAddressDto {
	return v.value
}

func (v *NullableRegisterSolverAddressDto) Set(val *RegisterSolverAddressDto) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterSolverAddressDto) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterSolverAddressDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterSolverAddressDto(val *RegisterSolverAddressDto) *NullableRegisterSolverAddressDto {
	return &NullableRegisterSolverAddressDto{value: val, isSet: true}
}

func (v NullableRegisterSolverAddressDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterSolverAddressDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
