/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
)

// checks if the OifQuotePreviewDtoOutputsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OifQuotePreviewDtoOutputsInner{}

// OifQuotePreviewDtoOutputsInner struct for OifQuotePreviewDtoOutputsInner
type OifQuotePreviewDtoOutputsInner struct {
	Receiver             *string `json:"receiver,omitempty"`
	Asset                *string `json:"asset,omitempty"`
	Amount               *string `json:"amount,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OifQuotePreviewDtoOutputsInner OifQuotePreviewDtoOutputsInner

// NewOifQuotePreviewDtoOutputsInner instantiates a new OifQuotePreviewDtoOutputsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOifQuotePreviewDtoOutputsInner() *OifQuotePreviewDtoOutputsInner {
	this := OifQuotePreviewDtoOutputsInner{}
	return &this
}

// NewOifQuotePreviewDtoOutputsInnerWithDefaults instantiates a new OifQuotePreviewDtoOutputsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOifQuotePreviewDtoOutputsInnerWithDefaults() *OifQuotePreviewDtoOutputsInner {
	this := OifQuotePreviewDtoOutputsInner{}
	return &this
}

// GetReceiver returns the Receiver field value if set, zero value otherwise.
func (o *OifQuotePreviewDtoOutputsInner) GetReceiver() string {
	if o == nil || IsNil(o.Receiver) {
		var ret string
		return ret
	}
	return *o.Receiver
}

// GetReceiverOk returns a tuple with the Receiver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OifQuotePreviewDtoOutputsInner) GetReceiverOk() (*string, bool) {
	if o == nil || IsNil(o.Receiver) {
		return nil, false
	}
	return o.Receiver, true
}

// HasReceiver returns a boolean if a field has been set.
func (o *OifQuotePreviewDtoOutputsInner) HasReceiver() bool {
	if o != nil && !IsNil(o.Receiver) {
		return true
	}

	return false
}

// SetReceiver gets a reference to the given string and assigns it to the Receiver field.
func (o *OifQuotePreviewDtoOutputsInner) SetReceiver(v string) {
	o.Receiver = &v
}

// GetAsset returns the Asset field value if set, zero value otherwise.
func (o *OifQuotePreviewDtoOutputsInner) GetAsset() string {
	if o == nil || IsNil(o.Asset) {
		var ret string
		return ret
	}
	return *o.Asset
}

// GetAssetOk returns a tuple with the Asset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OifQuotePreviewDtoOutputsInner) GetAssetOk() (*string, bool) {
	if o == nil || IsNil(o.Asset) {
		return nil, false
	}
	return o.Asset, true
}

// HasAsset returns a boolean if a field has been set.
func (o *OifQuotePreviewDtoOutputsInner) HasAsset() bool {
	if o != nil && !IsNil(o.Asset) {
		return true
	}

	return false
}

// SetAsset gets a reference to the given string and assigns it to the Asset field.
func (o *OifQuotePreviewDtoOutputsInner) SetAsset(v string) {
	o.Asset = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *OifQuotePreviewDtoOutputsInner) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OifQuotePreviewDtoOutputsInner) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *OifQuotePreviewDtoOutputsInner) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *OifQuotePreviewDtoOutputsInner) SetAmount(v string) {
	o.Amount = &v
}

func (o OifQuotePreviewDtoOutputsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OifQuotePreviewDtoOutputsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Receiver) {
		toSerialize["receiver"] = o.Receiver
	}
	if !IsNil(o.Asset) {
		toSerialize["asset"] = o.Asset
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OifQuotePreviewDtoOutputsInner) UnmarshalJSON(data []byte) (err error) {
	varOifQuotePreviewDtoOutputsInner := _OifQuotePreviewDtoOutputsInner{}

	err = json.Unmarshal(data, &varOifQuotePreviewDtoOutputsInner)

	if err != nil {
		return err
	}

	*o = OifQuotePreviewDtoOutputsInner(varOifQuotePreviewDtoOutputsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "receiver")
		delete(additionalProperties, "asset")
		delete(additionalProperties, "amount")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOifQuotePreviewDtoOutputsInner struct {
	value *OifQuotePreviewDtoOutputsInner
	isSet bool
}

func (v NullableOifQuotePreviewDtoOutputsInner) Get() *OifQuotePreviewDtoOutputsInner {
	return v.value
}

func (v *NullableOifQuotePreviewDtoOutputsInner) Set(val *OifQuotePreviewDtoOutputsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOifQuotePreviewDtoOutputsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOifQuotePreviewDtoOutputsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOifQuotePreviewDtoOutputsInner(val *OifQuotePreviewDtoOutputsInner) *NullableOifQuotePreviewDtoOutputsInner {
	return &NullableOifQuotePreviewDtoOutputsInner{value: val, isSet: true}
}

func (v NullableOifQuotePreviewDtoOutputsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOifQuotePreviewDtoOutputsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
