/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.20
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
)

// checks if the CatalogOracleDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogOracleDto{}

// CatalogOracleDto struct for CatalogOracleDto
type CatalogOracleDto struct {
	// Stable lowercase oracle identifier.
	Id string `json:"id"`
	// Display name of the oracle.
	Name string `json:"name"`
	// Registered deployments for this oracle.
	Deployments          []CatalogOracleDeploymentDto `json:"deployments"`
	AdditionalProperties map[string]interface{}
}

type _CatalogOracleDto CatalogOracleDto

// NewCatalogOracleDto instantiates a new CatalogOracleDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogOracleDto(id string, name string, deployments []CatalogOracleDeploymentDto) *CatalogOracleDto {
	this := CatalogOracleDto{}
	this.Id = id
	this.Name = name
	this.Deployments = deployments
	return &this
}

// NewCatalogOracleDtoWithDefaults instantiates a new CatalogOracleDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogOracleDtoWithDefaults() *CatalogOracleDto {
	this := CatalogOracleDto{}
	return &this
}

// GetId returns the Id field value
func (o *CatalogOracleDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CatalogOracleDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CatalogOracleDto) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CatalogOracleDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CatalogOracleDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CatalogOracleDto) SetName(v string) {
	o.Name = v
}

// GetDeployments returns the Deployments field value
func (o *CatalogOracleDto) GetDeployments() []CatalogOracleDeploymentDto {
	if o == nil {
		var ret []CatalogOracleDeploymentDto
		return ret
	}

	return o.Deployments
}

// GetDeploymentsOk returns a tuple with the Deployments field value
// and a boolean to check if the value has been set.
func (o *CatalogOracleDto) GetDeploymentsOk() ([]CatalogOracleDeploymentDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Deployments, true
}

// SetDeployments sets field value
func (o *CatalogOracleDto) SetDeployments(v []CatalogOracleDeploymentDto) {
	o.Deployments = v
}

func (o CatalogOracleDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogOracleDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["deployments"] = o.Deployments

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CatalogOracleDto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varCatalogOracleDto := _CatalogOracleDto{}

	err = json.Unmarshal(data, &varCatalogOracleDto)

	if err != nil {
		return err
	}

	*o = CatalogOracleDto(varCatalogOracleDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "deployments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCatalogOracleDto struct {
	value *CatalogOracleDto
	isSet bool
}

func (v NullableCatalogOracleDto) Get() *CatalogOracleDto {
	return v.value
}

func (v *NullableCatalogOracleDto) Set(val *CatalogOracleDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogOracleDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogOracleDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogOracleDto(val *CatalogOracleDto) *NullableCatalogOracleDto {
	return &NullableCatalogOracleDto{value: val, isSet: true}
}

func (v NullableCatalogOracleDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogOracleDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
