/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// HttpErrorDtoMessage - struct for HttpErrorDtoMessage
type HttpErrorDtoMessage struct {
	ArrayOfString *[]string
	String        *string
}

// []stringAsHttpErrorDtoMessage is a convenience function that returns []string wrapped in HttpErrorDtoMessage
func ArrayOfStringAsHttpErrorDtoMessage(v *[]string) HttpErrorDtoMessage {
	return HttpErrorDtoMessage{
		ArrayOfString: v,
	}
}

// stringAsHttpErrorDtoMessage is a convenience function that returns string wrapped in HttpErrorDtoMessage
func StringAsHttpErrorDtoMessage(v *string) HttpErrorDtoMessage {
	return HttpErrorDtoMessage{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *HttpErrorDtoMessage) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ArrayOfString
	err = newStrictDecoder(data).Decode(&dst.ArrayOfString)
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			if err = validator.Validate(dst.ArrayOfString); err != nil {
				dst.ArrayOfString = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfString = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfString = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(HttpErrorDtoMessage)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(HttpErrorDtoMessage)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src HttpErrorDtoMessage) MarshalJSON() ([]byte, error) {
	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *HttpErrorDtoMessage) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfString != nil {
		return obj.ArrayOfString
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj HttpErrorDtoMessage) GetActualInstanceValue() interface{} {
	if obj.ArrayOfString != nil {
		return *obj.ArrayOfString
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableHttpErrorDtoMessage struct {
	value *HttpErrorDtoMessage
	isSet bool
}

func (v NullableHttpErrorDtoMessage) Get() *HttpErrorDtoMessage {
	return v.value
}

func (v *NullableHttpErrorDtoMessage) Set(val *HttpErrorDtoMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableHttpErrorDtoMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableHttpErrorDtoMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttpErrorDtoMessage(val *HttpErrorDtoMessage) *NullableHttpErrorDtoMessage {
	return &NullableHttpErrorDtoMessage{value: val, isSet: true}
}

func (v NullableHttpErrorDtoMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttpErrorDtoMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
