/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// OifUserOpenIntentOrderDtoOpenIntentTx - Open intent transaction. EVM produces hex calldata; Solana produces a base58 serialized VersionedTransaction whose recentBlockhash must be overwritten before signing; Tron produces hex calldata the client wraps in a TriggerSmartContract envelope.
type OifUserOpenIntentOrderDtoOpenIntentTx struct {
	OpenIntentEvmTxDto  *OpenIntentEvmTxDto
	OpenIntentSvmTxDto  *OpenIntentSvmTxDto
	OpenIntentTronTxDto *OpenIntentTronTxDto
}

// OpenIntentEvmTxDtoAsOifUserOpenIntentOrderDtoOpenIntentTx is a convenience function that returns OpenIntentEvmTxDto wrapped in OifUserOpenIntentOrderDtoOpenIntentTx
func OpenIntentEvmTxDtoAsOifUserOpenIntentOrderDtoOpenIntentTx(v *OpenIntentEvmTxDto) OifUserOpenIntentOrderDtoOpenIntentTx {
	return OifUserOpenIntentOrderDtoOpenIntentTx{
		OpenIntentEvmTxDto: v,
	}
}

// OpenIntentSvmTxDtoAsOifUserOpenIntentOrderDtoOpenIntentTx is a convenience function that returns OpenIntentSvmTxDto wrapped in OifUserOpenIntentOrderDtoOpenIntentTx
func OpenIntentSvmTxDtoAsOifUserOpenIntentOrderDtoOpenIntentTx(v *OpenIntentSvmTxDto) OifUserOpenIntentOrderDtoOpenIntentTx {
	return OifUserOpenIntentOrderDtoOpenIntentTx{
		OpenIntentSvmTxDto: v,
	}
}

// OpenIntentTronTxDtoAsOifUserOpenIntentOrderDtoOpenIntentTx is a convenience function that returns OpenIntentTronTxDto wrapped in OifUserOpenIntentOrderDtoOpenIntentTx
func OpenIntentTronTxDtoAsOifUserOpenIntentOrderDtoOpenIntentTx(v *OpenIntentTronTxDto) OifUserOpenIntentOrderDtoOpenIntentTx {
	return OifUserOpenIntentOrderDtoOpenIntentTx{
		OpenIntentTronTxDto: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *OifUserOpenIntentOrderDtoOpenIntentTx) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into OpenIntentEvmTxDto
	err = newStrictDecoder(data).Decode(&dst.OpenIntentEvmTxDto)
	if err == nil {
		jsonOpenIntentEvmTxDto, _ := json.Marshal(dst.OpenIntentEvmTxDto)
		if string(jsonOpenIntentEvmTxDto) == "{}" { // empty struct
			dst.OpenIntentEvmTxDto = nil
		} else {
			if err = validator.Validate(dst.OpenIntentEvmTxDto); err != nil {
				dst.OpenIntentEvmTxDto = nil
			} else {
				match++
			}
		}
	} else {
		dst.OpenIntentEvmTxDto = nil
	}

	// try to unmarshal data into OpenIntentSvmTxDto
	err = newStrictDecoder(data).Decode(&dst.OpenIntentSvmTxDto)
	if err == nil {
		jsonOpenIntentSvmTxDto, _ := json.Marshal(dst.OpenIntentSvmTxDto)
		if string(jsonOpenIntentSvmTxDto) == "{}" { // empty struct
			dst.OpenIntentSvmTxDto = nil
		} else {
			if err = validator.Validate(dst.OpenIntentSvmTxDto); err != nil {
				dst.OpenIntentSvmTxDto = nil
			} else {
				match++
			}
		}
	} else {
		dst.OpenIntentSvmTxDto = nil
	}

	// try to unmarshal data into OpenIntentTronTxDto
	err = newStrictDecoder(data).Decode(&dst.OpenIntentTronTxDto)
	if err == nil {
		jsonOpenIntentTronTxDto, _ := json.Marshal(dst.OpenIntentTronTxDto)
		if string(jsonOpenIntentTronTxDto) == "{}" { // empty struct
			dst.OpenIntentTronTxDto = nil
		} else {
			if err = validator.Validate(dst.OpenIntentTronTxDto); err != nil {
				dst.OpenIntentTronTxDto = nil
			} else {
				match++
			}
		}
	} else {
		dst.OpenIntentTronTxDto = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.OpenIntentEvmTxDto = nil
		dst.OpenIntentSvmTxDto = nil
		dst.OpenIntentTronTxDto = nil

		return fmt.Errorf("data matches more than one schema in oneOf(OifUserOpenIntentOrderDtoOpenIntentTx)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(OifUserOpenIntentOrderDtoOpenIntentTx)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src OifUserOpenIntentOrderDtoOpenIntentTx) MarshalJSON() ([]byte, error) {
	if src.OpenIntentEvmTxDto != nil {
		return json.Marshal(&src.OpenIntentEvmTxDto)
	}

	if src.OpenIntentSvmTxDto != nil {
		return json.Marshal(&src.OpenIntentSvmTxDto)
	}

	if src.OpenIntentTronTxDto != nil {
		return json.Marshal(&src.OpenIntentTronTxDto)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *OifUserOpenIntentOrderDtoOpenIntentTx) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.OpenIntentEvmTxDto != nil {
		return obj.OpenIntentEvmTxDto
	}

	if obj.OpenIntentSvmTxDto != nil {
		return obj.OpenIntentSvmTxDto
	}

	if obj.OpenIntentTronTxDto != nil {
		return obj.OpenIntentTronTxDto
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj OifUserOpenIntentOrderDtoOpenIntentTx) GetActualInstanceValue() interface{} {
	if obj.OpenIntentEvmTxDto != nil {
		return *obj.OpenIntentEvmTxDto
	}

	if obj.OpenIntentSvmTxDto != nil {
		return *obj.OpenIntentSvmTxDto
	}

	if obj.OpenIntentTronTxDto != nil {
		return *obj.OpenIntentTronTxDto
	}

	// all schemas are nil
	return nil
}

type NullableOifUserOpenIntentOrderDtoOpenIntentTx struct {
	value *OifUserOpenIntentOrderDtoOpenIntentTx
	isSet bool
}

func (v NullableOifUserOpenIntentOrderDtoOpenIntentTx) Get() *OifUserOpenIntentOrderDtoOpenIntentTx {
	return v.value
}

func (v *NullableOifUserOpenIntentOrderDtoOpenIntentTx) Set(val *OifUserOpenIntentOrderDtoOpenIntentTx) {
	v.value = val
	v.isSet = true
}

func (v NullableOifUserOpenIntentOrderDtoOpenIntentTx) IsSet() bool {
	return v.isSet
}

func (v *NullableOifUserOpenIntentOrderDtoOpenIntentTx) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOifUserOpenIntentOrderDtoOpenIntentTx(val *OifUserOpenIntentOrderDtoOpenIntentTx) *NullableOifUserOpenIntentOrderDtoOpenIntentTx {
	return &NullableOifUserOpenIntentOrderDtoOpenIntentTx{value: val, isSet: true}
}

func (v NullableOifUserOpenIntentOrderDtoOpenIntentTx) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOifUserOpenIntentOrderDtoOpenIntentTx) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
