/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.20
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
)

// checks if the OutputDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputDto{}

// OutputDto struct for OutputDto
type OutputDto struct {
	// CAIP-2 chain identifier for this output (e.g., \"eip155:1\"). Applies to both receiver and asset.
	Chain string `json:"chain"`
	// Native address that will receive the output assets
	Receiver string `json:"receiver"`
	// Native address of the token/asset to be received as output. For the chain's native token pass the chain-native sentinel: the zero address \"0x0000000000000000000000000000000000000000\" for ETH/TRX on EVM/Tron destinations, or the zero pubkey \"11111111111111111111111111111111\" for native SOL on Solana destinations. Wrapped SOL (So11111111111111111111111111111111111111112) is a distinct SPL asset, not interchangeable with native SOL.
	Asset string `json:"asset"`
	// For exact-input: ignored by the quote decoder and not used for quoting. For exact-output: exact amount user wants to receive and is used for quoting
	Amount NullableString `json:"amount,omitempty"`
	// Optional calldata describing how the receiver will consume the output. Enables composability with other protocols
	Calldata             *string `json:"calldata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OutputDto OutputDto

// NewOutputDto instantiates a new OutputDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputDto(chain string, receiver string, asset string) *OutputDto {
	this := OutputDto{}
	this.Chain = chain
	this.Receiver = receiver
	this.Asset = asset
	return &this
}

// NewOutputDtoWithDefaults instantiates a new OutputDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputDtoWithDefaults() *OutputDto {
	this := OutputDto{}
	return &this
}

// GetChain returns the Chain field value
func (o *OutputDto) GetChain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *OutputDto) GetChainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *OutputDto) SetChain(v string) {
	o.Chain = v
}

// GetReceiver returns the Receiver field value
func (o *OutputDto) GetReceiver() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Receiver
}

// GetReceiverOk returns a tuple with the Receiver field value
// and a boolean to check if the value has been set.
func (o *OutputDto) GetReceiverOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Receiver, true
}

// SetReceiver sets field value
func (o *OutputDto) SetReceiver(v string) {
	o.Receiver = v
}

// GetAsset returns the Asset field value
func (o *OutputDto) GetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *OutputDto) GetAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *OutputDto) SetAsset(v string) {
	o.Asset = v
}

// GetAmount returns the Amount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OutputDto) GetAmount() string {
	if o == nil || IsNil(o.Amount.Get()) {
		var ret string
		return ret
	}
	return *o.Amount.Get()
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OutputDto) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Amount.Get(), o.Amount.IsSet()
}

// HasAmount returns a boolean if a field has been set.
func (o *OutputDto) HasAmount() bool {
	if o != nil && o.Amount.IsSet() {
		return true
	}

	return false
}

// SetAmount gets a reference to the given NullableString and assigns it to the Amount field.
func (o *OutputDto) SetAmount(v string) {
	o.Amount.Set(&v)
}

// SetAmountNil sets the value for Amount to be an explicit nil
func (o *OutputDto) SetAmountNil() {
	o.Amount.Set(nil)
}

// UnsetAmount ensures that no value is present for Amount, not even an explicit nil
func (o *OutputDto) UnsetAmount() {
	o.Amount.Unset()
}

// GetCalldata returns the Calldata field value if set, zero value otherwise.
func (o *OutputDto) GetCalldata() string {
	if o == nil || IsNil(o.Calldata) {
		var ret string
		return ret
	}
	return *o.Calldata
}

// GetCalldataOk returns a tuple with the Calldata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputDto) GetCalldataOk() (*string, bool) {
	if o == nil || IsNil(o.Calldata) {
		return nil, false
	}
	return o.Calldata, true
}

// HasCalldata returns a boolean if a field has been set.
func (o *OutputDto) HasCalldata() bool {
	if o != nil && !IsNil(o.Calldata) {
		return true
	}

	return false
}

// SetCalldata gets a reference to the given string and assigns it to the Calldata field.
func (o *OutputDto) SetCalldata(v string) {
	o.Calldata = &v
}

func (o OutputDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chain"] = o.Chain
	toSerialize["receiver"] = o.Receiver
	toSerialize["asset"] = o.Asset
	if o.Amount.IsSet() {
		toSerialize["amount"] = o.Amount.Get()
	}
	if !IsNil(o.Calldata) {
		toSerialize["calldata"] = o.Calldata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OutputDto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varOutputDto := _OutputDto{}

	err = json.Unmarshal(data, &varOutputDto)

	if err != nil {
		return err
	}

	*o = OutputDto(varOutputDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "chain")
		delete(additionalProperties, "receiver")
		delete(additionalProperties, "asset")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "calldata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOutputDto struct {
	value *OutputDto
	isSet bool
}

func (v NullableOutputDto) Get() *OutputDto {
	return v.value
}

func (v *NullableOutputDto) Set(val *OutputDto) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputDto) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputDto(val *OutputDto) *NullableOutputDto {
	return &NullableOutputDto{value: val, isSet: true}
}

func (v NullableOutputDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
