/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
)

// checks if the SupportedContractsResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SupportedContractsResponseDto{}

// SupportedContractsResponseDto struct for SupportedContractsResponseDto
type SupportedContractsResponseDto struct {
	Data                 ContractsByKindDto `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _SupportedContractsResponseDto SupportedContractsResponseDto

// NewSupportedContractsResponseDto instantiates a new SupportedContractsResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupportedContractsResponseDto(data ContractsByKindDto) *SupportedContractsResponseDto {
	this := SupportedContractsResponseDto{}
	this.Data = data
	return &this
}

// NewSupportedContractsResponseDtoWithDefaults instantiates a new SupportedContractsResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupportedContractsResponseDtoWithDefaults() *SupportedContractsResponseDto {
	this := SupportedContractsResponseDto{}
	return &this
}

// GetData returns the Data field value
func (o *SupportedContractsResponseDto) GetData() ContractsByKindDto {
	if o == nil {
		var ret ContractsByKindDto
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SupportedContractsResponseDto) GetDataOk() (*ContractsByKindDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SupportedContractsResponseDto) SetData(v ContractsByKindDto) {
	o.Data = v
}

func (o SupportedContractsResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SupportedContractsResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SupportedContractsResponseDto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varSupportedContractsResponseDto := _SupportedContractsResponseDto{}

	err = json.Unmarshal(data, &varSupportedContractsResponseDto)

	if err != nil {
		return err
	}

	*o = SupportedContractsResponseDto(varSupportedContractsResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSupportedContractsResponseDto struct {
	value *SupportedContractsResponseDto
	isSet bool
}

func (v NullableSupportedContractsResponseDto) Get() *SupportedContractsResponseDto {
	return v.value
}

func (v *NullableSupportedContractsResponseDto) Set(val *SupportedContractsResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportedContractsResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportedContractsResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportedContractsResponseDto(val *SupportedContractsResponseDto) *NullableSupportedContractsResponseDto {
	return &NullableSupportedContractsResponseDto{value: val, isSet: true}
}

func (v NullableSupportedContractsResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportedContractsResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
