/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
)

// checks if the SupportedChainDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SupportedChainDto{}

// SupportedChainDto struct for SupportedChainDto
type SupportedChainDto struct {
	// Unique identifier for the chain
	Id float32 `json:"id"`
	// Chain ID as a string
	ChainId string `json:"chainId"`
	// Human-readable name of the chain
	Name string `json:"name"`
	// Type of blockchain (EVM, SVM, TVM)
	ChainType            string `json:"chainType"`
	AdditionalProperties map[string]interface{}
}

type _SupportedChainDto SupportedChainDto

// NewSupportedChainDto instantiates a new SupportedChainDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupportedChainDto(id float32, chainId string, name string, chainType string) *SupportedChainDto {
	this := SupportedChainDto{}
	this.Id = id
	this.ChainId = chainId
	this.Name = name
	this.ChainType = chainType
	return &this
}

// NewSupportedChainDtoWithDefaults instantiates a new SupportedChainDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupportedChainDtoWithDefaults() *SupportedChainDto {
	this := SupportedChainDto{}
	return &this
}

// GetId returns the Id field value
func (o *SupportedChainDto) GetId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SupportedChainDto) GetIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SupportedChainDto) SetId(v float32) {
	o.Id = v
}

// GetChainId returns the ChainId field value
func (o *SupportedChainDto) GetChainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *SupportedChainDto) GetChainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *SupportedChainDto) SetChainId(v string) {
	o.ChainId = v
}

// GetName returns the Name field value
func (o *SupportedChainDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SupportedChainDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SupportedChainDto) SetName(v string) {
	o.Name = v
}

// GetChainType returns the ChainType field value
func (o *SupportedChainDto) GetChainType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChainType
}

// GetChainTypeOk returns a tuple with the ChainType field value
// and a boolean to check if the value has been set.
func (o *SupportedChainDto) GetChainTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainType, true
}

// SetChainType sets field value
func (o *SupportedChainDto) SetChainType(v string) {
	o.ChainType = v
}

func (o SupportedChainDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SupportedChainDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["chainId"] = o.ChainId
	toSerialize["name"] = o.Name
	toSerialize["chainType"] = o.ChainType

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SupportedChainDto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varSupportedChainDto := _SupportedChainDto{}

	err = json.Unmarshal(data, &varSupportedChainDto)

	if err != nil {
		return err
	}

	*o = SupportedChainDto(varSupportedChainDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "chainId")
		delete(additionalProperties, "name")
		delete(additionalProperties, "chainType")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSupportedChainDto struct {
	value *SupportedChainDto
	isSet bool
}

func (v NullableSupportedChainDto) Get() *SupportedChainDto {
	return v.value
}

func (v *NullableSupportedChainDto) Set(val *SupportedChainDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportedChainDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportedChainDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportedChainDto(val *SupportedChainDto) *NullableSupportedChainDto {
	return &NullableSupportedChainDto{value: val, isSet: true}
}

func (v NullableSupportedChainDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportedChainDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
