/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
)

// checks if the InputDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputDto{}

// InputDto struct for InputDto
type InputDto struct {
	// CAIP-2 chain identifier for this input (e.g., \"eip155:1\"). Applies to both user and asset.
	Chain string `json:"chain"`
	// Native address of the user providing the input assets
	User string `json:"user"`
	// Native address of the token/asset being provided as input
	Asset string `json:"asset"`
	// Amount available. For exact-input: exact amount user will provide and is used for quoting. For exact-output: ignored by the quote decoder and not used for quoting
	Amount NullableString `json:"amount,omitempty"`
	// Optional lock reference for securing the input assets. Shape: { kind: \"the-compact\" | \"rhinestone\", params: object }. Currently ignored by the quote decoder.
	Lock                 map[string]interface{} `json:"lock,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InputDto InputDto

// NewInputDto instantiates a new InputDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputDto(chain string, user string, asset string) *InputDto {
	this := InputDto{}
	this.Chain = chain
	this.User = user
	this.Asset = asset
	return &this
}

// NewInputDtoWithDefaults instantiates a new InputDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputDtoWithDefaults() *InputDto {
	this := InputDto{}
	return &this
}

// GetChain returns the Chain field value
func (o *InputDto) GetChain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *InputDto) GetChainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *InputDto) SetChain(v string) {
	o.Chain = v
}

// GetUser returns the User field value
func (o *InputDto) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *InputDto) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *InputDto) SetUser(v string) {
	o.User = v
}

// GetAsset returns the Asset field value
func (o *InputDto) GetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *InputDto) GetAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *InputDto) SetAsset(v string) {
	o.Asset = v
}

// GetAmount returns the Amount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InputDto) GetAmount() string {
	if o == nil || IsNil(o.Amount.Get()) {
		var ret string
		return ret
	}
	return *o.Amount.Get()
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InputDto) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Amount.Get(), o.Amount.IsSet()
}

// HasAmount returns a boolean if a field has been set.
func (o *InputDto) HasAmount() bool {
	if o != nil && o.Amount.IsSet() {
		return true
	}

	return false
}

// SetAmount gets a reference to the given NullableString and assigns it to the Amount field.
func (o *InputDto) SetAmount(v string) {
	o.Amount.Set(&v)
}

// SetAmountNil sets the value for Amount to be an explicit nil
func (o *InputDto) SetAmountNil() {
	o.Amount.Set(nil)
}

// UnsetAmount ensures that no value is present for Amount, not even an explicit nil
func (o *InputDto) UnsetAmount() {
	o.Amount.Unset()
}

// GetLock returns the Lock field value if set, zero value otherwise.
func (o *InputDto) GetLock() map[string]interface{} {
	if o == nil || IsNil(o.Lock) {
		var ret map[string]interface{}
		return ret
	}
	return o.Lock
}

// GetLockOk returns a tuple with the Lock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputDto) GetLockOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Lock) {
		return map[string]interface{}{}, false
	}
	return o.Lock, true
}

// HasLock returns a boolean if a field has been set.
func (o *InputDto) HasLock() bool {
	if o != nil && !IsNil(o.Lock) {
		return true
	}

	return false
}

// SetLock gets a reference to the given map[string]interface{} and assigns it to the Lock field.
func (o *InputDto) SetLock(v map[string]interface{}) {
	o.Lock = v
}

func (o InputDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chain"] = o.Chain
	toSerialize["user"] = o.User
	toSerialize["asset"] = o.Asset
	if o.Amount.IsSet() {
		toSerialize["amount"] = o.Amount.Get()
	}
	if !IsNil(o.Lock) {
		toSerialize["lock"] = o.Lock
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InputDto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varInputDto := _InputDto{}

	err = json.Unmarshal(data, &varInputDto)

	if err != nil {
		return err
	}

	*o = InputDto(varInputDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "chain")
		delete(additionalProperties, "user")
		delete(additionalProperties, "asset")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "lock")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInputDto struct {
	value *InputDto
	isSet bool
}

func (v NullableInputDto) Get() *InputDto {
	return v.value
}

func (v *NullableInputDto) Set(val *InputDto) {
	v.value = val
	v.isSet = true
}

func (v NullableInputDto) IsSet() bool {
	return v.isSet
}

func (v *NullableInputDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputDto(val *InputDto) *NullableInputDto {
	return &NullableInputDto{value: val, isSet: true}
}

func (v NullableInputDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
