/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OpenIntentEvmTxDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenIntentEvmTxDto{}

// OpenIntentEvmTxDto struct for OpenIntentEvmTxDto
type OpenIntentEvmTxDto struct {
	// CAIP-2 chain identifier for the destination contract
	Chain string `json:"chain"`
	// Destination contract address (checksummed hex)
	To string `json:"to"`
	// Transaction calldata as hex string
	Data string `json:"data"`
	// Gas required for execution as a decimal string
	GasRequired string `json:"gasRequired"`
}

type _OpenIntentEvmTxDto OpenIntentEvmTxDto

// NewOpenIntentEvmTxDto instantiates a new OpenIntentEvmTxDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenIntentEvmTxDto(chain string, to string, data string, gasRequired string) *OpenIntentEvmTxDto {
	this := OpenIntentEvmTxDto{}
	this.Chain = chain
	this.To = to
	this.Data = data
	this.GasRequired = gasRequired
	return &this
}

// NewOpenIntentEvmTxDtoWithDefaults instantiates a new OpenIntentEvmTxDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenIntentEvmTxDtoWithDefaults() *OpenIntentEvmTxDto {
	this := OpenIntentEvmTxDto{}
	return &this
}

// GetChain returns the Chain field value
func (o *OpenIntentEvmTxDto) GetChain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *OpenIntentEvmTxDto) GetChainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *OpenIntentEvmTxDto) SetChain(v string) {
	o.Chain = v
}

// GetTo returns the To field value
func (o *OpenIntentEvmTxDto) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *OpenIntentEvmTxDto) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *OpenIntentEvmTxDto) SetTo(v string) {
	o.To = v
}

// GetData returns the Data field value
func (o *OpenIntentEvmTxDto) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *OpenIntentEvmTxDto) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *OpenIntentEvmTxDto) SetData(v string) {
	o.Data = v
}

// GetGasRequired returns the GasRequired field value
func (o *OpenIntentEvmTxDto) GetGasRequired() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GasRequired
}

// GetGasRequiredOk returns a tuple with the GasRequired field value
// and a boolean to check if the value has been set.
func (o *OpenIntentEvmTxDto) GetGasRequiredOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GasRequired, true
}

// SetGasRequired sets field value
func (o *OpenIntentEvmTxDto) SetGasRequired(v string) {
	o.GasRequired = v
}

func (o OpenIntentEvmTxDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenIntentEvmTxDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chain"] = o.Chain
	toSerialize["to"] = o.To
	toSerialize["data"] = o.Data
	toSerialize["gasRequired"] = o.GasRequired
	return toSerialize, nil
}

func (o *OpenIntentEvmTxDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"chain",
		"to",
		"data",
		"gasRequired",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenIntentEvmTxDto := _OpenIntentEvmTxDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenIntentEvmTxDto)

	if err != nil {
		return err
	}

	*o = OpenIntentEvmTxDto(varOpenIntentEvmTxDto)

	return err
}

type NullableOpenIntentEvmTxDto struct {
	value *OpenIntentEvmTxDto
	isSet bool
}

func (v NullableOpenIntentEvmTxDto) Get() *OpenIntentEvmTxDto {
	return v.value
}

func (v *NullableOpenIntentEvmTxDto) Set(val *OpenIntentEvmTxDto) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenIntentEvmTxDto) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenIntentEvmTxDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenIntentEvmTxDto(val *OpenIntentEvmTxDto) *NullableOpenIntentEvmTxDto {
	return &NullableOpenIntentEvmTxDto{value: val, isSet: true}
}

func (v NullableOpenIntentEvmTxDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenIntentEvmTxDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
