/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.20
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
)

// checks if the GetSupportedRoutesResponseV1Dto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSupportedRoutesResponseV1Dto{}

// GetSupportedRoutesResponseV1Dto struct for GetSupportedRoutesResponseV1Dto
type GetSupportedRoutesResponseV1Dto struct {
	// Array of supported routes
	Routes               []SupportedRouteV1Dto `json:"routes"`
	AdditionalProperties map[string]interface{}
}

type _GetSupportedRoutesResponseV1Dto GetSupportedRoutesResponseV1Dto

// NewGetSupportedRoutesResponseV1Dto instantiates a new GetSupportedRoutesResponseV1Dto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSupportedRoutesResponseV1Dto(routes []SupportedRouteV1Dto) *GetSupportedRoutesResponseV1Dto {
	this := GetSupportedRoutesResponseV1Dto{}
	this.Routes = routes
	return &this
}

// NewGetSupportedRoutesResponseV1DtoWithDefaults instantiates a new GetSupportedRoutesResponseV1Dto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSupportedRoutesResponseV1DtoWithDefaults() *GetSupportedRoutesResponseV1Dto {
	this := GetSupportedRoutesResponseV1Dto{}
	return &this
}

// GetRoutes returns the Routes field value
func (o *GetSupportedRoutesResponseV1Dto) GetRoutes() []SupportedRouteV1Dto {
	if o == nil {
		var ret []SupportedRouteV1Dto
		return ret
	}

	return o.Routes
}

// GetRoutesOk returns a tuple with the Routes field value
// and a boolean to check if the value has been set.
func (o *GetSupportedRoutesResponseV1Dto) GetRoutesOk() ([]SupportedRouteV1Dto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Routes, true
}

// SetRoutes sets field value
func (o *GetSupportedRoutesResponseV1Dto) SetRoutes(v []SupportedRouteV1Dto) {
	o.Routes = v
}

func (o GetSupportedRoutesResponseV1Dto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSupportedRoutesResponseV1Dto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["routes"] = o.Routes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetSupportedRoutesResponseV1Dto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varGetSupportedRoutesResponseV1Dto := _GetSupportedRoutesResponseV1Dto{}

	err = json.Unmarshal(data, &varGetSupportedRoutesResponseV1Dto)

	if err != nil {
		return err
	}

	*o = GetSupportedRoutesResponseV1Dto(varGetSupportedRoutesResponseV1Dto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "routes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetSupportedRoutesResponseV1Dto struct {
	value *GetSupportedRoutesResponseV1Dto
	isSet bool
}

func (v NullableGetSupportedRoutesResponseV1Dto) Get() *GetSupportedRoutesResponseV1Dto {
	return v.value
}

func (v *NullableGetSupportedRoutesResponseV1Dto) Set(val *GetSupportedRoutesResponseV1Dto) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSupportedRoutesResponseV1Dto) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSupportedRoutesResponseV1Dto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSupportedRoutesResponseV1Dto(val *GetSupportedRoutesResponseV1Dto) *NullableGetSupportedRoutesResponseV1Dto {
	return &NullableGetSupportedRoutesResponseV1Dto{value: val, isSet: true}
}

func (v NullableGetSupportedRoutesResponseV1Dto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSupportedRoutesResponseV1Dto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
