/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.20
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"encoding/json"
)

// checks if the UnregisterAccountV1Dto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnregisterAccountV1Dto{}

// UnregisterAccountV1Dto struct for UnregisterAccountV1Dto
type UnregisterAccountV1Dto struct {
	// Account address. EVM: hex20 EOA or hex32 bytes32 (last 20 bytes are extracted). Solana: base58 ed25519 public key. Tron: T-prefixed base58check or 0x hex.
	Account string `json:"account"`
	// CAIP-2 chain identifier. Selects how the account is parsed; accounts are keyed by address alone.
	Chain                string `json:"chain"`
	AdditionalProperties map[string]interface{}
}

type _UnregisterAccountV1Dto UnregisterAccountV1Dto

// NewUnregisterAccountV1Dto instantiates a new UnregisterAccountV1Dto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnregisterAccountV1Dto(account string, chain string) *UnregisterAccountV1Dto {
	this := UnregisterAccountV1Dto{}
	this.Account = account
	this.Chain = chain
	return &this
}

// NewUnregisterAccountV1DtoWithDefaults instantiates a new UnregisterAccountV1Dto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnregisterAccountV1DtoWithDefaults() *UnregisterAccountV1Dto {
	this := UnregisterAccountV1Dto{}
	return &this
}

// GetAccount returns the Account field value
func (o *UnregisterAccountV1Dto) GetAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *UnregisterAccountV1Dto) GetAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *UnregisterAccountV1Dto) SetAccount(v string) {
	o.Account = v
}

// GetChain returns the Chain field value
func (o *UnregisterAccountV1Dto) GetChain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *UnregisterAccountV1Dto) GetChainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *UnregisterAccountV1Dto) SetChain(v string) {
	o.Chain = v
}

func (o UnregisterAccountV1Dto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnregisterAccountV1Dto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account"] = o.Account
	toSerialize["chain"] = o.Chain

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UnregisterAccountV1Dto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varUnregisterAccountV1Dto := _UnregisterAccountV1Dto{}

	err = json.Unmarshal(data, &varUnregisterAccountV1Dto)

	if err != nil {
		return err
	}

	*o = UnregisterAccountV1Dto(varUnregisterAccountV1Dto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account")
		delete(additionalProperties, "chain")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUnregisterAccountV1Dto struct {
	value *UnregisterAccountV1Dto
	isSet bool
}

func (v NullableUnregisterAccountV1Dto) Get() *UnregisterAccountV1Dto {
	return v.value
}

func (v *NullableUnregisterAccountV1Dto) Set(val *UnregisterAccountV1Dto) {
	v.value = val
	v.isSet = true
}

func (v NullableUnregisterAccountV1Dto) IsSet() bool {
	return v.isSet
}

func (v *NullableUnregisterAccountV1Dto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnregisterAccountV1Dto(val *UnregisterAccountV1Dto) *NullableUnregisterAccountV1Dto {
	return &NullableUnregisterAccountV1Dto{value: val, isSet: true}
}

func (v NullableUnregisterAccountV1Dto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnregisterAccountV1Dto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
