/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SolverQuoteDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SolverQuoteDto{}

// SolverQuoteDto struct for SolverQuoteDto
type SolverQuoteDto struct {
	// Unique identifier for the solver quote
	Id string `json:"id"`
	// Creation timestamp
	CreatedAt string `json:"createdAt"`
	// Last update timestamp
	UpdatedAt string `json:"updatedAt"`
	// Source chain network ID
	FromChainNetworkId string `json:"fromChainNetworkId"`
	// Destination chain network ID
	ToChainNetworkId string `json:"toChainNetworkId"`
	// Source asset address
	FromAssetAddress string `json:"fromAssetAddress"`
	// Destination asset address
	ToAssetAddress string `json:"toAssetAddress"`
	// Source asset decimals
	FromAssetDecimals float32 `json:"fromAssetDecimals"`
	// Destination asset decimals
	ToAssetDecimals float32 `json:"toAssetDecimals"`
	// Source decimals (legacy field)
	FromDecimals float32 `json:"fromDecimals"`
	// Destination decimals (legacy field)
	ToDecimals float32 `json:"toDecimals"`
	// Quote expiry timestamp
	Expiry string `json:"expiry"`
	// Quote rate for this range
	Quote string `json:"quote"`
	// Minimum amount for this quote range
	MinAmount string `json:"minAmount"`
	// Maximum amount for this quote range
	MaxAmount string `json:"maxAmount"`
	// Exclusive for address
	ExclusiveFor map[string]interface{} `json:"exclusiveFor"`
	// Source asset record ID
	FromAssetRecordId map[string]interface{} `json:"fromAssetRecordId"`
	// Destination asset record ID
	ToAssetRecordId map[string]interface{} `json:"toAssetRecordId"`
	// Source chain record ID
	FromChainRecordId map[string]interface{} `json:"fromChainRecordId"`
	// Destination chain record ID
	ToChainRecordId map[string]interface{} `json:"toChainRecordId"`
	// Associated solver ID
	SolverId float32 `json:"solverId"`
	// Integrator key hash this quote is tagged for, or null for open-market quotes
	IntegratorKeyHash map[string]interface{} `json:"integratorKeyHash,omitempty"`
}

type _SolverQuoteDto SolverQuoteDto

// NewSolverQuoteDto instantiates a new SolverQuoteDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSolverQuoteDto(id string, createdAt string, updatedAt string, fromChainNetworkId string, toChainNetworkId string, fromAssetAddress string, toAssetAddress string, fromAssetDecimals float32, toAssetDecimals float32, fromDecimals float32, toDecimals float32, expiry string, quote string, minAmount string, maxAmount string, exclusiveFor map[string]interface{}, fromAssetRecordId map[string]interface{}, toAssetRecordId map[string]interface{}, fromChainRecordId map[string]interface{}, toChainRecordId map[string]interface{}, solverId float32) *SolverQuoteDto {
	this := SolverQuoteDto{}
	this.Id = id
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.FromChainNetworkId = fromChainNetworkId
	this.ToChainNetworkId = toChainNetworkId
	this.FromAssetAddress = fromAssetAddress
	this.ToAssetAddress = toAssetAddress
	this.FromAssetDecimals = fromAssetDecimals
	this.ToAssetDecimals = toAssetDecimals
	this.FromDecimals = fromDecimals
	this.ToDecimals = toDecimals
	this.Expiry = expiry
	this.Quote = quote
	this.MinAmount = minAmount
	this.MaxAmount = maxAmount
	this.ExclusiveFor = exclusiveFor
	this.FromAssetRecordId = fromAssetRecordId
	this.ToAssetRecordId = toAssetRecordId
	this.FromChainRecordId = fromChainRecordId
	this.ToChainRecordId = toChainRecordId
	this.SolverId = solverId
	return &this
}

// NewSolverQuoteDtoWithDefaults instantiates a new SolverQuoteDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSolverQuoteDtoWithDefaults() *SolverQuoteDto {
	this := SolverQuoteDto{}
	return &this
}

// GetId returns the Id field value
func (o *SolverQuoteDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SolverQuoteDto) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SolverQuoteDto) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SolverQuoteDto) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *SolverQuoteDto) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *SolverQuoteDto) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetFromChainNetworkId returns the FromChainNetworkId field value
func (o *SolverQuoteDto) GetFromChainNetworkId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromChainNetworkId
}

// GetFromChainNetworkIdOk returns a tuple with the FromChainNetworkId field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetFromChainNetworkIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromChainNetworkId, true
}

// SetFromChainNetworkId sets field value
func (o *SolverQuoteDto) SetFromChainNetworkId(v string) {
	o.FromChainNetworkId = v
}

// GetToChainNetworkId returns the ToChainNetworkId field value
func (o *SolverQuoteDto) GetToChainNetworkId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToChainNetworkId
}

// GetToChainNetworkIdOk returns a tuple with the ToChainNetworkId field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetToChainNetworkIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToChainNetworkId, true
}

// SetToChainNetworkId sets field value
func (o *SolverQuoteDto) SetToChainNetworkId(v string) {
	o.ToChainNetworkId = v
}

// GetFromAssetAddress returns the FromAssetAddress field value
func (o *SolverQuoteDto) GetFromAssetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromAssetAddress
}

// GetFromAssetAddressOk returns a tuple with the FromAssetAddress field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetFromAssetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromAssetAddress, true
}

// SetFromAssetAddress sets field value
func (o *SolverQuoteDto) SetFromAssetAddress(v string) {
	o.FromAssetAddress = v
}

// GetToAssetAddress returns the ToAssetAddress field value
func (o *SolverQuoteDto) GetToAssetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToAssetAddress
}

// GetToAssetAddressOk returns a tuple with the ToAssetAddress field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetToAssetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToAssetAddress, true
}

// SetToAssetAddress sets field value
func (o *SolverQuoteDto) SetToAssetAddress(v string) {
	o.ToAssetAddress = v
}

// GetFromAssetDecimals returns the FromAssetDecimals field value
func (o *SolverQuoteDto) GetFromAssetDecimals() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FromAssetDecimals
}

// GetFromAssetDecimalsOk returns a tuple with the FromAssetDecimals field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetFromAssetDecimalsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromAssetDecimals, true
}

// SetFromAssetDecimals sets field value
func (o *SolverQuoteDto) SetFromAssetDecimals(v float32) {
	o.FromAssetDecimals = v
}

// GetToAssetDecimals returns the ToAssetDecimals field value
func (o *SolverQuoteDto) GetToAssetDecimals() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ToAssetDecimals
}

// GetToAssetDecimalsOk returns a tuple with the ToAssetDecimals field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetToAssetDecimalsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToAssetDecimals, true
}

// SetToAssetDecimals sets field value
func (o *SolverQuoteDto) SetToAssetDecimals(v float32) {
	o.ToAssetDecimals = v
}

// GetFromDecimals returns the FromDecimals field value
func (o *SolverQuoteDto) GetFromDecimals() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.FromDecimals
}

// GetFromDecimalsOk returns a tuple with the FromDecimals field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetFromDecimalsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromDecimals, true
}

// SetFromDecimals sets field value
func (o *SolverQuoteDto) SetFromDecimals(v float32) {
	o.FromDecimals = v
}

// GetToDecimals returns the ToDecimals field value
func (o *SolverQuoteDto) GetToDecimals() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ToDecimals
}

// GetToDecimalsOk returns a tuple with the ToDecimals field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetToDecimalsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToDecimals, true
}

// SetToDecimals sets field value
func (o *SolverQuoteDto) SetToDecimals(v float32) {
	o.ToDecimals = v
}

// GetExpiry returns the Expiry field value
func (o *SolverQuoteDto) GetExpiry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Expiry
}

// GetExpiryOk returns a tuple with the Expiry field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetExpiryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expiry, true
}

// SetExpiry sets field value
func (o *SolverQuoteDto) SetExpiry(v string) {
	o.Expiry = v
}

// GetQuote returns the Quote field value
func (o *SolverQuoteDto) GetQuote() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Quote
}

// GetQuoteOk returns a tuple with the Quote field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetQuoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quote, true
}

// SetQuote sets field value
func (o *SolverQuoteDto) SetQuote(v string) {
	o.Quote = v
}

// GetMinAmount returns the MinAmount field value
func (o *SolverQuoteDto) GetMinAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MinAmount
}

// GetMinAmountOk returns a tuple with the MinAmount field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetMinAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinAmount, true
}

// SetMinAmount sets field value
func (o *SolverQuoteDto) SetMinAmount(v string) {
	o.MinAmount = v
}

// GetMaxAmount returns the MaxAmount field value
func (o *SolverQuoteDto) GetMaxAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MaxAmount
}

// GetMaxAmountOk returns a tuple with the MaxAmount field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetMaxAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxAmount, true
}

// SetMaxAmount sets field value
func (o *SolverQuoteDto) SetMaxAmount(v string) {
	o.MaxAmount = v
}

// GetExclusiveFor returns the ExclusiveFor field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *SolverQuoteDto) GetExclusiveFor() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ExclusiveFor
}

// GetExclusiveForOk returns a tuple with the ExclusiveFor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SolverQuoteDto) GetExclusiveForOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ExclusiveFor) {
		return map[string]interface{}{}, false
	}
	return o.ExclusiveFor, true
}

// SetExclusiveFor sets field value
func (o *SolverQuoteDto) SetExclusiveFor(v map[string]interface{}) {
	o.ExclusiveFor = v
}

// GetFromAssetRecordId returns the FromAssetRecordId field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *SolverQuoteDto) GetFromAssetRecordId() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.FromAssetRecordId
}

// GetFromAssetRecordIdOk returns a tuple with the FromAssetRecordId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SolverQuoteDto) GetFromAssetRecordIdOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FromAssetRecordId) {
		return map[string]interface{}{}, false
	}
	return o.FromAssetRecordId, true
}

// SetFromAssetRecordId sets field value
func (o *SolverQuoteDto) SetFromAssetRecordId(v map[string]interface{}) {
	o.FromAssetRecordId = v
}

// GetToAssetRecordId returns the ToAssetRecordId field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *SolverQuoteDto) GetToAssetRecordId() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ToAssetRecordId
}

// GetToAssetRecordIdOk returns a tuple with the ToAssetRecordId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SolverQuoteDto) GetToAssetRecordIdOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ToAssetRecordId) {
		return map[string]interface{}{}, false
	}
	return o.ToAssetRecordId, true
}

// SetToAssetRecordId sets field value
func (o *SolverQuoteDto) SetToAssetRecordId(v map[string]interface{}) {
	o.ToAssetRecordId = v
}

// GetFromChainRecordId returns the FromChainRecordId field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *SolverQuoteDto) GetFromChainRecordId() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.FromChainRecordId
}

// GetFromChainRecordIdOk returns a tuple with the FromChainRecordId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SolverQuoteDto) GetFromChainRecordIdOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FromChainRecordId) {
		return map[string]interface{}{}, false
	}
	return o.FromChainRecordId, true
}

// SetFromChainRecordId sets field value
func (o *SolverQuoteDto) SetFromChainRecordId(v map[string]interface{}) {
	o.FromChainRecordId = v
}

// GetToChainRecordId returns the ToChainRecordId field value
// If the value is explicit nil, the zero value for map[string]interface{} will be returned
func (o *SolverQuoteDto) GetToChainRecordId() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.ToChainRecordId
}

// GetToChainRecordIdOk returns a tuple with the ToChainRecordId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SolverQuoteDto) GetToChainRecordIdOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ToChainRecordId) {
		return map[string]interface{}{}, false
	}
	return o.ToChainRecordId, true
}

// SetToChainRecordId sets field value
func (o *SolverQuoteDto) SetToChainRecordId(v map[string]interface{}) {
	o.ToChainRecordId = v
}

// GetSolverId returns the SolverId field value
func (o *SolverQuoteDto) GetSolverId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SolverId
}

// GetSolverIdOk returns a tuple with the SolverId field value
// and a boolean to check if the value has been set.
func (o *SolverQuoteDto) GetSolverIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SolverId, true
}

// SetSolverId sets field value
func (o *SolverQuoteDto) SetSolverId(v float32) {
	o.SolverId = v
}

// GetIntegratorKeyHash returns the IntegratorKeyHash field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SolverQuoteDto) GetIntegratorKeyHash() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.IntegratorKeyHash
}

// GetIntegratorKeyHashOk returns a tuple with the IntegratorKeyHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SolverQuoteDto) GetIntegratorKeyHashOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.IntegratorKeyHash) {
		return map[string]interface{}{}, false
	}
	return o.IntegratorKeyHash, true
}

// HasIntegratorKeyHash returns a boolean if a field has been set.
func (o *SolverQuoteDto) HasIntegratorKeyHash() bool {
	if o != nil && !IsNil(o.IntegratorKeyHash) {
		return true
	}

	return false
}

// SetIntegratorKeyHash gets a reference to the given map[string]interface{} and assigns it to the IntegratorKeyHash field.
func (o *SolverQuoteDto) SetIntegratorKeyHash(v map[string]interface{}) {
	o.IntegratorKeyHash = v
}

func (o SolverQuoteDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SolverQuoteDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["fromChainNetworkId"] = o.FromChainNetworkId
	toSerialize["toChainNetworkId"] = o.ToChainNetworkId
	toSerialize["fromAssetAddress"] = o.FromAssetAddress
	toSerialize["toAssetAddress"] = o.ToAssetAddress
	toSerialize["fromAssetDecimals"] = o.FromAssetDecimals
	toSerialize["toAssetDecimals"] = o.ToAssetDecimals
	toSerialize["fromDecimals"] = o.FromDecimals
	toSerialize["toDecimals"] = o.ToDecimals
	toSerialize["expiry"] = o.Expiry
	toSerialize["quote"] = o.Quote
	toSerialize["minAmount"] = o.MinAmount
	toSerialize["maxAmount"] = o.MaxAmount
	if o.ExclusiveFor != nil {
		toSerialize["exclusiveFor"] = o.ExclusiveFor
	}
	if o.FromAssetRecordId != nil {
		toSerialize["fromAssetRecordId"] = o.FromAssetRecordId
	}
	if o.ToAssetRecordId != nil {
		toSerialize["toAssetRecordId"] = o.ToAssetRecordId
	}
	if o.FromChainRecordId != nil {
		toSerialize["fromChainRecordId"] = o.FromChainRecordId
	}
	if o.ToChainRecordId != nil {
		toSerialize["toChainRecordId"] = o.ToChainRecordId
	}
	toSerialize["solverId"] = o.SolverId
	if o.IntegratorKeyHash != nil {
		toSerialize["integratorKeyHash"] = o.IntegratorKeyHash
	}
	return toSerialize, nil
}

func (o *SolverQuoteDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"createdAt",
		"updatedAt",
		"fromChainNetworkId",
		"toChainNetworkId",
		"fromAssetAddress",
		"toAssetAddress",
		"fromAssetDecimals",
		"toAssetDecimals",
		"fromDecimals",
		"toDecimals",
		"expiry",
		"quote",
		"minAmount",
		"maxAmount",
		"exclusiveFor",
		"fromAssetRecordId",
		"toAssetRecordId",
		"fromChainRecordId",
		"toChainRecordId",
		"solverId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSolverQuoteDto := _SolverQuoteDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSolverQuoteDto)

	if err != nil {
		return err
	}

	*o = SolverQuoteDto(varSolverQuoteDto)

	return err
}

type NullableSolverQuoteDto struct {
	value *SolverQuoteDto
	isSet bool
}

func (v NullableSolverQuoteDto) Get() *SolverQuoteDto {
	return v.value
}

func (v *NullableSolverQuoteDto) Set(val *SolverQuoteDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSolverQuoteDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSolverQuoteDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSolverQuoteDto(val *SolverQuoteDto) *NullableSolverQuoteDto {
	return &NullableSolverQuoteDto{value: val, isSet: true}
}

func (v NullableSolverQuoteDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSolverQuoteDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
