/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OifQuoteRequestDtoIntentInputsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OifQuoteRequestDtoIntentInputsInner{}

// OifQuoteRequestDtoIntentInputsInner struct for OifQuoteRequestDtoIntentInputsInner
type OifQuoteRequestDtoIntentInputsInner struct {
	// User address in EIP-7930 interoperable format
	User string `json:"user"`
	// Asset address in EIP-7930 interoperable format
	Asset string `json:"asset"`
	// Amount as string-encoded integer (optional for quote requests)
	Amount *string                                  `json:"amount,omitempty"`
	Lock   *OifQuoteRequestDtoIntentInputsInnerLock `json:"lock,omitempty"`
}

type _OifQuoteRequestDtoIntentInputsInner OifQuoteRequestDtoIntentInputsInner

// NewOifQuoteRequestDtoIntentInputsInner instantiates a new OifQuoteRequestDtoIntentInputsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOifQuoteRequestDtoIntentInputsInner(user string, asset string) *OifQuoteRequestDtoIntentInputsInner {
	this := OifQuoteRequestDtoIntentInputsInner{}
	this.User = user
	this.Asset = asset
	return &this
}

// NewOifQuoteRequestDtoIntentInputsInnerWithDefaults instantiates a new OifQuoteRequestDtoIntentInputsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOifQuoteRequestDtoIntentInputsInnerWithDefaults() *OifQuoteRequestDtoIntentInputsInner {
	this := OifQuoteRequestDtoIntentInputsInner{}
	return &this
}

// GetUser returns the User field value
func (o *OifQuoteRequestDtoIntentInputsInner) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *OifQuoteRequestDtoIntentInputsInner) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *OifQuoteRequestDtoIntentInputsInner) SetUser(v string) {
	o.User = v
}

// GetAsset returns the Asset field value
func (o *OifQuoteRequestDtoIntentInputsInner) GetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *OifQuoteRequestDtoIntentInputsInner) GetAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *OifQuoteRequestDtoIntentInputsInner) SetAsset(v string) {
	o.Asset = v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *OifQuoteRequestDtoIntentInputsInner) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OifQuoteRequestDtoIntentInputsInner) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *OifQuoteRequestDtoIntentInputsInner) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *OifQuoteRequestDtoIntentInputsInner) SetAmount(v string) {
	o.Amount = &v
}

// GetLock returns the Lock field value if set, zero value otherwise.
func (o *OifQuoteRequestDtoIntentInputsInner) GetLock() OifQuoteRequestDtoIntentInputsInnerLock {
	if o == nil || IsNil(o.Lock) {
		var ret OifQuoteRequestDtoIntentInputsInnerLock
		return ret
	}
	return *o.Lock
}

// GetLockOk returns a tuple with the Lock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OifQuoteRequestDtoIntentInputsInner) GetLockOk() (*OifQuoteRequestDtoIntentInputsInnerLock, bool) {
	if o == nil || IsNil(o.Lock) {
		return nil, false
	}
	return o.Lock, true
}

// HasLock returns a boolean if a field has been set.
func (o *OifQuoteRequestDtoIntentInputsInner) HasLock() bool {
	if o != nil && !IsNil(o.Lock) {
		return true
	}

	return false
}

// SetLock gets a reference to the given OifQuoteRequestDtoIntentInputsInnerLock and assigns it to the Lock field.
func (o *OifQuoteRequestDtoIntentInputsInner) SetLock(v OifQuoteRequestDtoIntentInputsInnerLock) {
	o.Lock = &v
}

func (o OifQuoteRequestDtoIntentInputsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OifQuoteRequestDtoIntentInputsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user"] = o.User
	toSerialize["asset"] = o.Asset
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Lock) {
		toSerialize["lock"] = o.Lock
	}
	return toSerialize, nil
}

func (o *OifQuoteRequestDtoIntentInputsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user",
		"asset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOifQuoteRequestDtoIntentInputsInner := _OifQuoteRequestDtoIntentInputsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOifQuoteRequestDtoIntentInputsInner)

	if err != nil {
		return err
	}

	*o = OifQuoteRequestDtoIntentInputsInner(varOifQuoteRequestDtoIntentInputsInner)

	return err
}

type NullableOifQuoteRequestDtoIntentInputsInner struct {
	value *OifQuoteRequestDtoIntentInputsInner
	isSet bool
}

func (v NullableOifQuoteRequestDtoIntentInputsInner) Get() *OifQuoteRequestDtoIntentInputsInner {
	return v.value
}

func (v *NullableOifQuoteRequestDtoIntentInputsInner) Set(val *OifQuoteRequestDtoIntentInputsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOifQuoteRequestDtoIntentInputsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOifQuoteRequestDtoIntentInputsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOifQuoteRequestDtoIntentInputsInner(val *OifQuoteRequestDtoIntentInputsInner) *NullableOifQuoteRequestDtoIntentInputsInner {
	return &NullableOifQuoteRequestDtoIntentInputsInner{value: val, isSet: true}
}

func (v NullableOifQuoteRequestDtoIntentInputsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOifQuoteRequestDtoIntentInputsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
