/*
Lifi Intents API Reference

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lifiorder

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ChainAddressDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChainAddressDto{}

// ChainAddressDto struct for ChainAddressDto
type ChainAddressDto struct {
	// CAIP-2 chain identifier
	Chain string `json:"chain"`
	// Native contract address for the chain
	Address string `json:"address"`
}

type _ChainAddressDto ChainAddressDto

// NewChainAddressDto instantiates a new ChainAddressDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChainAddressDto(chain string, address string) *ChainAddressDto {
	this := ChainAddressDto{}
	this.Chain = chain
	this.Address = address
	return &this
}

// NewChainAddressDtoWithDefaults instantiates a new ChainAddressDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChainAddressDtoWithDefaults() *ChainAddressDto {
	this := ChainAddressDto{}
	return &this
}

// GetChain returns the Chain field value
func (o *ChainAddressDto) GetChain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *ChainAddressDto) GetChainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *ChainAddressDto) SetChain(v string) {
	o.Chain = v
}

// GetAddress returns the Address field value
func (o *ChainAddressDto) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *ChainAddressDto) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *ChainAddressDto) SetAddress(v string) {
	o.Address = v
}

func (o ChainAddressDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChainAddressDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chain"] = o.Chain
	toSerialize["address"] = o.Address
	return toSerialize, nil
}

func (o *ChainAddressDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"chain",
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChainAddressDto := _ChainAddressDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChainAddressDto)

	if err != nil {
		return err
	}

	*o = ChainAddressDto(varChainAddressDto)

	return err
}

type NullableChainAddressDto struct {
	value *ChainAddressDto
	isSet bool
}

func (v NullableChainAddressDto) Get() *ChainAddressDto {
	return v.value
}

func (v *NullableChainAddressDto) Set(val *ChainAddressDto) {
	v.value = val
	v.isSet = true
}

func (v NullableChainAddressDto) IsSet() bool {
	return v.isSet
}

func (v *NullableChainAddressDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChainAddressDto(val *ChainAddressDto) *NullableChainAddressDto {
	return &NullableChainAddressDto{value: val, isSet: true}
}

func (v NullableChainAddressDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChainAddressDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
