/*
UniswapX

REST API for retrieving signed UniswapX orders. Dutch (V1/V2/V3), Priority, Hybrid, and Relay orders are served by /orders; limit orders are served by /limit-orders. Order submission is handled by the Uniswap Trading API and is not part of this specification.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uniswapxservice

import (
	"encoding/json"
	"fmt"
)

// SortKey the model 'SortKey'
type SortKey string

// List of SortKey
const (
	CREATED_AT SortKey = "createdAt"
)

// All allowed values of SortKey enum
var AllowedSortKeyEnumValues = []SortKey{
	"createdAt",
}

func (v *SortKey) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SortKey(value)
	for _, existing := range AllowedSortKeyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SortKey", value)
}

// NewSortKeyFromValue returns a pointer to a valid SortKey
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSortKeyFromValue(v string) (*SortKey, error) {
	ev := SortKey(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SortKey: valid values are %v", v, AllowedSortKeyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SortKey) IsValid() bool {
	for _, existing := range AllowedSortKeyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SortKey value
func (v SortKey) Ptr() *SortKey {
	return &v
}

type NullableSortKey struct {
	value *SortKey
	isSet bool
}

func (v NullableSortKey) Get() *SortKey {
	return v.value
}

func (v *NullableSortKey) Set(val *SortKey) {
	v.value = val
	v.isSet = true
}

func (v NullableSortKey) IsSet() bool {
	return v.isSet
}

func (v *NullableSortKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSortKey(val *SortKey) *NullableSortKey {
	return &NullableSortKey{value: val, isSet: true}
}

func (v NullableSortKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSortKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
