/*
UniswapX

REST API for retrieving signed UniswapX orders. Dutch (V1/V2/V3), Priority, Hybrid, and Relay orders are served by /orders; limit orders are served by /limit-orders. Order submission is handled by the Uniswap Trading API and is not part of this specification.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uniswapxservice

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DutchV3OrderEntityOutputsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DutchV3OrderEntityOutputsInner{}

// DutchV3OrderEntityOutputsInner struct for DutchV3OrderEntityOutputsInner
type DutchV3OrderEntityOutputsInner struct {
	// EIP-55 checksummed Ethereum address.
	Token string `json:"token"`
	// uint256 encoded as a base-10 string.
	StartAmount string                    `json:"startAmount" validate:"regexp=^[0-9]{1,78}$"`
	Curve       *NonlinearDutchDecayCurve `json:"curve,omitempty"`
	// EIP-55 checksummed Ethereum address.
	Recipient string `json:"recipient"`
	// uint256 encoded as a base-10 string.
	MinAmount *string `json:"minAmount,omitempty" validate:"regexp=^[0-9]{1,78}$"`
	// uint256 encoded as a base-10 string.
	AdjustmentPerGweiBaseFee *string `json:"adjustmentPerGweiBaseFee,omitempty" validate:"regexp=^[0-9]{1,78}$"`
}

type _DutchV3OrderEntityOutputsInner DutchV3OrderEntityOutputsInner

// NewDutchV3OrderEntityOutputsInner instantiates a new DutchV3OrderEntityOutputsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDutchV3OrderEntityOutputsInner(token string, startAmount string, recipient string) *DutchV3OrderEntityOutputsInner {
	this := DutchV3OrderEntityOutputsInner{}
	this.Token = token
	this.StartAmount = startAmount
	this.Recipient = recipient
	return &this
}

// NewDutchV3OrderEntityOutputsInnerWithDefaults instantiates a new DutchV3OrderEntityOutputsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDutchV3OrderEntityOutputsInnerWithDefaults() *DutchV3OrderEntityOutputsInner {
	this := DutchV3OrderEntityOutputsInner{}
	return &this
}

// GetToken returns the Token field value
func (o *DutchV3OrderEntityOutputsInner) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *DutchV3OrderEntityOutputsInner) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *DutchV3OrderEntityOutputsInner) SetToken(v string) {
	o.Token = v
}

// GetStartAmount returns the StartAmount field value
func (o *DutchV3OrderEntityOutputsInner) GetStartAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartAmount
}

// GetStartAmountOk returns a tuple with the StartAmount field value
// and a boolean to check if the value has been set.
func (o *DutchV3OrderEntityOutputsInner) GetStartAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartAmount, true
}

// SetStartAmount sets field value
func (o *DutchV3OrderEntityOutputsInner) SetStartAmount(v string) {
	o.StartAmount = v
}

// GetCurve returns the Curve field value if set, zero value otherwise.
func (o *DutchV3OrderEntityOutputsInner) GetCurve() NonlinearDutchDecayCurve {
	if o == nil || IsNil(o.Curve) {
		var ret NonlinearDutchDecayCurve
		return ret
	}
	return *o.Curve
}

// GetCurveOk returns a tuple with the Curve field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DutchV3OrderEntityOutputsInner) GetCurveOk() (*NonlinearDutchDecayCurve, bool) {
	if o == nil || IsNil(o.Curve) {
		return nil, false
	}
	return o.Curve, true
}

// HasCurve returns a boolean if a field has been set.
func (o *DutchV3OrderEntityOutputsInner) HasCurve() bool {
	if o != nil && !IsNil(o.Curve) {
		return true
	}

	return false
}

// SetCurve gets a reference to the given NonlinearDutchDecayCurve and assigns it to the Curve field.
func (o *DutchV3OrderEntityOutputsInner) SetCurve(v NonlinearDutchDecayCurve) {
	o.Curve = &v
}

// GetRecipient returns the Recipient field value
func (o *DutchV3OrderEntityOutputsInner) GetRecipient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value
// and a boolean to check if the value has been set.
func (o *DutchV3OrderEntityOutputsInner) GetRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recipient, true
}

// SetRecipient sets field value
func (o *DutchV3OrderEntityOutputsInner) SetRecipient(v string) {
	o.Recipient = v
}

// GetMinAmount returns the MinAmount field value if set, zero value otherwise.
func (o *DutchV3OrderEntityOutputsInner) GetMinAmount() string {
	if o == nil || IsNil(o.MinAmount) {
		var ret string
		return ret
	}
	return *o.MinAmount
}

// GetMinAmountOk returns a tuple with the MinAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DutchV3OrderEntityOutputsInner) GetMinAmountOk() (*string, bool) {
	if o == nil || IsNil(o.MinAmount) {
		return nil, false
	}
	return o.MinAmount, true
}

// HasMinAmount returns a boolean if a field has been set.
func (o *DutchV3OrderEntityOutputsInner) HasMinAmount() bool {
	if o != nil && !IsNil(o.MinAmount) {
		return true
	}

	return false
}

// SetMinAmount gets a reference to the given string and assigns it to the MinAmount field.
func (o *DutchV3OrderEntityOutputsInner) SetMinAmount(v string) {
	o.MinAmount = &v
}

// GetAdjustmentPerGweiBaseFee returns the AdjustmentPerGweiBaseFee field value if set, zero value otherwise.
func (o *DutchV3OrderEntityOutputsInner) GetAdjustmentPerGweiBaseFee() string {
	if o == nil || IsNil(o.AdjustmentPerGweiBaseFee) {
		var ret string
		return ret
	}
	return *o.AdjustmentPerGweiBaseFee
}

// GetAdjustmentPerGweiBaseFeeOk returns a tuple with the AdjustmentPerGweiBaseFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DutchV3OrderEntityOutputsInner) GetAdjustmentPerGweiBaseFeeOk() (*string, bool) {
	if o == nil || IsNil(o.AdjustmentPerGweiBaseFee) {
		return nil, false
	}
	return o.AdjustmentPerGweiBaseFee, true
}

// HasAdjustmentPerGweiBaseFee returns a boolean if a field has been set.
func (o *DutchV3OrderEntityOutputsInner) HasAdjustmentPerGweiBaseFee() bool {
	if o != nil && !IsNil(o.AdjustmentPerGweiBaseFee) {
		return true
	}

	return false
}

// SetAdjustmentPerGweiBaseFee gets a reference to the given string and assigns it to the AdjustmentPerGweiBaseFee field.
func (o *DutchV3OrderEntityOutputsInner) SetAdjustmentPerGweiBaseFee(v string) {
	o.AdjustmentPerGweiBaseFee = &v
}

func (o DutchV3OrderEntityOutputsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DutchV3OrderEntityOutputsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	toSerialize["startAmount"] = o.StartAmount
	if !IsNil(o.Curve) {
		toSerialize["curve"] = o.Curve
	}
	toSerialize["recipient"] = o.Recipient
	if !IsNil(o.MinAmount) {
		toSerialize["minAmount"] = o.MinAmount
	}
	if !IsNil(o.AdjustmentPerGweiBaseFee) {
		toSerialize["adjustmentPerGweiBaseFee"] = o.AdjustmentPerGweiBaseFee
	}
	return toSerialize, nil
}

func (o *DutchV3OrderEntityOutputsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
		"startAmount",
		"recipient",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDutchV3OrderEntityOutputsInner := _DutchV3OrderEntityOutputsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDutchV3OrderEntityOutputsInner)

	if err != nil {
		return err
	}

	*o = DutchV3OrderEntityOutputsInner(varDutchV3OrderEntityOutputsInner)

	return err
}

type NullableDutchV3OrderEntityOutputsInner struct {
	value *DutchV3OrderEntityOutputsInner
	isSet bool
}

func (v NullableDutchV3OrderEntityOutputsInner) Get() *DutchV3OrderEntityOutputsInner {
	return v.value
}

func (v *NullableDutchV3OrderEntityOutputsInner) Set(val *DutchV3OrderEntityOutputsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDutchV3OrderEntityOutputsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDutchV3OrderEntityOutputsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDutchV3OrderEntityOutputsInner(val *DutchV3OrderEntityOutputsInner) *NullableDutchV3OrderEntityOutputsInner {
	return &NullableDutchV3OrderEntityOutputsInner{value: val, isSet: true}
}

func (v NullableDutchV3OrderEntityOutputsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDutchV3OrderEntityOutputsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
