/*
UniswapX

REST API for retrieving signed UniswapX orders. Dutch (V1/V2/V3), Priority, Hybrid, and Relay orders are served by /orders; limit orders are served by /limit-orders. Order submission is handled by the Uniswap Trading API and is not part of this specification.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uniswapxservice

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PriorityOrderEntityOutputsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PriorityOrderEntityOutputsInner{}

// PriorityOrderEntityOutputsInner struct for PriorityOrderEntityOutputsInner
type PriorityOrderEntityOutputsInner struct {
	// EIP-55 checksummed Ethereum address.
	Token string `json:"token"`
	// uint256 encoded as a base-10 string.
	Amount string `json:"amount" validate:"regexp=^[0-9]{1,78}$"`
	// uint256 encoded as a base-10 string.
	MpsPerPriorityFeeWei string `json:"mpsPerPriorityFeeWei" validate:"regexp=^[0-9]{1,78}$"`
	// EIP-55 checksummed Ethereum address.
	Recipient string `json:"recipient"`
}

type _PriorityOrderEntityOutputsInner PriorityOrderEntityOutputsInner

// NewPriorityOrderEntityOutputsInner instantiates a new PriorityOrderEntityOutputsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPriorityOrderEntityOutputsInner(token string, amount string, mpsPerPriorityFeeWei string, recipient string) *PriorityOrderEntityOutputsInner {
	this := PriorityOrderEntityOutputsInner{}
	this.Token = token
	this.Amount = amount
	this.MpsPerPriorityFeeWei = mpsPerPriorityFeeWei
	this.Recipient = recipient
	return &this
}

// NewPriorityOrderEntityOutputsInnerWithDefaults instantiates a new PriorityOrderEntityOutputsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPriorityOrderEntityOutputsInnerWithDefaults() *PriorityOrderEntityOutputsInner {
	this := PriorityOrderEntityOutputsInner{}
	return &this
}

// GetToken returns the Token field value
func (o *PriorityOrderEntityOutputsInner) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *PriorityOrderEntityOutputsInner) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *PriorityOrderEntityOutputsInner) SetToken(v string) {
	o.Token = v
}

// GetAmount returns the Amount field value
func (o *PriorityOrderEntityOutputsInner) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *PriorityOrderEntityOutputsInner) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *PriorityOrderEntityOutputsInner) SetAmount(v string) {
	o.Amount = v
}

// GetMpsPerPriorityFeeWei returns the MpsPerPriorityFeeWei field value
func (o *PriorityOrderEntityOutputsInner) GetMpsPerPriorityFeeWei() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MpsPerPriorityFeeWei
}

// GetMpsPerPriorityFeeWeiOk returns a tuple with the MpsPerPriorityFeeWei field value
// and a boolean to check if the value has been set.
func (o *PriorityOrderEntityOutputsInner) GetMpsPerPriorityFeeWeiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MpsPerPriorityFeeWei, true
}

// SetMpsPerPriorityFeeWei sets field value
func (o *PriorityOrderEntityOutputsInner) SetMpsPerPriorityFeeWei(v string) {
	o.MpsPerPriorityFeeWei = v
}

// GetRecipient returns the Recipient field value
func (o *PriorityOrderEntityOutputsInner) GetRecipient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value
// and a boolean to check if the value has been set.
func (o *PriorityOrderEntityOutputsInner) GetRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recipient, true
}

// SetRecipient sets field value
func (o *PriorityOrderEntityOutputsInner) SetRecipient(v string) {
	o.Recipient = v
}

func (o PriorityOrderEntityOutputsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PriorityOrderEntityOutputsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	toSerialize["amount"] = o.Amount
	toSerialize["mpsPerPriorityFeeWei"] = o.MpsPerPriorityFeeWei
	toSerialize["recipient"] = o.Recipient
	return toSerialize, nil
}

func (o *PriorityOrderEntityOutputsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
		"amount",
		"mpsPerPriorityFeeWei",
		"recipient",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPriorityOrderEntityOutputsInner := _PriorityOrderEntityOutputsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPriorityOrderEntityOutputsInner)

	if err != nil {
		return err
	}

	*o = PriorityOrderEntityOutputsInner(varPriorityOrderEntityOutputsInner)

	return err
}

type NullablePriorityOrderEntityOutputsInner struct {
	value *PriorityOrderEntityOutputsInner
	isSet bool
}

func (v NullablePriorityOrderEntityOutputsInner) Get() *PriorityOrderEntityOutputsInner {
	return v.value
}

func (v *NullablePriorityOrderEntityOutputsInner) Set(val *PriorityOrderEntityOutputsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePriorityOrderEntityOutputsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePriorityOrderEntityOutputsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePriorityOrderEntityOutputsInner(val *PriorityOrderEntityOutputsInner) *NullablePriorityOrderEntityOutputsInner {
	return &NullablePriorityOrderEntityOutputsInner{value: val, isSet: true}
}

func (v NullablePriorityOrderEntityOutputsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePriorityOrderEntityOutputsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
