/*
UniswapX

REST API for retrieving signed UniswapX orders. Dutch (V1/V2/V3), Priority, Hybrid, and Relay orders are served by /orders; limit orders are served by /limit-orders. Order submission is handled by the Uniswap Trading API and is not part of this specification.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uniswapxservice

import (
	"encoding/json"
)

// checks if the GetOrdersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrdersResponse{}

// GetOrdersResponse struct for GetOrdersResponse
type GetOrdersResponse struct {
	Orders []GetOrdersResponseOrdersInner `json:"orders,omitempty"`
	// GET /limit-orders only. Defined when the results are paginated; pass back via the cursor query parameter to fetch the next page.
	Cursor               *string `json:"cursor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetOrdersResponse GetOrdersResponse

// NewGetOrdersResponse instantiates a new GetOrdersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrdersResponse() *GetOrdersResponse {
	this := GetOrdersResponse{}
	return &this
}

// NewGetOrdersResponseWithDefaults instantiates a new GetOrdersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrdersResponseWithDefaults() *GetOrdersResponse {
	this := GetOrdersResponse{}
	return &this
}

// GetOrders returns the Orders field value if set, zero value otherwise.
func (o *GetOrdersResponse) GetOrders() []GetOrdersResponseOrdersInner {
	if o == nil || IsNil(o.Orders) {
		var ret []GetOrdersResponseOrdersInner
		return ret
	}
	return o.Orders
}

// GetOrdersOk returns a tuple with the Orders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersResponse) GetOrdersOk() ([]GetOrdersResponseOrdersInner, bool) {
	if o == nil || IsNil(o.Orders) {
		return nil, false
	}
	return o.Orders, true
}

// HasOrders returns a boolean if a field has been set.
func (o *GetOrdersResponse) HasOrders() bool {
	if o != nil && !IsNil(o.Orders) {
		return true
	}

	return false
}

// SetOrders gets a reference to the given []GetOrdersResponseOrdersInner and assigns it to the Orders field.
func (o *GetOrdersResponse) SetOrders(v []GetOrdersResponseOrdersInner) {
	o.Orders = v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *GetOrdersResponse) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrdersResponse) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *GetOrdersResponse) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *GetOrdersResponse) SetCursor(v string) {
	o.Cursor = &v
}

func (o GetOrdersResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrdersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Orders) {
		toSerialize["orders"] = o.Orders
	}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetOrdersResponse) UnmarshalJSON(data []byte) (err error) {
	varGetOrdersResponse := _GetOrdersResponse{}

	err = json.Unmarshal(data, &varGetOrdersResponse)

	if err != nil {
		return err
	}

	*o = GetOrdersResponse(varGetOrdersResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "orders")
		delete(additionalProperties, "cursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetOrdersResponse struct {
	value *GetOrdersResponse
	isSet bool
}

func (v NullableGetOrdersResponse) Get() *GetOrdersResponse {
	return v.value
}

func (v *NullableGetOrdersResponse) Set(val *GetOrdersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrdersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrdersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrdersResponse(val *GetOrdersResponse) *NullableGetOrdersResponse {
	return &NullableGetOrdersResponse{value: val, isSet: true}
}

func (v NullableGetOrdersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrdersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
