/*
UniswapX

REST API for retrieving signed UniswapX orders. Dutch (V1/V2/V3), Priority, Hybrid, and Relay orders are served by /orders; limit orders are served by /limit-orders. Order submission is handled by the Uniswap Trading API and is not part of this specification.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uniswapxservice

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HybridOrderEntityInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HybridOrderEntityInput{}

// HybridOrderEntityInput struct for HybridOrderEntityInput
type HybridOrderEntityInput struct {
	// EIP-55 checksummed Ethereum address.
	Token string `json:"token"`
	// uint256 encoded as a base-10 string.
	MaxAmount string `json:"maxAmount" validate:"regexp=^[0-9]{1,78}$"`
}

type _HybridOrderEntityInput HybridOrderEntityInput

// NewHybridOrderEntityInput instantiates a new HybridOrderEntityInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHybridOrderEntityInput(token string, maxAmount string) *HybridOrderEntityInput {
	this := HybridOrderEntityInput{}
	this.Token = token
	this.MaxAmount = maxAmount
	return &this
}

// NewHybridOrderEntityInputWithDefaults instantiates a new HybridOrderEntityInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHybridOrderEntityInputWithDefaults() *HybridOrderEntityInput {
	this := HybridOrderEntityInput{}
	return &this
}

// GetToken returns the Token field value
func (o *HybridOrderEntityInput) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *HybridOrderEntityInput) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *HybridOrderEntityInput) SetToken(v string) {
	o.Token = v
}

// GetMaxAmount returns the MaxAmount field value
func (o *HybridOrderEntityInput) GetMaxAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MaxAmount
}

// GetMaxAmountOk returns a tuple with the MaxAmount field value
// and a boolean to check if the value has been set.
func (o *HybridOrderEntityInput) GetMaxAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxAmount, true
}

// SetMaxAmount sets field value
func (o *HybridOrderEntityInput) SetMaxAmount(v string) {
	o.MaxAmount = v
}

func (o HybridOrderEntityInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HybridOrderEntityInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	toSerialize["maxAmount"] = o.MaxAmount
	return toSerialize, nil
}

func (o *HybridOrderEntityInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
		"maxAmount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHybridOrderEntityInput := _HybridOrderEntityInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHybridOrderEntityInput)

	if err != nil {
		return err
	}

	*o = HybridOrderEntityInput(varHybridOrderEntityInput)

	return err
}

type NullableHybridOrderEntityInput struct {
	value *HybridOrderEntityInput
	isSet bool
}

func (v NullableHybridOrderEntityInput) Get() *HybridOrderEntityInput {
	return v.value
}

func (v *NullableHybridOrderEntityInput) Set(val *HybridOrderEntityInput) {
	v.value = val
	v.isSet = true
}

func (v NullableHybridOrderEntityInput) IsSet() bool {
	return v.isSet
}

func (v *NullableHybridOrderEntityInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHybridOrderEntityInput(val *HybridOrderEntityInput) *NullableHybridOrderEntityInput {
	return &NullableHybridOrderEntityInput{value: val, isSet: true}
}

func (v NullableHybridOrderEntityInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHybridOrderEntityInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
