/*
UniswapX

REST API for retrieving signed UniswapX orders. Dutch (V1/V2/V3), Priority, Hybrid, and Relay orders are served by /orders; limit orders are served by /limit-orders. Order submission is handled by the Uniswap Trading API and is not part of this specification.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uniswapxservice

import (
	"encoding/json"
)

// checks if the Route type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Route{}

// Route Classic-route quote metadata associated with the order's quote.
type Route struct {
	// uint256 encoded as a base-10 string.
	Quote *string `json:"quote,omitempty" validate:"regexp=^[0-9]{1,78}$"`
	// uint256 encoded as a base-10 string.
	QuoteGasAdjusted *string `json:"quoteGasAdjusted,omitempty" validate:"regexp=^[0-9]{1,78}$"`
	// uint256 encoded as a base-10 string.
	GasPriceWei *string `json:"gasPriceWei,omitempty" validate:"regexp=^[0-9]{1,78}$"`
	// uint256 encoded as a base-10 string.
	GasUseEstimateQuote *string `json:"gasUseEstimateQuote,omitempty" validate:"regexp=^[0-9]{1,78}$"`
	// uint256 encoded as a base-10 string.
	GasUseEstimate   *string                `json:"gasUseEstimate,omitempty" validate:"regexp=^[0-9]{1,78}$"`
	MethodParameters *RouteMethodParameters `json:"methodParameters,omitempty"`
}

// NewRoute instantiates a new Route object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoute() *Route {
	this := Route{}
	return &this
}

// NewRouteWithDefaults instantiates a new Route object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRouteWithDefaults() *Route {
	this := Route{}
	return &this
}

// GetQuote returns the Quote field value if set, zero value otherwise.
func (o *Route) GetQuote() string {
	if o == nil || IsNil(o.Quote) {
		var ret string
		return ret
	}
	return *o.Quote
}

// GetQuoteOk returns a tuple with the Quote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Route) GetQuoteOk() (*string, bool) {
	if o == nil || IsNil(o.Quote) {
		return nil, false
	}
	return o.Quote, true
}

// HasQuote returns a boolean if a field has been set.
func (o *Route) HasQuote() bool {
	if o != nil && !IsNil(o.Quote) {
		return true
	}

	return false
}

// SetQuote gets a reference to the given string and assigns it to the Quote field.
func (o *Route) SetQuote(v string) {
	o.Quote = &v
}

// GetQuoteGasAdjusted returns the QuoteGasAdjusted field value if set, zero value otherwise.
func (o *Route) GetQuoteGasAdjusted() string {
	if o == nil || IsNil(o.QuoteGasAdjusted) {
		var ret string
		return ret
	}
	return *o.QuoteGasAdjusted
}

// GetQuoteGasAdjustedOk returns a tuple with the QuoteGasAdjusted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Route) GetQuoteGasAdjustedOk() (*string, bool) {
	if o == nil || IsNil(o.QuoteGasAdjusted) {
		return nil, false
	}
	return o.QuoteGasAdjusted, true
}

// HasQuoteGasAdjusted returns a boolean if a field has been set.
func (o *Route) HasQuoteGasAdjusted() bool {
	if o != nil && !IsNil(o.QuoteGasAdjusted) {
		return true
	}

	return false
}

// SetQuoteGasAdjusted gets a reference to the given string and assigns it to the QuoteGasAdjusted field.
func (o *Route) SetQuoteGasAdjusted(v string) {
	o.QuoteGasAdjusted = &v
}

// GetGasPriceWei returns the GasPriceWei field value if set, zero value otherwise.
func (o *Route) GetGasPriceWei() string {
	if o == nil || IsNil(o.GasPriceWei) {
		var ret string
		return ret
	}
	return *o.GasPriceWei
}

// GetGasPriceWeiOk returns a tuple with the GasPriceWei field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Route) GetGasPriceWeiOk() (*string, bool) {
	if o == nil || IsNil(o.GasPriceWei) {
		return nil, false
	}
	return o.GasPriceWei, true
}

// HasGasPriceWei returns a boolean if a field has been set.
func (o *Route) HasGasPriceWei() bool {
	if o != nil && !IsNil(o.GasPriceWei) {
		return true
	}

	return false
}

// SetGasPriceWei gets a reference to the given string and assigns it to the GasPriceWei field.
func (o *Route) SetGasPriceWei(v string) {
	o.GasPriceWei = &v
}

// GetGasUseEstimateQuote returns the GasUseEstimateQuote field value if set, zero value otherwise.
func (o *Route) GetGasUseEstimateQuote() string {
	if o == nil || IsNil(o.GasUseEstimateQuote) {
		var ret string
		return ret
	}
	return *o.GasUseEstimateQuote
}

// GetGasUseEstimateQuoteOk returns a tuple with the GasUseEstimateQuote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Route) GetGasUseEstimateQuoteOk() (*string, bool) {
	if o == nil || IsNil(o.GasUseEstimateQuote) {
		return nil, false
	}
	return o.GasUseEstimateQuote, true
}

// HasGasUseEstimateQuote returns a boolean if a field has been set.
func (o *Route) HasGasUseEstimateQuote() bool {
	if o != nil && !IsNil(o.GasUseEstimateQuote) {
		return true
	}

	return false
}

// SetGasUseEstimateQuote gets a reference to the given string and assigns it to the GasUseEstimateQuote field.
func (o *Route) SetGasUseEstimateQuote(v string) {
	o.GasUseEstimateQuote = &v
}

// GetGasUseEstimate returns the GasUseEstimate field value if set, zero value otherwise.
func (o *Route) GetGasUseEstimate() string {
	if o == nil || IsNil(o.GasUseEstimate) {
		var ret string
		return ret
	}
	return *o.GasUseEstimate
}

// GetGasUseEstimateOk returns a tuple with the GasUseEstimate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Route) GetGasUseEstimateOk() (*string, bool) {
	if o == nil || IsNil(o.GasUseEstimate) {
		return nil, false
	}
	return o.GasUseEstimate, true
}

// HasGasUseEstimate returns a boolean if a field has been set.
func (o *Route) HasGasUseEstimate() bool {
	if o != nil && !IsNil(o.GasUseEstimate) {
		return true
	}

	return false
}

// SetGasUseEstimate gets a reference to the given string and assigns it to the GasUseEstimate field.
func (o *Route) SetGasUseEstimate(v string) {
	o.GasUseEstimate = &v
}

// GetMethodParameters returns the MethodParameters field value if set, zero value otherwise.
func (o *Route) GetMethodParameters() RouteMethodParameters {
	if o == nil || IsNil(o.MethodParameters) {
		var ret RouteMethodParameters
		return ret
	}
	return *o.MethodParameters
}

// GetMethodParametersOk returns a tuple with the MethodParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Route) GetMethodParametersOk() (*RouteMethodParameters, bool) {
	if o == nil || IsNil(o.MethodParameters) {
		return nil, false
	}
	return o.MethodParameters, true
}

// HasMethodParameters returns a boolean if a field has been set.
func (o *Route) HasMethodParameters() bool {
	if o != nil && !IsNil(o.MethodParameters) {
		return true
	}

	return false
}

// SetMethodParameters gets a reference to the given RouteMethodParameters and assigns it to the MethodParameters field.
func (o *Route) SetMethodParameters(v RouteMethodParameters) {
	o.MethodParameters = &v
}

func (o Route) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Route) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Quote) {
		toSerialize["quote"] = o.Quote
	}
	if !IsNil(o.QuoteGasAdjusted) {
		toSerialize["quoteGasAdjusted"] = o.QuoteGasAdjusted
	}
	if !IsNil(o.GasPriceWei) {
		toSerialize["gasPriceWei"] = o.GasPriceWei
	}
	if !IsNil(o.GasUseEstimateQuote) {
		toSerialize["gasUseEstimateQuote"] = o.GasUseEstimateQuote
	}
	if !IsNil(o.GasUseEstimate) {
		toSerialize["gasUseEstimate"] = o.GasUseEstimate
	}
	if !IsNil(o.MethodParameters) {
		toSerialize["methodParameters"] = o.MethodParameters
	}
	return toSerialize, nil
}

type NullableRoute struct {
	value *Route
	isSet bool
}

func (v NullableRoute) Get() *Route {
	return v.value
}

func (v *NullableRoute) Set(val *Route) {
	v.value = val
	v.isSet = true
}

func (v NullableRoute) IsSet() bool {
	return v.isSet
}

func (v *NullableRoute) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoute(val *Route) *NullableRoute {
	return &NullableRoute{value: val, isSet: true}
}

func (v NullableRoute) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoute) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
