/*
BF API Reference

BP subdomain API documentation for bf.dev.gcp.3f.xyz

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package threef

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AuctionDepositAssetDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuctionDepositAssetDto{}

// AuctionDepositAssetDto struct for AuctionDepositAssetDto
type AuctionDepositAssetDto struct {
	// Deposit (stablecoin) token contract address
	Address string `json:"address"`
	// Deposit token symbol (ERC-20 ticker)
	Symbol string `json:"symbol"`
	// Deposit token decimals
	Decimals float32 `json:"decimals"`
}

type _AuctionDepositAssetDto AuctionDepositAssetDto

// NewAuctionDepositAssetDto instantiates a new AuctionDepositAssetDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuctionDepositAssetDto(address string, symbol string, decimals float32) *AuctionDepositAssetDto {
	this := AuctionDepositAssetDto{}
	this.Address = address
	this.Symbol = symbol
	this.Decimals = decimals
	return &this
}

// NewAuctionDepositAssetDtoWithDefaults instantiates a new AuctionDepositAssetDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuctionDepositAssetDtoWithDefaults() *AuctionDepositAssetDto {
	this := AuctionDepositAssetDto{}
	return &this
}

// GetAddress returns the Address field value
func (o *AuctionDepositAssetDto) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *AuctionDepositAssetDto) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *AuctionDepositAssetDto) SetAddress(v string) {
	o.Address = v
}

// GetSymbol returns the Symbol field value
func (o *AuctionDepositAssetDto) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *AuctionDepositAssetDto) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *AuctionDepositAssetDto) SetSymbol(v string) {
	o.Symbol = v
}

// GetDecimals returns the Decimals field value
func (o *AuctionDepositAssetDto) GetDecimals() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Decimals
}

// GetDecimalsOk returns a tuple with the Decimals field value
// and a boolean to check if the value has been set.
func (o *AuctionDepositAssetDto) GetDecimalsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decimals, true
}

// SetDecimals sets field value
func (o *AuctionDepositAssetDto) SetDecimals(v float32) {
	o.Decimals = v
}

func (o AuctionDepositAssetDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuctionDepositAssetDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["symbol"] = o.Symbol
	toSerialize["decimals"] = o.Decimals
	return toSerialize, nil
}

func (o *AuctionDepositAssetDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"symbol",
		"decimals",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuctionDepositAssetDto := _AuctionDepositAssetDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuctionDepositAssetDto)

	if err != nil {
		return err
	}

	*o = AuctionDepositAssetDto(varAuctionDepositAssetDto)

	return err
}

type NullableAuctionDepositAssetDto struct {
	value *AuctionDepositAssetDto
	isSet bool
}

func (v NullableAuctionDepositAssetDto) Get() *AuctionDepositAssetDto {
	return v.value
}

func (v *NullableAuctionDepositAssetDto) Set(val *AuctionDepositAssetDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAuctionDepositAssetDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAuctionDepositAssetDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuctionDepositAssetDto(val *AuctionDepositAssetDto) *NullableAuctionDepositAssetDto {
	return &NullableAuctionDepositAssetDto{value: val, isSet: true}
}

func (v NullableAuctionDepositAssetDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuctionDepositAssetDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
