/*
BF API Reference

BP subdomain API documentation for bf.dev.gcp.3f.xyz

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package threef

import (
	"encoding/json"
)

// checks if the GetFacilitatorOfferAddressResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFacilitatorOfferAddressResponseDto{}

// GetFacilitatorOfferAddressResponseDto struct for GetFacilitatorOfferAddressResponseDto
type GetFacilitatorOfferAddressResponseDto struct {
	// Facilitator address associated with the API key
	Facilitator string `json:"facilitator"`
	// Current offer address for the facilitator
	OfferAddress         string `json:"offerAddress"`
	AdditionalProperties map[string]interface{}
}

type _GetFacilitatorOfferAddressResponseDto GetFacilitatorOfferAddressResponseDto

// NewGetFacilitatorOfferAddressResponseDto instantiates a new GetFacilitatorOfferAddressResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFacilitatorOfferAddressResponseDto(facilitator string, offerAddress string) *GetFacilitatorOfferAddressResponseDto {
	this := GetFacilitatorOfferAddressResponseDto{}
	this.Facilitator = facilitator
	this.OfferAddress = offerAddress
	return &this
}

// NewGetFacilitatorOfferAddressResponseDtoWithDefaults instantiates a new GetFacilitatorOfferAddressResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFacilitatorOfferAddressResponseDtoWithDefaults() *GetFacilitatorOfferAddressResponseDto {
	this := GetFacilitatorOfferAddressResponseDto{}
	return &this
}

// GetFacilitator returns the Facilitator field value
func (o *GetFacilitatorOfferAddressResponseDto) GetFacilitator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Facilitator
}

// GetFacilitatorOk returns a tuple with the Facilitator field value
// and a boolean to check if the value has been set.
func (o *GetFacilitatorOfferAddressResponseDto) GetFacilitatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Facilitator, true
}

// SetFacilitator sets field value
func (o *GetFacilitatorOfferAddressResponseDto) SetFacilitator(v string) {
	o.Facilitator = v
}

// GetOfferAddress returns the OfferAddress field value
func (o *GetFacilitatorOfferAddressResponseDto) GetOfferAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OfferAddress
}

// GetOfferAddressOk returns a tuple with the OfferAddress field value
// and a boolean to check if the value has been set.
func (o *GetFacilitatorOfferAddressResponseDto) GetOfferAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OfferAddress, true
}

// SetOfferAddress sets field value
func (o *GetFacilitatorOfferAddressResponseDto) SetOfferAddress(v string) {
	o.OfferAddress = v
}

func (o GetFacilitatorOfferAddressResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFacilitatorOfferAddressResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["facilitator"] = o.Facilitator
	toSerialize["offerAddress"] = o.OfferAddress

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetFacilitatorOfferAddressResponseDto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varGetFacilitatorOfferAddressResponseDto := _GetFacilitatorOfferAddressResponseDto{}

	err = json.Unmarshal(data, &varGetFacilitatorOfferAddressResponseDto)

	if err != nil {
		return err
	}

	*o = GetFacilitatorOfferAddressResponseDto(varGetFacilitatorOfferAddressResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "facilitator")
		delete(additionalProperties, "offerAddress")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetFacilitatorOfferAddressResponseDto struct {
	value *GetFacilitatorOfferAddressResponseDto
	isSet bool
}

func (v NullableGetFacilitatorOfferAddressResponseDto) Get() *GetFacilitatorOfferAddressResponseDto {
	return v.value
}

func (v *NullableGetFacilitatorOfferAddressResponseDto) Set(val *GetFacilitatorOfferAddressResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFacilitatorOfferAddressResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFacilitatorOfferAddressResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFacilitatorOfferAddressResponseDto(val *GetFacilitatorOfferAddressResponseDto) *NullableGetFacilitatorOfferAddressResponseDto {
	return &NullableGetFacilitatorOfferAddressResponseDto{value: val, isSet: true}
}

func (v NullableGetFacilitatorOfferAddressResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFacilitatorOfferAddressResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
