/*
BF API Reference

BP subdomain API documentation for bf.dev.gcp.3f.xyz

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package threef

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateOfferDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOfferDto{}

// CreateOfferDto struct for CreateOfferDto
type CreateOfferDto struct {
	// Chain ID for resolving the request EIP-712 domain
	ChainId *float32 `json:"chainId,omitempty"`
	// ID of the auction to submit an offer for
	AuctionId float32 `json:"auctionId"`
	// Ethereum address of the offer maker. For unsigned API-key requests, the configured facilitator offer address is used as the stored maker when present.
	Maker string `json:"maker" validate:"regexp=^0x[a-fA-F0-9]{40}$"`
	// Offer amount as a numeric string (uint256)
	Amount string `json:"amount"`
	// Expected yield amount as a numeric string (uint256). Total repayment is `amount + expectedReturn`.
	ExpectedReturn string `json:"expectedReturn"`
	// Nonce for replay protection (uint256)
	Nonce string `json:"nonce"`
	// Offer expiration timestamp (uint256)
	Expiration string `json:"expiration"`
	// Whether to use callback when executing the offer
	UseCallback bool `json:"useCallback"`
	// EIP-712/EIP-1271 signature bytes. Use `0x` while deferred EIP-1271 approval is pending. Required if chainId is provided.
	Signature *string `json:"signature,omitempty"`
}

type _CreateOfferDto CreateOfferDto

// NewCreateOfferDto instantiates a new CreateOfferDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOfferDto(auctionId float32, maker string, amount string, expectedReturn string, nonce string, expiration string, useCallback bool) *CreateOfferDto {
	this := CreateOfferDto{}
	this.AuctionId = auctionId
	this.Maker = maker
	this.Amount = amount
	this.ExpectedReturn = expectedReturn
	this.Nonce = nonce
	this.Expiration = expiration
	this.UseCallback = useCallback
	return &this
}

// NewCreateOfferDtoWithDefaults instantiates a new CreateOfferDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOfferDtoWithDefaults() *CreateOfferDto {
	this := CreateOfferDto{}
	return &this
}

// GetChainId returns the ChainId field value if set, zero value otherwise.
func (o *CreateOfferDto) GetChainId() float32 {
	if o == nil || IsNil(o.ChainId) {
		var ret float32
		return ret
	}
	return *o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOfferDto) GetChainIdOk() (*float32, bool) {
	if o == nil || IsNil(o.ChainId) {
		return nil, false
	}
	return o.ChainId, true
}

// HasChainId returns a boolean if a field has been set.
func (o *CreateOfferDto) HasChainId() bool {
	if o != nil && !IsNil(o.ChainId) {
		return true
	}

	return false
}

// SetChainId gets a reference to the given float32 and assigns it to the ChainId field.
func (o *CreateOfferDto) SetChainId(v float32) {
	o.ChainId = &v
}

// GetAuctionId returns the AuctionId field value
func (o *CreateOfferDto) GetAuctionId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AuctionId
}

// GetAuctionIdOk returns a tuple with the AuctionId field value
// and a boolean to check if the value has been set.
func (o *CreateOfferDto) GetAuctionIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuctionId, true
}

// SetAuctionId sets field value
func (o *CreateOfferDto) SetAuctionId(v float32) {
	o.AuctionId = v
}

// GetMaker returns the Maker field value
func (o *CreateOfferDto) GetMaker() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Maker
}

// GetMakerOk returns a tuple with the Maker field value
// and a boolean to check if the value has been set.
func (o *CreateOfferDto) GetMakerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Maker, true
}

// SetMaker sets field value
func (o *CreateOfferDto) SetMaker(v string) {
	o.Maker = v
}

// GetAmount returns the Amount field value
func (o *CreateOfferDto) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *CreateOfferDto) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *CreateOfferDto) SetAmount(v string) {
	o.Amount = v
}

// GetExpectedReturn returns the ExpectedReturn field value
func (o *CreateOfferDto) GetExpectedReturn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedReturn
}

// GetExpectedReturnOk returns a tuple with the ExpectedReturn field value
// and a boolean to check if the value has been set.
func (o *CreateOfferDto) GetExpectedReturnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedReturn, true
}

// SetExpectedReturn sets field value
func (o *CreateOfferDto) SetExpectedReturn(v string) {
	o.ExpectedReturn = v
}

// GetNonce returns the Nonce field value
func (o *CreateOfferDto) GetNonce() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Nonce
}

// GetNonceOk returns a tuple with the Nonce field value
// and a boolean to check if the value has been set.
func (o *CreateOfferDto) GetNonceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nonce, true
}

// SetNonce sets field value
func (o *CreateOfferDto) SetNonce(v string) {
	o.Nonce = v
}

// GetExpiration returns the Expiration field value
func (o *CreateOfferDto) GetExpiration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Expiration
}

// GetExpirationOk returns a tuple with the Expiration field value
// and a boolean to check if the value has been set.
func (o *CreateOfferDto) GetExpirationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expiration, true
}

// SetExpiration sets field value
func (o *CreateOfferDto) SetExpiration(v string) {
	o.Expiration = v
}

// GetUseCallback returns the UseCallback field value
func (o *CreateOfferDto) GetUseCallback() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.UseCallback
}

// GetUseCallbackOk returns a tuple with the UseCallback field value
// and a boolean to check if the value has been set.
func (o *CreateOfferDto) GetUseCallbackOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UseCallback, true
}

// SetUseCallback sets field value
func (o *CreateOfferDto) SetUseCallback(v bool) {
	o.UseCallback = v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *CreateOfferDto) GetSignature() string {
	if o == nil || IsNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOfferDto) GetSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *CreateOfferDto) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *CreateOfferDto) SetSignature(v string) {
	o.Signature = &v
}

func (o CreateOfferDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOfferDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChainId) {
		toSerialize["chainId"] = o.ChainId
	}
	toSerialize["auctionId"] = o.AuctionId
	toSerialize["maker"] = o.Maker
	toSerialize["amount"] = o.Amount
	toSerialize["expectedReturn"] = o.ExpectedReturn
	toSerialize["nonce"] = o.Nonce
	toSerialize["expiration"] = o.Expiration
	toSerialize["useCallback"] = o.UseCallback
	if !IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	return toSerialize, nil
}

func (o *CreateOfferDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auctionId",
		"maker",
		"amount",
		"expectedReturn",
		"nonce",
		"expiration",
		"useCallback",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOfferDto := _CreateOfferDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOfferDto)

	if err != nil {
		return err
	}

	*o = CreateOfferDto(varCreateOfferDto)

	return err
}

type NullableCreateOfferDto struct {
	value *CreateOfferDto
	isSet bool
}

func (v NullableCreateOfferDto) Get() *CreateOfferDto {
	return v.value
}

func (v *NullableCreateOfferDto) Set(val *CreateOfferDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOfferDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOfferDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOfferDto(val *CreateOfferDto) *NullableCreateOfferDto {
	return &NullableCreateOfferDto{value: val, isSet: true}
}

func (v NullableCreateOfferDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOfferDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
