/*
BF API Reference

BP subdomain API documentation for bf.dev.gcp.3f.xyz

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package threef

import (
	"encoding/json"
)

// checks if the CancelOfferDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelOfferDto{}

// CancelOfferDto struct for CancelOfferDto
type CancelOfferDto struct {
	// Offer ID to cancel
	OfferId float32 `json:"offerId"`
	// Ethereum address of the offer maker
	Maker string `json:"maker" validate:"regexp=^0x[a-fA-F0-9]{40}$"`
	// Chain ID for signature verification
	ChainId *float32 `json:"chainId,omitempty"`
	// Signature deadline timestamp (uint256)
	Deadline *string `json:"deadline,omitempty"`
	// EIP-712 signature (required if chainId is provided)
	Signature            *string `json:"signature,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CancelOfferDto CancelOfferDto

// NewCancelOfferDto instantiates a new CancelOfferDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelOfferDto(offerId float32, maker string) *CancelOfferDto {
	this := CancelOfferDto{}
	this.OfferId = offerId
	this.Maker = maker
	return &this
}

// NewCancelOfferDtoWithDefaults instantiates a new CancelOfferDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelOfferDtoWithDefaults() *CancelOfferDto {
	this := CancelOfferDto{}
	return &this
}

// GetOfferId returns the OfferId field value
func (o *CancelOfferDto) GetOfferId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.OfferId
}

// GetOfferIdOk returns a tuple with the OfferId field value
// and a boolean to check if the value has been set.
func (o *CancelOfferDto) GetOfferIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OfferId, true
}

// SetOfferId sets field value
func (o *CancelOfferDto) SetOfferId(v float32) {
	o.OfferId = v
}

// GetMaker returns the Maker field value
func (o *CancelOfferDto) GetMaker() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Maker
}

// GetMakerOk returns a tuple with the Maker field value
// and a boolean to check if the value has been set.
func (o *CancelOfferDto) GetMakerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Maker, true
}

// SetMaker sets field value
func (o *CancelOfferDto) SetMaker(v string) {
	o.Maker = v
}

// GetChainId returns the ChainId field value if set, zero value otherwise.
func (o *CancelOfferDto) GetChainId() float32 {
	if o == nil || IsNil(o.ChainId) {
		var ret float32
		return ret
	}
	return *o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelOfferDto) GetChainIdOk() (*float32, bool) {
	if o == nil || IsNil(o.ChainId) {
		return nil, false
	}
	return o.ChainId, true
}

// HasChainId returns a boolean if a field has been set.
func (o *CancelOfferDto) HasChainId() bool {
	if o != nil && !IsNil(o.ChainId) {
		return true
	}

	return false
}

// SetChainId gets a reference to the given float32 and assigns it to the ChainId field.
func (o *CancelOfferDto) SetChainId(v float32) {
	o.ChainId = &v
}

// GetDeadline returns the Deadline field value if set, zero value otherwise.
func (o *CancelOfferDto) GetDeadline() string {
	if o == nil || IsNil(o.Deadline) {
		var ret string
		return ret
	}
	return *o.Deadline
}

// GetDeadlineOk returns a tuple with the Deadline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelOfferDto) GetDeadlineOk() (*string, bool) {
	if o == nil || IsNil(o.Deadline) {
		return nil, false
	}
	return o.Deadline, true
}

// HasDeadline returns a boolean if a field has been set.
func (o *CancelOfferDto) HasDeadline() bool {
	if o != nil && !IsNil(o.Deadline) {
		return true
	}

	return false
}

// SetDeadline gets a reference to the given string and assigns it to the Deadline field.
func (o *CancelOfferDto) SetDeadline(v string) {
	o.Deadline = &v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *CancelOfferDto) GetSignature() string {
	if o == nil || IsNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelOfferDto) GetSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *CancelOfferDto) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *CancelOfferDto) SetSignature(v string) {
	o.Signature = &v
}

func (o CancelOfferDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelOfferDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["offerId"] = o.OfferId
	toSerialize["maker"] = o.Maker
	if !IsNil(o.ChainId) {
		toSerialize["chainId"] = o.ChainId
	}
	if !IsNil(o.Deadline) {
		toSerialize["deadline"] = o.Deadline
	}
	if !IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CancelOfferDto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varCancelOfferDto := _CancelOfferDto{}

	err = json.Unmarshal(data, &varCancelOfferDto)

	if err != nil {
		return err
	}

	*o = CancelOfferDto(varCancelOfferDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "offerId")
		delete(additionalProperties, "maker")
		delete(additionalProperties, "chainId")
		delete(additionalProperties, "deadline")
		delete(additionalProperties, "signature")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCancelOfferDto struct {
	value *CancelOfferDto
	isSet bool
}

func (v NullableCancelOfferDto) Get() *CancelOfferDto {
	return v.value
}

func (v *NullableCancelOfferDto) Set(val *CancelOfferDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelOfferDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelOfferDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelOfferDto(val *CancelOfferDto) *NullableCancelOfferDto {
	return &NullableCancelOfferDto{value: val, isSet: true}
}

func (v NullableCancelOfferDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelOfferDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
