/*
BF API Reference

BP subdomain API documentation for bf.dev.gcp.3f.xyz

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package threef

import (
	"encoding/json"
)

// checks if the GenerateFacilitatorApiKeyDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateFacilitatorApiKeyDto{}

// GenerateFacilitatorApiKeyDto struct for GenerateFacilitatorApiKeyDto
type GenerateFacilitatorApiKeyDto struct {
	// Chain ID for EIP-712 signature verification
	ChainId float32 `json:"chainId"`
	// Ethereum address of the facilitator
	Facilitator string `json:"facilitator" validate:"regexp=^0x[a-fA-F0-9]{40}$"`
	// Signature deadline timestamp (uint256)
	Deadline string `json:"deadline"`
	// EIP-712 signature from the facilitator
	Signature            string `json:"signature" validate:"regexp=^0x[a-fA-F0-9]{130}$"`
	AdditionalProperties map[string]interface{}
}

type _GenerateFacilitatorApiKeyDto GenerateFacilitatorApiKeyDto

// NewGenerateFacilitatorApiKeyDto instantiates a new GenerateFacilitatorApiKeyDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateFacilitatorApiKeyDto(chainId float32, facilitator string, deadline string, signature string) *GenerateFacilitatorApiKeyDto {
	this := GenerateFacilitatorApiKeyDto{}
	this.ChainId = chainId
	this.Facilitator = facilitator
	this.Deadline = deadline
	this.Signature = signature
	return &this
}

// NewGenerateFacilitatorApiKeyDtoWithDefaults instantiates a new GenerateFacilitatorApiKeyDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateFacilitatorApiKeyDtoWithDefaults() *GenerateFacilitatorApiKeyDto {
	this := GenerateFacilitatorApiKeyDto{}
	return &this
}

// GetChainId returns the ChainId field value
func (o *GenerateFacilitatorApiKeyDto) GetChainId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *GenerateFacilitatorApiKeyDto) GetChainIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *GenerateFacilitatorApiKeyDto) SetChainId(v float32) {
	o.ChainId = v
}

// GetFacilitator returns the Facilitator field value
func (o *GenerateFacilitatorApiKeyDto) GetFacilitator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Facilitator
}

// GetFacilitatorOk returns a tuple with the Facilitator field value
// and a boolean to check if the value has been set.
func (o *GenerateFacilitatorApiKeyDto) GetFacilitatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Facilitator, true
}

// SetFacilitator sets field value
func (o *GenerateFacilitatorApiKeyDto) SetFacilitator(v string) {
	o.Facilitator = v
}

// GetDeadline returns the Deadline field value
func (o *GenerateFacilitatorApiKeyDto) GetDeadline() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Deadline
}

// GetDeadlineOk returns a tuple with the Deadline field value
// and a boolean to check if the value has been set.
func (o *GenerateFacilitatorApiKeyDto) GetDeadlineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deadline, true
}

// SetDeadline sets field value
func (o *GenerateFacilitatorApiKeyDto) SetDeadline(v string) {
	o.Deadline = v
}

// GetSignature returns the Signature field value
func (o *GenerateFacilitatorApiKeyDto) GetSignature() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value
// and a boolean to check if the value has been set.
func (o *GenerateFacilitatorApiKeyDto) GetSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Signature, true
}

// SetSignature sets field value
func (o *GenerateFacilitatorApiKeyDto) SetSignature(v string) {
	o.Signature = v
}

func (o GenerateFacilitatorApiKeyDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateFacilitatorApiKeyDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chainId"] = o.ChainId
	toSerialize["facilitator"] = o.Facilitator
	toSerialize["deadline"] = o.Deadline
	toSerialize["signature"] = o.Signature

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GenerateFacilitatorApiKeyDto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varGenerateFacilitatorApiKeyDto := _GenerateFacilitatorApiKeyDto{}

	err = json.Unmarshal(data, &varGenerateFacilitatorApiKeyDto)

	if err != nil {
		return err
	}

	*o = GenerateFacilitatorApiKeyDto(varGenerateFacilitatorApiKeyDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "chainId")
		delete(additionalProperties, "facilitator")
		delete(additionalProperties, "deadline")
		delete(additionalProperties, "signature")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGenerateFacilitatorApiKeyDto struct {
	value *GenerateFacilitatorApiKeyDto
	isSet bool
}

func (v NullableGenerateFacilitatorApiKeyDto) Get() *GenerateFacilitatorApiKeyDto {
	return v.value
}

func (v *NullableGenerateFacilitatorApiKeyDto) Set(val *GenerateFacilitatorApiKeyDto) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateFacilitatorApiKeyDto) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateFacilitatorApiKeyDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateFacilitatorApiKeyDto(val *GenerateFacilitatorApiKeyDto) *NullableGenerateFacilitatorApiKeyDto {
	return &NullableGenerateFacilitatorApiKeyDto{value: val, isSet: true}
}

func (v NullableGenerateFacilitatorApiKeyDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateFacilitatorApiKeyDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
