/*
BF API Reference

BP subdomain API documentation for bf.dev.gcp.3f.xyz

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package threef

import (
	"encoding/json"
)

// checks if the SetFacilitatorOfferAddressDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetFacilitatorOfferAddressDto{}

// SetFacilitatorOfferAddressDto struct for SetFacilitatorOfferAddressDto
type SetFacilitatorOfferAddressDto struct {
	// Offer address to associate with the facilitator
	OfferAddress         string `json:"offerAddress" validate:"regexp=^0x[a-fA-F0-9]{40}$"`
	AdditionalProperties map[string]interface{}
}

type _SetFacilitatorOfferAddressDto SetFacilitatorOfferAddressDto

// NewSetFacilitatorOfferAddressDto instantiates a new SetFacilitatorOfferAddressDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetFacilitatorOfferAddressDto(offerAddress string) *SetFacilitatorOfferAddressDto {
	this := SetFacilitatorOfferAddressDto{}
	this.OfferAddress = offerAddress
	return &this
}

// NewSetFacilitatorOfferAddressDtoWithDefaults instantiates a new SetFacilitatorOfferAddressDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetFacilitatorOfferAddressDtoWithDefaults() *SetFacilitatorOfferAddressDto {
	this := SetFacilitatorOfferAddressDto{}
	return &this
}

// GetOfferAddress returns the OfferAddress field value
func (o *SetFacilitatorOfferAddressDto) GetOfferAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OfferAddress
}

// GetOfferAddressOk returns a tuple with the OfferAddress field value
// and a boolean to check if the value has been set.
func (o *SetFacilitatorOfferAddressDto) GetOfferAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OfferAddress, true
}

// SetOfferAddress sets field value
func (o *SetFacilitatorOfferAddressDto) SetOfferAddress(v string) {
	o.OfferAddress = v
}

func (o SetFacilitatorOfferAddressDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetFacilitatorOfferAddressDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["offerAddress"] = o.OfferAddress

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SetFacilitatorOfferAddressDto) UnmarshalJSON(data []byte) (err error) {
	// Required-property validation removed by hack/openapi-relax-client.py:
	// upstream may drop fields at any time; absent values zero-value instead of
	// failing the whole decode.

	varSetFacilitatorOfferAddressDto := _SetFacilitatorOfferAddressDto{}

	err = json.Unmarshal(data, &varSetFacilitatorOfferAddressDto)

	if err != nil {
		return err
	}

	*o = SetFacilitatorOfferAddressDto(varSetFacilitatorOfferAddressDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "offerAddress")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSetFacilitatorOfferAddressDto struct {
	value *SetFacilitatorOfferAddressDto
	isSet bool
}

func (v NullableSetFacilitatorOfferAddressDto) Get() *SetFacilitatorOfferAddressDto {
	return v.value
}

func (v *NullableSetFacilitatorOfferAddressDto) Set(val *SetFacilitatorOfferAddressDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSetFacilitatorOfferAddressDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSetFacilitatorOfferAddressDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetFacilitatorOfferAddressDto(val *SetFacilitatorOfferAddressDto) *NullableSetFacilitatorOfferAddressDto {
	return &NullableSetFacilitatorOfferAddressDto{value: val, isSet: true}
}

func (v NullableSetFacilitatorOfferAddressDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetFacilitatorOfferAddressDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
