/*
BF API Reference

BP subdomain API documentation for bf.dev.gcp.3f.xyz

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package threef

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateOfferResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOfferResponseDto{}

// CreateOfferResponseDto struct for CreateOfferResponseDto
type CreateOfferResponseDto struct {
	// Created or updated offer ID
	Id float32 `json:"id"`
}

type _CreateOfferResponseDto CreateOfferResponseDto

// NewCreateOfferResponseDto instantiates a new CreateOfferResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOfferResponseDto(id float32) *CreateOfferResponseDto {
	this := CreateOfferResponseDto{}
	this.Id = id
	return &this
}

// NewCreateOfferResponseDtoWithDefaults instantiates a new CreateOfferResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOfferResponseDtoWithDefaults() *CreateOfferResponseDto {
	this := CreateOfferResponseDto{}
	return &this
}

// GetId returns the Id field value
func (o *CreateOfferResponseDto) GetId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateOfferResponseDto) GetIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateOfferResponseDto) SetId(v float32) {
	o.Id = v
}

func (o CreateOfferResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOfferResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *CreateOfferResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOfferResponseDto := _CreateOfferResponseDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOfferResponseDto)

	if err != nil {
		return err
	}

	*o = CreateOfferResponseDto(varCreateOfferResponseDto)

	return err
}

type NullableCreateOfferResponseDto struct {
	value *CreateOfferResponseDto
	isSet bool
}

func (v NullableCreateOfferResponseDto) Get() *CreateOfferResponseDto {
	return v.value
}

func (v *NullableCreateOfferResponseDto) Set(val *CreateOfferResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOfferResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOfferResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOfferResponseDto(val *CreateOfferResponseDto) *NullableCreateOfferResponseDto {
	return &NullableCreateOfferResponseDto{value: val, isSet: true}
}

func (v NullableCreateOfferResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOfferResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
