name: Deploy prod

on:
  push:
    branches:
      - 'main'

jobs:
  docker-build-node:
    uses: symbioticfi/github-workflows-common/.github/workflows/docker-build.yml@main
    with:
      target: 'final'
      name: ${{ github.event.repository.name }}/node

  deploy-public-stage:
    name: Deploy ${{ matrix.network }}-symbiotic-fi
    needs:
      - docker-build-node
    strategy:
      fail-fast: false
      matrix:
        network:
          - hoodi
          - sepolia
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      namespace: '${{ matrix.network }}-symbiotic-fi'
      digest: ${{ needs.docker-build-node.outputs.digest }}

  deploy-prod:
    name: Deploy symbiotic-fi
    needs:
      - docker-build-node
      - deploy-public-stage
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      namespace: 'symbiotic-fi'
      digest: ${{ needs.docker-build-node.outputs.digest }}
